### ISSUE TITLE
Create Decision letters/author responses page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#100]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add workflow info (including what we do if decision letters fail/author response videos)
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by FAtherden-eLife** [comment]
@naushinthomson @JGilbert-eLife @bcollins14 @Melissa37, please review https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/decision-letters-and-author-responses

I have a couple of questions:
- In cases where the decision-letter-parser might need work I have included text such as:
> It is worth notifying Fred in the Production team so that he can feed this back to the developer responsible for the decision-letter-parser. 
Is that OK?
- `dec-letter-editor-test-6` - I think I included this because at some point we included these in the Decision letter. It looks like, regardless of what is in the role element, our site displays these as Senior and Reviewing Editors which I presume is wrong because in each case there is actually a Reviewing Editor and separate tagging for an actual Senior and Reviewing Editor. [Here's an example](https://elifesciences.org/articles/39140#SA1). Any reason anyone can think of why I should delete this test?

Please also note that I will fill out the 'Decision letter Word markup for JATS parsing' section once Graham has completed the kitchen sink word document.

**Comment by JGilbert-eLife** [comment]
> (an Author response may not be included in very rare cases, but this is not the norm).

This is going to be the norm for articles reviewed on Review Commons, apparently.

**Comment by JGilbert-eLife** [comment]
For dec-letter-front-test-4, I wonder if it's worth including a description of one common case, which is that the reviewers opted to be anonymous on the first round of review but opted to have their name revealed in a subsequent round of review. This could mean that Editorial include their name in the letter, rather than 'chose to remain anonymous', but they aren't listed in the XML because eJP only outputs non-anonymous reviewers from the full submission.

**Comment by JGilbert-eLife** [comment]
> if it fires in live content,

I wonder if a different term would make more sense - current content? Just a bit worried that 'live' can feasibly cover any content we are working on, whether it's a new version or not.

**Comment by JGilbert-eLife** [comment]
Out of curiosity, why do we have rule dec-letter-reviewer-test-6 rather than just trusting the number of reviewers coming out of eJP? The cases where we have more than three aren't mistakes, after all, just alternative scenarios.

**Comment by JGilbert-eLife** [comment]
> correct the capture of the text.

I suggest simplifying this to 'tag the text as boxed-text'.

**Comment by JGilbert-eLife** [comment]
I think for reply-missing-disp-quote-test-2, it's worth stating explicitly that if the italic text is not a quote from the decision letter, it should be tagged as a disp-quote, as the authors may include quoted paras from their article file in italics.

**Comment by FAtherden-eLife** [comment]
> Out of curiosity, why do we have rule dec-letter-reviewer-test-6 rather than just trusting the number of reviewers coming out of eJP? The cases where we have more than three aren't mistakes, after all, just alternative scenarios. 

I don't trust eJP :smile:. Happy to remove though if it's deemed overly cautious

**Comment by naushinthomson** [comment]
In the 'what needs to be checked' section
>There are no unaddressed Schematron messages relating to the incorrect capture of content in the Decision letter or Author response.
Do we need this here? Is the understanding not that all schematron messages should be addressed where possible?

**Comment by naushinthomson** [comment]
>Question for review - where should these be outlined? They are already explained in detail [here](https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/managing-the-production-inbox#decision-letter-loading). Should they be here instead? In Both places? Or should we just link to [here](https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/managing-the-production-inbox#decision-letter-loading)?]
I think the information about why a decision letter might fail should be on this page and deleted from the managing the inbox page (but with a link added to this page).

**Comment by naushinthomson** [comment]
Is it worth making it clear how we verify that the DL has loaded in Kriya (just checking the dashboard)?

**Comment by naushinthomson** [comment]
This may be a question for the meeting but when might the DL be loaded at post-author stages? I realise you specify that this is unlikely but just wondered what scenario would lead to this :) 

![Screenshot 2020-08-05 at 12 56 04](https://user-images.githubusercontent.com/57144084/89410217-39152f80-d71b-11ea-828e-c6e3a27be498.png)

**Comment by naushinthomson** [comment]
Re: the video loading workflow, I'm a little confused by the flow chart. The pub-check procedure seems to suggest that once Exeter has processed the videos, we send it back to Pre-editing and the DL is loaded once more, then Exeter has to be informed, then we have to verify the DL is loaded. Is that what happens (i.e. the whole process of DL loading happens again)?

**Comment by naushinthomson** [comment]
For the video loading flow chart, the PAV action - should it say 'Exeter processes the video (s)' since this is an Exeter stage? 

![Screenshot 2020-08-05 at 12 55 08](https://user-images.githubusercontent.com/57144084/89410461-a9bc4c00-d71b-11ea-8b0c-6a643ae6fe37.png)

**Comment by naushinthomson** [comment]
> For dec-letter-front-test-4, dec-letter-reviewer-test-1, I wonder if it's worth including a description of one common case, which is that the reviewers opted to be anonymous on the first round of review but opted to have their name revealed in a subsequent round of review. This could mean that Editorial include their name in the letter, rather than 'chose to remain anonymous', but they aren't listed in the XML because eJP only outputs non-anonymous reviewers from the full submission.

This happened recently for article 53249 if that's helpful!

**Comment by naushinthomson** [comment]
For dec-letter-front-test-4

>Every Decision letter should have at least 1 reviewer, unless the reviewers opted to be anonymous, or if the paper was reviewed via Review commons. If this warning fires, Exeter should inform eLife Production. eLife Production should query the eLife Editorial team, asking whether Reviewers need to be included and if so, what their details are (name and optional affiliation).

Is it worth clarifying that Exeter don't need to contact us if the text 'the reviewer(s) opted to remain anonymous' or similar is present?

**Comment by naushinthomson** [comment]
I'm not sure why the actions for reply-missing-disp-quote-test-1 and reply-missing-disp-quote-test-2 are slightly different - should the following text be added to reply-missing-disp-quote-test-1 as well?

>If it is not a quote from the Decision letter, and the text was italic in the original word document, then the text should be left as italics (a relatively common use-case is quoting from the article itself, rather than from the Decision letter).

**Comment by naushinthomson** [comment]
Just a general question but when we format sections of the author response letter as display quotes (e.g. if they're missed), are they automatically captured as @content-type='editor-comment'?

**Comment by naushinthomson** [comment]
I think that's all from me, thanks Fred!

**Comment by FAtherden-eLife** [comment]
> In the 'what needs to be checked' section
>> There are no unaddressed Schematron messages relating to the incorrect capture of content in the Decision letter or Author response.

>Do we need this here? Is the understanding not that all schematron messages should be addressed where possible?

There may be some that can be ignores. I was just trying to think of a concise way of saying that none of the messages which require action are missed. I've tried to re-phrase, but suggestions welcome.

**Comment by FAtherden-eLife** [comment]
> This may be a question for the meeting but when might the DL be loaded at post-author stages? I realise you specify that this is unlikely but just wondered what scenario would lead to this :)

It's quite rare, but an example that comes to hand is a major problem with the parsing of the Decision letter, which Graham has subsequently fixed, and where the simplest fix would be to re-upload the same package.

**Comment by FAtherden-eLife** [comment]
> Re: the video loading workflow, I'm a little confused by the flow chart. The pub-check procedure seems to suggest that once Exeter has processed the videos, we send it back to Pre-editing and the DL is loaded once more, then Exeter has to be informed, then we have to verify the DL is loaded. Is that what happens (i.e. the whole process of DL loading happens again)?

I wondered whether the flow chart would communicate what I intended. If it's not useful or if you can think of a better way to render the info then I'm happy to remove/change it (I actually went through numerous different tries and this was the best!). The X axis is meant to be interpreted as basically independent from the Y axis, except in specific cases where red lines come off actions in the X axis (revised workflows, in which case the dashed red lines should be followed). 

So re your specific example it's supposed to be read:
- DL is loaded (follow X Axis) - Pub check -> Send to Pre-editing
- Follow dashed red lines, Pub-check -> Pre-editing -> Diamond question etc.
- Normal publishing workflow continues from there (solid red lines) - Required freelance copyedit yes/no -> etc.

**Comment by FAtherden-eLife** [comment]
> For dec-letter-front-test-4

>> Every Decision letter should have at least 1 reviewer, unless the reviewers opted to be anonymous, or if the paper was reviewed via Review commons. If this warning fires, Exeter should inform eLife Production. eLife Production should query the eLife Editorial team, asking whether Reviewers need to be included and if so, what their details are (name and optional affiliation).

> Is it worth clarifying that Exeter don't need to contact us if the text 'the reviewer(s) opted to remain anonymous' or similar is present?

The test will no longer fire if that text is present, so that's why I left it out. Is it still necessary to include that info?

**Comment by FAtherden-eLife** [comment]
> Just a general question but when we format sections of the author response letter as display quotes (e.g. if they're missed), are they automatically captured as @ content-type='editor-comment'?

Yup, every display quote in the AR will have that attribute.

**Comment by FAtherden-eLife** [comment]
> For the video loading flow chart, the PAV action - should it say 'Exeter processes the video (s)' since this is an Exeter stage?

I think we'll still need to inform them that it has videos, since I don't think that they will be notified of that in any way and they have to manually do something.

**Comment by Melissa37** [comment]
>All Figures, Tables, and Videos display as expected.
There are no unaddressed Schematron messages which require action.

Suggest changing to:

>All Figures, Tables, and Videos display expected to display in the same way as in main article.

**Comment by Melissa37** [comment]
>The word document containing both the Decision letter and Author response, and any accompanying assets are zipped up, and placed in the elife/decision-letter-input AWS bucket by the eLife Editorial team.

Suggested changes:

>The Word document, which contains both the Decision letter and Author response, along with any accompanying assets, are zipped up and placed in the elife/decision-letter-input AWS bucket by the eLife Editorial team.

**Comment by Melissa37** [comment]
>In the event that a Decision letter/Author response contains videos, Editorial will inform Production prior to uploading, see below on what to do when this occurs workflow. 

Suggest adding  "in the" before workflow at the end.

**Comment by Melissa37** [comment]
>See below for the workflow
https://docs.google.com/drawings/d/1mN7lHDMwa2CWaMSoR8q1xHiuvDzY3y3iOGdG9UKUVTc/edit

Wow, this looks really complicated!!

**Comment by Melissa37** [comment]
>Action: This will fire is a paragraph in a Decision letter or Author response contains the text </author response or similar. This type of pseudo-code is included in the original Word document by the eLife editorial team as flags for the decision-letter-parser to correctly recognise what a certain object in the document should be captured as. If this text is in the JATS, however, that means that the content has not been correctly recognised by the parser. Exeter should flag this error with the eLife production team.

Should the pseudo code have a close bracket on it?

**Comment by Melissa37** [comment]
> If this warning fires, Exeter should inform eLife Production. eLife Production should query the eLife Editorial team, asking whether Reviewers need to be included and if so, what their details are (name and optional affiliation). 

Needs comma before "if so" as well as after it

**Comment by Melissa37** [comment]
>The eLife production team should check the article in eJP (it might be that the editor details were added subsequent to the article being exported to Kriya). If the information is not available in eJP, then this should be queried with the eLife Editorial team in order to get the details for the the Reviewing Editor (name and affiliation - both are mandatory).

double "the" - remove one

**Comment by FAtherden-eLife** [comment]
> The Word document, which contains both the Decision letter and Author response, along with any accompanying assets, are zipped up and placed in the elife/decision-letter-input AWS bucket by the eLife Editorial team.

I think this wording implies that the assets are included in the word document, which is not the case and is the reason for the original clunky wording.

**Comment by FAtherden-eLife** [comment]
>> Action: This will fire is a paragraph in a Decision letter or Author response contains the text </author response or similar. This type of pseudo-code is included in the original Word document by the eLife editorial team as flags for the decision-letter-parser to correctly recognise what a certain object in the document should be captured as. If this text is in the JATS, however, that means that the content has not been correctly recognised by the parser. Exeter should flag this error with the eLife production team.

> Should the pseudo code have a close bracket on it?

It will fire even if there isn't a closed bracket (which might the cause of the issue in the first place). I have also included an example with a closed bracket in the action.

**Comment by Melissa37** [comment]
Unicode tests

I wonder whether we should say something along the lines of "if there are lots of these schematron warnings production can send the article back to Exeter to fix them all?

**Comment by Melissa37** [comment]
>Error: sub-article id must be in the format 'sa0', where '0' is it's position (1 or 2).


it's should be its
?

**Comment by Melissa37** [comment]
>Error: sub-article contain one and only one front-stub.
>Error: sub-article contain one and only one body.


Should be "sub article contains" in both places

**Comment by bcollins14** [comment]
Would author response images mislabelling be counted on this page? Typically when they forget the . at the end.

**Comment by bcollins14** [comment]
Other than that, everyone has covered everything. I loved the diagrams and the information boxes.

**Comment by FAtherden-eLife** [comment]
> Would author response images mislabelling be counted on this page? Typically when they forget the . at the end.

I think that would be covered [here](https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/allowed-assets/figures#reply-fig-test-2)
