### ISSUE TITLE
Create Versioning/corrections page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#108]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Need to clarify that correction/retraction notice PDFs don't need to be generated in Kriya
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?

**Comment by FAtherden-eLife** [comment]
Making a note for whoever picks this up, to please detail that V2/SC XML should still be validated against the Schematron (despite the fact that there may be errors which one cannot/should not fix) and/or special attention paid to MSAs (which may require updating), so that we can avoid cases like these - https://github.com/elifesciences/issues/issues/6834.

**Comment by naushinthomson** [comment]
[This page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/versioning) is now ready to review, however I want to polish the 'Issuing a correction or retraction notice in eJP' section when the next one comes along so that section can be somewhat ignored for now!

**Comment by Melissa37** [comment]
New versions (also known as V2)

I'd change to 

New versions (also known as V2s)

So the plural matches

**Comment by Melissa37** [comment]
I'd change 

>Issued if the error is visible, but does not affect the scientific content of the research, for example, typos in names, incorrect funding or affiliation information, minor figure edits (without changing the data itself) etc. 

To:
>Issued if the error is in the content (not XML formatting), but does not affect the scientific content of the research, for example, typos in names, incorrect funding or affiliation information, minor figure edits (without changing the data itself) etc. Exception: Feature content (see here for Feature content)

**Comment by Melissa37** [comment]
Can you add a section about Feature content - that the features team makes the decision which type of correction it is?

Also, that although Digests are produced by the feature team, changes to content after publication are within research articles so follow the standard production rules.

**Comment by Melissa37** [comment]
>If there are errors in PoAs, new versions of these can also be issued before the VoR if appropriate (see more here). 

See more here does not link to anything.

Could we phrase it to make it clear we prefer to wait for the VoR publication to make changes rather than version PoAs

**Comment by Melissa37** [comment]
>Silent corrections
Issued if the correction does not affect scientific content or result in a visible change in the article, for example, if the error is in the XML. No annotations are added on the website - the article is silently updated. 

I'd change to:

>Silent corrections
Issued for formatting errors is in the XML. No annotations are added on the website - the new version replaces the version present on the site and no change history is available to the viewer. Feature content can also be silently corrected for content changes

**Comment by Melissa37** [comment]
>Official corrections
Issued if an error affects or impacts upon the scientific content of the article, for example, major corrections to figures (e.g. incorrect/duplicated western blot panels, changes to p values or any other data changes) or text edits affecting some scientific conclusions. The corrected article has a red banner heading on the eLife website to link readers to the correction notice. 

Could you add something about these going through the editorial team and editors and create a Correction article that accompanies the updated version...ie it's 2 part - a correction article is published along with a V2 of the research article itself?

**Comment by Melissa37** [comment]
>It can be tricky to figure out whether an error affects the scientific meaning/conclusions of the article. If there is any doubt, this should be discussed with the Production team in the first instance, and the Editorial team as well if required. 

I am not sure this is the process? I thought these generally come from the editorial team and we don't decide whether a correction notice is needed, they do?

**Comment by Melissa37** [comment]
How are V2s cleared off the Kriya 2 dashboard? Do they need to be?

**Comment by Melissa37** [comment]
>Silent corrections can be issued if a change does not affect the scientific content.

Change to

>Silent corrections can be issued if a change does not change the content

**Comment by Melissa37** [comment]
> Silent corrections can be issued if a change does not affect the scientific content. These are processed in a similar manner to new versions - except there is no Continuum check step. Instead, after checking the relevant changes have been made, the article is sent straight to the website and published automatically via the silent-corrections AWS bucket. 


Change to:

> Silent corrections can be issued if a change does not affect the scientific content. These are processed in a similar manner to new versions - except there is no Continuum check step. Instead, after checking the relevant changes have been made, the article is sent straight to the website and published automatically via the silent-corrections AWS bucket. Silent corrections replace the current version on the website by over writing it.

**Comment by Melissa37** [comment]
>No annotations should be left to indicate the change as this is a silent correction. Because of this, silent corrections should only be used when absolutely necessary. 

Change to

>No annotations should be left to indicate the change because the reader cannot see an old version to verify against. Silent corrections should only be used for XML issues and not content changes (with the exception fo Features content)

**Comment by Melissa37** [comment]
>An official correction is required when an author wishes to make changes to the scientific content of their work after publication. This is the chief difference between this kind of correction and a new version: the changes affect the scientific content and potentially the conclusions presented in the article, therefore readers must be informed that the article has changed.

Change to?
>An official correction is required when an author wishes to make changes to the scientific content of their work after publication and this needs to be clear to all readers wherever they may access the content. Official correction notices are published and linked to the research content on other sites such as PMC, Scopus and Web of Science, as well as the eLife website and this is a historic scholarly publication process that all publishers adhere to (publishing correction notices).

**Comment by Melissa37** [comment]
>When an author requests a change to their article that constitutes an edit to the scientific content, Editorial will need to be informed. It will usually be clear from the author’s message to what extent the changes affect the content of the article but if there is any uncertainty, correspond with Editorial to make the decision. The editors who handled the article will need to be informed of the required correction. Editorial will then work with the authors and editors to draft and approve the text for the correction notice. This will then be emailed to the Production team for processing. 

Add:

>When an author requests a change to their article that constitutes an edit to the scientific content, Editorial will need to be informed. It will usually be clear from the author’s message to what extent the changes affect the content of the article but if there is any uncertainty, correspond with Editorial to make the decision. The editors who handled the article will need to be informed of the required correction. Editorial will then work with the authors and editors to draft and approve the text for the correction notice. This will then be emailed to the Production team for processing. Note, this is a subjective decision sometimes.

**Comment by Melissa37** [comment]
EJP process

Can we look for efficiencies here? If there is an article with multiple authors, could we just add the corresponding author to EJP and ask Exeter to ignore the EJP XML and use the Word file?
This seems like a waste of time and effort all thisEJP filling in...the data will be in the eLife system later, so it's not 100% necessary to have it at this point?

**Comment by Melissa37** [comment]
>Once the required changes have been made to the article, check everything over again, and then update the pub-date of the correction notice to today's date. 

I think I'd add clarification to NOT update the pub date of the research article itself. It's just the correction you are adding the pub date for?

**Comment by Melissa37** [comment]
For retractions

I think it could be clearer that we don't change the original article AT ALL except to add the correction banner to the PDF. All the info about the issues is in the retraction notice

**Comment by Melissa37** [comment]
>To prevent retracted articles being redelivered to PMC, the retraction notice and corresponding article must be published on the same day.

Why don't we want PMC to have the new PDFs with the retraction notice on them?

**Comment by Melissa37** [comment]
>Once this is back from Exeter, check it looks ok, then update the pub-date of the retraction notice and send it to Continuum

I think elsewhere in the GitBook we use upper case of OK

**Comment by Melissa37** [comment]
Thanks @naushinthomson this is really informative and helpful!! I learnt a lot form reading it :-)

**Comment by JGilbert-eLife** [comment]
> Could we phrase it to make it clear we prefer to wait for the VoR publication to make changes rather than version PoAs

Sorry, just jumping on this - we do need to cover that there are some things that NEED to be fixed for PoAs if they're particularly egregious errors (affiliations being flat out wrong, for example), or if they affect the readability of the article (rendering issues with the PDF).

**Comment by JGilbert-eLife** [comment]
"Issued if an error affects or impacts upon the scientific . . ." 

I think this can just be "Issued if an error impacts the scientific . . ." to avoid tautology.

**Comment by JGilbert-eLife** [comment]
"Except for new versions, post-publication changes are only applied for VoRs."

I'm not sure what this means, since it's not strictly true. We've silently corrected PoAs before now (pub date issues) and we would in theory need to retract a PoA if that was necessary, since PoA counts as publishing an article and entering it into the scientific corpus (PubMed etc).

**Comment by JGilbert-eLife** [comment]
"For example, the old MSA, 'Human Biology and Medicine' was updated to 'Medicine' in 2020. Any updates to articles with the MSA 'Human Biology and Medicine' would therefore need to include a change to the MSA as well. "

I would make clear that a lot of these changes involved adding additional subject areas, so you need to check the MSAs on the published article to ensure they match.

**Comment by JGilbert-eLife** [comment]
"If there are no Schematron errors, send the article to Continuum and check and publish as usual. However if there are Schematron error messages that can't or don't need to be resolved, Exeter will need to turn off the validator so the article can be sent to Continuum - ask them to do this in Slack, noting in the Production channel that this has been done. Once the article is on Continuum, ask Exeter to turn the validator back on (and let the Production channel know when this has been done)."

Is this true for Kriya 2? I mean, it's not true for Kriya 1 any more, but is the validator any barrier to proceeding on 2?

**Comment by JGilbert-eLife** [comment]
"The first time you do this, you will need to sign in to ORCID."

I think it would be more accurate to say that you need to be logged into ORCID to annotate articles - I get logged out over time, so it's not a one-time thing!

**Comment by JGilbert-eLife** [comment]
I think it would be worth covering manual silent corrections for really old content that cannot be carried out via Kriya.

**Comment by JGilbert-eLife** [comment]
The correction notice and the corrected article should be batch-published so they go out at the same time. The text here suggests that we publish the article first and then load the notice. That's really not what we should be doing, because we don't want to be in a situation where the article's updated but the notice isn't yet live.

**Comment by JGilbert-eLife** [comment]
Retractions are obviously a little different because the article is being silently corrected, but you haven't actually said the retraction notice should be published! Again, the SC and publication of the notice should be done as simultaneously as possible.

**Comment by JGilbert-eLife** [comment]
Thanks @naushinthomson :)

**Comment by griffithsc** [comment]
Once the updated article is live, add an annotation using hypothesis:

Could you add in brackets what Hypothesis is?

**Comment by griffithsc** [comment]
Instead, after checking the relevant changes have been made, the article is sent straight to the website and published automatically via the silent-corrections AWS bucket. 

- Will we need to update this in light of what you mentioned in the meeting this morning, i.e., clicking 'send to Continuum' and adding a note to Exeter to say that this should be uploaded to the silent corrections bucket? (apologies if I misunderstood here!)

**Comment by griffithsc** [comment]
It can be tricky to figure out whether an error affects the scientific meaning/conclusions of the article. If there is any doubt, this should be discussed with the Production team in the first instance, and the Editorial team as well if required. 

Is it worth mentioning here that Editorial will sometimes ask our advice as to whether a particular case is best captured as a new version or a correction?

**Comment by griffithsc** [comment]
Thanks so much Naushin - really helpful to have this all in one place! :-)

**Comment by naushinthomson** [comment]
> I think it would be worth covering manual silent corrections for really old content that cannot be carried out via Kriya.

@JGilbert-eLife I've added this info from previous documentation to the section 'Correcting older articles' (let me know if you can think of a better title!). I wasn't sure what the 'OS ticket thread' is though, any idea? Let me know if more info needs to be added as well!

**Comment by JGilbert-eLife** [comment]
@naushinthomson I think these instructions are way out of date by this point. OS ticketing was a management system Exeter used to track their emails previously; not sure if they're still using it. I think you can just read that as 'email thread'?

We don't have access to that FTP 'input' folder any more either - we'd need to handle the communication for this process via email or Slack now.

Important to note that for silent corrections, we might not even need to involve Exeter as we'd just update the XML ourselves; we only need Exeter if it's going to affect the PDF.

**Comment by naushinthomson** [comment]
> "For example, the old MSA, 'Human Biology and Medicine' was updated to 'Medicine' in 2020. Any updates to articles with the MSA 'Human Biology and Medicine' would therefore need to include a change to the MSA as well. "
> 
> I would make clear that a lot of these changes involved adding additional subject areas, so you need to check the MSAs on the published article to ensure they match.

I've added this in [this section](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/versioning#vor) now, let me know if anything is unclear! :)

**Comment by naushinthomson** [comment]
> * that

@griffithsc No I think I was just getting myself mixed up! In Kriya 2, when we resupply and click on send for silent correction, it should then go into the silent correction bucket when we 'send to continuum'. Does that make sense/should I clarify that on the page?

**Comment by naushinthomson** [comment]
> hese going through the editorial team and editors and create a Correction article that accompanies the updated vers

@Melissa37 This is covered in the [later section](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/versioning#processing-official-corrections-and-retractions) - is that enough or do I need more detail?

**Comment by naushinthomson** [comment]
> > It can be tricky to figure out whether an error affects the scientific meaning/conclusions of the article. If there is any doubt, this should be discussed with the Production team in the first instance, and the Editorial team as well if required.
> 
> I am not sure this is the process? I thought these generally come from the editorial team and we don't decide whether a correction notice is needed, they do?

That part is more about generally deciding if something should be a V2, SC or OC and I was more thinking of when an author gets in touch with us directly but I'll clarify!

**Comment by FAtherden-eLife** [comment]
> Why don't we want PMC to have the new PDFs with the retraction notice on them?

I agree it would be good to add this detail. It's because PMC don't do anything with the PDFs, so if adding the "This article has been retracted" banner to the PDF is the only change (as is the case for a retracted article), then they don't want the update.

@naushinthomson, are you happy to detail this info in the page somewhere appropriate?

**Comment by FAtherden-eLife** [comment]
> The Editorial team will usually decide if an article requires a correction/retraction. See more here. 

Perhaps we could change this to something like:
> The Editorial team may need to be consulted to determine whether correcting an article requires a correction or new version. 

I'm thinking of cases when the authors contact us and it's obvious a V2 will be fine, or that it's obvious a correction is appropriate (esp. if the authors request a correction notice), and in the latter case it would be basically just confirmation with Editorial.

**Comment by FAtherden-eLife** [comment]
> Only VoRs tend to have official corrections. 

I don't recall a POA that we've ever had to officially correct. Any objections to simply changing this to "Only VORs will have official corrections."?

**Comment by FAtherden-eLife** [comment]
> Make sure to validate the XML against the Schematron as usual. If the article is older, there may be some error messages, as the Schematron may have been updated since the article was published.

Should we specify to use [the validator](https://basex-validator.elifesciences.org/) rather than the Schematron, since that needs to be used to compare the MSAs in the published article and those in the XML? Or is this clear/obvious enough as is?

**Comment by FAtherden-eLife** [comment]
Is it worth just briefly mentioning name change requests somewhere and linking to [the page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/toolkit/name-change-requests)?

**Comment by FAtherden-eLife** [comment]
> Subject line: TNQ correction: Article number - silent correction/new version/official correction

Can we add delete as appropriate here?

**Comment by FAtherden-eLife** [comment]
> For V2s - Exeter will deliver the article to Continuum via the elife-production-final bucket. 
> For Silent Corrections -  upload the corrected article to the prod-elife-silent-corrections bucket.

So for V2s Exeter deliver it, but for SCs we do it? I think we could rephrase to detail which bucket to upload the package in if we're able to make the edits ourselves, otherwise we can simply let Exeter know what kind of correction it is, and they will upload to the appropriate bucket.

**Comment by FAtherden-eLife** [comment]
Would it be worth having a section about determining whether an update is a V2 or correction, just so that it's pulled out from the text a bit more and easier to find? It doesn't have to be extensive. 

We could also add in there that if the authors have specifically requested a correction notice (which they may wish to do for reasons other than our criteria), then that should likely be the course of action after confirmation with the authors (after detailing our usual criteria to them) and Editorial.

**Comment by FAtherden-eLife** [comment]
Nice work, thanks @naushinthomson
