### ISSUE TITLE
Create Striking images page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#112]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?

**Comment by bcollins14** [comment]
I believe this is now ready for Production to review (eekk!) @naushinthomson @JGilbert-eLife @FAtherden-eLife @Melissa37 

[https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/striking-images-1](url)

**Comment by FAtherden-eLife** [comment]
Is it worth providing the screenshot without the browser highlighting over 'striking image'?
![Screenshot 2020-07-09 at 14 36 09](https://user-images.githubusercontent.com/43879983/87046897-abb0ef00-c1f1-11ea-82fb-61024b9f7286.png)

**Comment by FAtherden-eLife** [comment]
> They may only include the title of the article without the article number but you can often find this by searching in eJP using the article title or email address of the author.

Is this referring to the email subject? If so, I think this should be made clearer.

**Comment by FAtherden-eLife** [comment]
> If you are unable to do so, the author will need to be asked for this so that we can ensure the striking image is uploaded correctly. 

Suggest changing to:
If you are unable to determine which article the striking image relates to, the author will need to be asked what their manuscript tracking number is, so that the striking image can be uploaded correctly.

**Comment by FAtherden-eLife** [comment]
> Depending on the status of the article, you can upload this striking image through eJP or the Kriya dashboard. 

Please clarify what status determines this.

**Comment by FAtherden-eLife** [comment]
> Alternatively, you can look in the Production inbox for the XML notification.  

Suggest changing to:
Alternatively, search the manuscript number in the Production Inbox, and check if there's an XML notification email which indicates that the article has been sent to Kriya (see **[here](https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/managing-the-production-inbox#xml-notification-emails)**).

**Comment by FAtherden-eLife** [comment]
> It is worth noting that you are unable to select multiple images to upload through the 'Select file' icon and each image will need to be selected separately (but within the same uploading session).

Would it be worth including a screenshot or two of this process to make absolutely clear?

**Comment by FAtherden-eLife** [comment]
> After clicking on 'Update' the uploader will not automatically close.

Huh, I didn't know that! I've always just waited (in some cases for a long time), for the pop-up to close.

**Comment by FAtherden-eLife** [comment]
You allude to the fact that other journals might include these as covers, and sometimes eLife authors contact us expecting the same - i.e. "I provided a striking image but the poster for my article doesn't contain it - why is that?"

Does this need to be covered in this page, or the production inbox page? I see there are email templates relating to Striking images as well. Should these be covered in this page or the production inbox page? If the latter, then I think we should mention these in this page referring the user to the appropriate section in that page.

**Comment by FAtherden-eLife** [comment]
Out of scope for this ticket but, looking at the email template for responding to a striking image email:
> Dear 
> Thank you very much for sending over your striking image. I have uploaded it to our system for you now. 
> Best wishes,

Is it worth clarifying what it will be used for in the template?

I used to say something like, "I have uploaded it to our system for possible selection by our social media team".

The attempt here is to mitigate against the "I provided a striking image but the poster for my article doesn't contain it - why is that?" type emails.

**Comment by Melissa37** [comment]
>Uses for striking images
Striking images can be used in the following ways 
...
within the eLife digest [see here for the digest channel] 

Suggest change to:
to accompany the Digest in the eLife digest channel (note: this cannot accompany the Digest on the journal article HTML view or in the PDF)


>The authors are also free to use these images for their own social media and press releases and do not need to ask permission for this. 

...because they fall under the CCBY license along with the rest of the content.

**Comment by FAtherden-eLife** [comment]
Would it be worth putting uploading to Kriya and AWS above uploading to eJP?

Is the thought process?
*  Is it in Kriya? 
    * yes:
        * Does it already have a striking image?
                * yes -> upload to AWS
                * no -> upload via Kriya
    * no:
        * upload to eJP


If so, then I think it should be ordered based on that.

**Comment by FAtherden-eLife** [comment]
That's it from me - thanks Becky, nice job.

**Comment by Melissa37** [comment]
@bcollins14 can you add the url link to where this page is again? I cannot get the link to work from the top of this ticket.

Thanks!
M

**Comment by Melissa37** [comment]
>To maximise the impact of an article upon its release, it is beneficial to accompany an article with an eye catching image that highlights the research article. 

Suggest adding hyphen between eye and catching:

>To maximise the impact of an article upon its release, it is beneficial to accompany an article with an eye-catching image that highlights the research article.

**Comment by Melissa37** [comment]
>At eLife, when an acceptance letter is sent out, we encourage authors to submit a promotional image which we call a 'striking image', which can be emailed to the Production team and/or uploaded during their submission to eJP.

Suggest changing to following:

>At eLife, when an acceptance letter is sent out, we encourage authors to submit a promotional image that we call a 'striking image'. This can be emailed to the Production team directly and/or uploaded during their submission to eJP.

**Comment by Melissa37** [comment]
>These images should preferably be in colour, in a landscape format and be at least 1800 x 900 pixels. 

I believe we use the Oxford comma:

>These images should preferably be in colour, in a landscape format, and be at least 1800 x 900 pixels.

**Comment by Melissa37** [comment]
>Photographs, microscopy images and illustrations work best

Suggest Oxford comma usage:

>Photographs, microscopy images, and illustrations work best

**Comment by bcollins14** [comment]
**To add:** If an author had uploaded the image via eJP (or emailed Production) and Features also send us the image. Need to check what has been uploaded already to the AWS bucket and ensure correct caption is included.

**Comment by Melissa37** [comment]
>This information is provided to authors, and it is up to them to ensure the images they provide adhere to these guidelines. We do not check them and we upload whatever is provided to Kriya. 

I don't think this is very clear - what info? 

Should it be?
>We assume the images provided are licensed under CC-BY and do not check this information. If there is a caption or attribution information provided with the image this should be added to the 'metacontent' when uploading to Kriya (see below).

How is this info provided if in EJP?

**Comment by Melissa37** [comment]
Tautology (remove "via email"):

>Authors can email Production with a striking image via email as indicated in the acceptance email from Editorial and will have been provided with the guidance shown below.

**Comment by Melissa37** [comment]
>They may only include the title of the article without the article number but you can often find this by searching in eJP using the article title or email address of the author. If you are unable to do so, the author will need to be asked for this so that we can ensure the striking image is uploaded correctly. 


Suggest changing to:
>They may only include the title of the article without the article number but you can often find this by searching in eJP using the article title or email address of the author. If you are unable to do so, the author will need to be asked for this so that we can ensure the striking image is associated with the correct article.

**Comment by Melissa37** [comment]
>Depending on the status of the article, you can upload this striking image through eJP or the Kriya dashboard. 

Suggest changing to:

>If the article has been exported from eJP and is in Kriya, upload the image via the Kriya dashboard. If the article is still within eJP and not yet exported, upload it to eJP. It is important **not** to load it to eJP if the article is already in the production system because the systems do not transfer further information with each other after export has occured.

**Comment by Melissa37** [comment]
>To upload this via eJP, you should bring up the accepted version of the article. 


Suggest changing to:
>To upload the image to eJP, search eJP using the MS number.

**Comment by Melissa37** [comment]
>Ensure this article has not already been exported from eJP to Kriya. To check, you can look to see if under  'More Manuscript Info and Tools' on the right hand side of the page, and see if the 'Export to Exeter' option is not displaying but instead says 'Resend/Export to Exeter Premedia'. Alternatively, you can look in the Production inbox for the XML notification.

Suggest changing to:
>Ensure this article has not already been exported from eJP to Kriya. The most efficient way to do this is to search the Production inbox for the XML notification, which informs production an article has been exported from eJP.
However, if you are in eJP look at 'More Manuscript Info and Tools' on the right-hand side of the page. If the 'Export to Exeter' option is not displaying but instead says 'Resend/Export to Exeter Premedia' this means the article has already been exported. 

Might be worth rejigging with the part above too. Perhaps move "Ensure this article has not already been exported from eJP to Kriya. The most efficient way to do this is to search the Production inbox for the XML notification, which informs production an article has been exported from eJP." to above the section about loading to eJP?

**Comment by Melissa37** [comment]
>When the uploader appears, select the file and then click on 'Update'. Leave the 'metacontent' as is, unless the authors have provided a caption or attribution information in which case these should be entered instead. 

Suggest changing to:
>When the uploader appears, select the file and then click on 'Update'. Do not add text to the 'metacontent' field unless the authors have provided a caption or attribution information, in which case enter the provided text here.

**Comment by Melissa37** [comment]
>It is worth noting that you are unable to select multiple images to upload through the 'Select file' icon and each image will need to be selected separately (but within the same uploading session). This is because with each image upload, it will overwrite what is previously in the striking images AWS bucket. To add additional images to an article has already has an image, please see below.


Suggest changing to
>It is worth noting that you are unable to select multiple images to upload through the 'Select file' icon. If an author has provided more than one image uploaded them successively within the **same** session. 
Successive upload sessions overwrite what was previously uploaded.
Authors who provide more than one image are giving us more choice of images to use.

**Comment by Melissa37** [comment]
>Uploading via the striking images AWS bucket 

Need to explain what the AWS bucket is, how to get there and what it's purpose is

**Comment by Melissa37** [comment]
>Open this folder and drag and drop the new striking image in to upload it. Make sure the striking image is titled appropriately - e.g. '56754-b_striking_image' if there is already a '56754-a_striking_image'. If the authors have provided a title, caption, or attribution information, enter this into a .txt file and save with the same title (i.e. '56754-b_striking_image'). If they have not provided this information, you do not need to include a .txt file. 

Are the file names created with the -a  suffix even if there is only 1?

**Comment by Melissa37** [comment]
This ticket is called Create Striking/homepage images page but it does not include info about the homepage. Is that going to be in another page/ticket?

Thanks! I'm all done @bcollins14

**Comment by JGilbert-eLife** [comment]
Thanks for this @bcollins14!

"To maximise the impact of an article upon its release, it is beneficial to accompany an article with an eye catching image that highlights the research article. "

I think this phrasing might be a little bit misleading - articles are not accompanied by the images in the way that authors tend to assume they will be - the images are used to promote their articles, but don't appear on the website etc etc. Maybe:

"To maximise the impact upon publication, it is beneficial if an eye-catching image highlighting the research is available to promote the article."

**Comment by JGilbert-eLife** [comment]
Maybe say in the legend for the image that it's an example of a graphical abstract? Just to be 100% clear

**Comment by JGilbert-eLife** [comment]
> Are the file names created with the -a suffix even if there is only 1?

They are, yes.

**Comment by JGilbert-eLife** [comment]
". . . we upload whatever is provided to Kriya."

To be really picky, we don't upload them to Kriya. We upload them *via* Kriya but the end-point is the striking image bucket. I think this is a distinction worth drawing because we sometimes have to do this manually for really large images, or if Kriya is borked.

**Comment by JGilbert-eLife** [comment]
Hmm - I wonder if it's less hassle to simply take an existing image and reupload it if you need to add an extra one through Kriya. It's a faff either way, but that might be the easier route?

**Comment by naushinthomson** [comment]
I think everyone has already covered anything I would have noted. Thanks for working on this Becky!

**Comment by eLifeProduction** [comment]
> After clicking on 'Update' the uploader will not automatically close.
> 
> Huh, I didn't know that! I've always just waited (in some cases for a long time), for the pop-up to close.

It hasn't always been this way, it used to close automatically but this has been a work around for a while now. It took me a while to realise it had indeed broke >_<

**Comment by bcollins14** [comment]
Opps would help if I was signed in as myself!

**Comment by bcollins14** [comment]
> This ticket is called Create Striking/homepage images page but it does not include info about the homepage. Is that going to be in another page/ticket?

I felt having a separate page for the homepage would be better as it can go into how the process works too. I need to make another ticket for this.

**Comment by bcollins14** [comment]
@JGilbert-eLife @Melissa37 @FAtherden-eLife @naushinthomson I believe this is now ready for review again [https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/striking-images-1](url)

**Comment by FAtherden-eLife** [comment]
Thanks Becky, do we need something in the [Uploading a striking image](https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/striking-images-1#uploading-a-striking-image) section about whether the article already has a striking image, and what to do in that case? I.e. don't upload via Kriya if there already is a striking image (or images) since it will be overwritten?

**Comment by Melissa37** [comment]
>Cover images - These are used as front cover images on the article's journal issue. 

Should we add something like "eLife produces 'vanity covers' for authors, but the image used is a stock image and not what the author provides as a striking image)?

**Comment by Melissa37** [comment]
>It is important not to load it to eJP if the article is already in the production system because the systems do not transfer further information with each other after export has occurred.The most efficient way to do this is to search the Production inbox for the XML notification, which informs production an article has been exported from eJP.

Suggest changing to (note also the missing space after the full stop):

>It is important not to load it to eJP if the article is already in the production system because after export has occurred there is no further push of information from eJP to Kriya. The most efficient way to do this is to search the Production inbox for the XML notification, which informs production an article has been exported from eJP.

But suggestions welcome, don't think that's quite right yet!

Sorry, know it was my suggested wording originally!

**Comment by Melissa37** [comment]
>To upload a striking image to an article, download the image provided by the author, go to the article in the Kriya dashboard and click on 'Striking image'. 

Needs full stop in front of and

**Comment by Melissa37** [comment]
>The AWS (Amazon Web Services) bucket is a remote file storage system. If you require access to this, please speak to a member of Production. You can use cloud storage browsers such as Cyberduck or Transit to view the bucket. 

It's Transmit, not Transit :-)

**Comment by Melissa37** [comment]
>For ease, you can search if an article has a striking image using the 'Search' bar and typing in the MS number. 

Suggest changing to:

>To find whether an article has a striking image using the 'Search' bar and typing in the MS number.

**Comment by Melissa37** [comment]
>There are times when you may need to access the striking images bucket directly, for example, if an image is too large to upload via Kriya, Kriya is down, or a striking image has already been uploaded. 


I know we discussed this, but it seems really inefficient loading it to Kriya. What are the benefits of loading it via Kriya? Could they be added?

**Comment by Melissa37** [comment]
>It is typically easier, if you can, to use the Kriya dashboard as it sets up the initial folder and creates the .txt files automatically. In certain situations, mentioned above, you may need to manually create a folder for an article's striking image. 


Suggest moving this to the start of the section about uploading via Kriya and reword it appropriately

**Comment by Melissa37** [comment]
>To do this, you need to go to the 'elife-striking-images' bucket and create a new folder. You can either do this through the 'File' menu at the top left hand corner of your screen or right click to bring up this option on the 'elife-striking-images' bucket overview. Click 'New Folder...'.
. 


Suggest adding hyphens between left and hand and also right and click

**Comment by Melissa37** [comment]
right-click - a late instance where this hyphen could be added:

>Once it has finished uploading, you will need to right click on the file to rename it.

**Comment by Melissa37** [comment]
>Open this folder and drag and drop the new striking image in to upload it. Make sure the striking image is titled appropriately - e.g. '56754-b_striking_image' if there is already a '56754-a_striking_image'.

Suggest changing to:

>Open this folder and drag and drop the new striking image in to upload it. Make sure the striking image is titled appropriately - e.g. '56754-b_striking_image' because there is already a '56754-a_striking_image'.

In this scenario it's a given there is an "a" file in place already

**Comment by Melissa37** [comment]
>Existing striking images


Please explain that Kriya will overwrite what's in the bucket already and that's why you need to do this process :-)

**Comment by Melissa37** [comment]
>If you have multiple images to upload with captions, you may prefer to upload these all together through the Kriya dashboard. To do this, you should download any existing images and .txt files (if these contain any captions) from the bucket and upload these along with the new images as shown in the previous section.  

suggest changing to:

>If you have multiple images with captions to add to existing images provided by the author, you may prefer to use the Kriya dashboard. You will need to re-upload the old images at the same time as the new images to prevent overwriting. To do this, you should download any existing images and .txt files (if these contain any captions) from the bucket and upload these along with the new images as shown in the previous section.

**Comment by Melissa37** [comment]
>However, if you are in eJP look at 'More Manuscript Info and Tools' on the right-hand side of the page

Suggest changing to:

>However, if you are already in eJP look at 'More Manuscript Info and Tools' on the right-hand side of the page

**Comment by Melissa37** [comment]
>The Features team work...

Change to

>The Features team works...

**Comment by Melissa37** [comment]
>The Features team work with authors to write Digests and often, during this correspondence the authors will send them striking images. Features will then forward on these emails to us. 


There is a comma missing:
>The Features team works with authors to write Digests and often, during this correspondence, the authors will send them striking images. Features will then forward on these emails to us.

**Comment by JGilbert-eLife** [comment]
Suggest changing

"Occasionally, eLife authors contact us expecting to see their striking image on the personalised poster which they can download from their 'The full version of your eLife article is now available' email they receive upon publication."

to

"Occasionally, eLife authors contact us expecting to see their striking image on the personalised poster which they can download from the publication notification email ('The full version of your eLife article is now available')."

**Comment by JGilbert-eLife** [comment]
Other than that, seems good to me.

**Comment by naushinthomson** [comment]
'The most efficient way to do this is to search the Production inbox for the XML notification, which informs production an article has been exported from eJP.'

Can you add a screenshot of this email?

**Comment by naushinthomson** [comment]
Just a minor point but you can delete the following text from the changelog:

'After Exeter has fed back on the page and it has been updated, any further changes to the page should be listed in order from oldest to most recent. '

**Comment by naushinthomson** [comment]
That's all from me!

**Comment by naushinthomson** [comment]
Just had a thought - do we need to cover what to do when an article has been PoA'd but not yet loaded in Kriya and the authors send a striking image through? Even if it's just 'leave a note on the email'?
