### ISSUE TITLE
Create Changing homepage image page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#113]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?

**Comment by eLifeProduction** [comment]
Hello @naushinthomson @FAtherden-eLife @JGilbert-eLife @Melissa37 this page is ready for your review https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/

**Comment by bcollins14** [comment]
Sorry added my previous comment using the production github account >_< 

@naushinthomson @FAtherden-eLife @JGilbert-eLife @Melissa37 this page is ready for your review https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/

**Comment by bcollins14** [comment]
This should work.. https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/striking-images-1/homepage-images

**Comment by Melissa37** [comment]
>On eLife's homepage, we feature three striking images on an image carousel. Each image will stay on the carousel for three weeks, which offers the chance of promoting the article during this time. Only VOR articles are selected for the homepage, not PoA articles.

I think we use the term VoR not VOR
PoA (publish on accept)
VoR (version of record)
filler words don't warrant capitalisation - sure filler is not the right term, but you know what mean?!

**Comment by Melissa37** [comment]
>The best choices are colour photographs, microscopy images and illustrations.

Comma missing before "and" in images

**Comment by Melissa37** [comment]
>The requirements for Journal CMS (the website used to change the homepage image) are as follows: 

CMS stands for content management system.

Suggest changing to 
>The requirements for Journal CMS (the content management system used to change the homepage image) are as follows:

**Comment by Melissa37** [comment]
>Maximum of 32MB, 
Image size larger than 1800x900 pixels
 Accepted formats are png, jpg, and jpeg.

Remove comma after 32MB
Remove space in front of Accepted
Remove fullstop after jpeg

**Comment by Melissa37** [comment]
>The new homepage image is selected from the striking images of VOR articles that have been published from Wednesday, of the previous week, to the following Tuesday. The words are requested on the Monday morning so, if you were to pick a VOR article that has not yet been published, it is best to only use press papers that are already scheduled for that Tuesday. 

I don't quite understand this, would it be better as a timeline of actions?
Who requests the words and what's the process there?

**Comment by Melissa37** [comment]
>You can use the Production team action sheet to look for articles that have been scheduled, and/or use the eLife's website to find VOR articles that have been published in the previous week. As you bring up each article, you will need to search the striking image bucket to see if it has a suitable image. Once you have found an image, you will then need to send this to Peter as outlined below. On the rare occasion that you do not find a suitable image, you should email Peter to let him know. Then either send an image later in the day when more articles have been published or at the very latest, Tuesday morning. 

Suggest linking to Production team action sheet 

>As you bring up each article, you will need to search the striking image bucket to see if it has a suitable image.
As you view each article?
Where is the striking image bucket?

**Comment by Melissa37** [comment]
>If you have found an image but it is not quite right, i.e slightly too small, you should able to adjust this in a photo editing programme such as Photoshop. However, you should not make any significant changes to the photo. 

Program not programme - computer programs are commonly referred to without the "me" even if using English English

**Comment by Melissa37** [comment]
>If you have found an image but it is not quite right, i.e slightly too small, you should able to adjust this in a photo editing programme such as Photoshop. However, you should not make any significant changes to the photo. 

Could you clarify what you can and cannot change? It's not very clear

**Comment by Melissa37** [comment]
>emailed to Peter (on the Features team) 

(the features editor)

**Comment by Melissa37** [comment]
>The homepage image is selected by a nominated member of the Production team on a Monday morning and this image will be emailed to Peter (on the Features team) to provide the wording which overlays the image. This text is a short description of the article which you can see on the carousel at the top of this page.

Suggest changing to:
>The homepage image is selected by a nominated member of the Production team on a Monday morning. This image is emailed to Peter (the Features Editor) asking him to provide the wording which overlays the image. This text is a short description of the article, which you can see on the carousel at the top of this page.

**Comment by Melissa37** [comment]
>Now 'Choose file' under the 'Image (banner) field. It may help to already have the chosen image on your desktop.

It may help to already have the chosen image saved to your desktop.

**Comment by Melissa37** [comment]
>After you have selected/opened your image

the image

**Comment by Melissa37** [comment]
>...be a maximum of 32MB, larger than 1800x900 pixels, and in either png jpg jpeg format

,and only in of the three following formats: png, jpg, or jpeg

**Comment by Melissa37** [comment]
Nice, thanks! Now I know what the process is :-) Less scary!

**Comment by FAtherden-eLife** [comment]
Suggest moving this in the TOC (on the left hand side) so that it is under Toolkit, rather than striking images.

**Comment by FAtherden-eLife** [comment]
> On eLife's homepage, we feature three striking images on an image carousel. Each image will stay on the carousel for three weeks, which offers the chance of promoting the article during this time. Only VOR articles are selected for the homepage, not PoA articles.

Is it worth clarifying that it's one per week?

**Comment by FAtherden-eLife** [comment]
> The new homepage image is selected from the striking images of VOR articles that have been published from Wednesday, of the previous week, to the following Tuesday.

This wording is a little unclear for me. It might be worth starting with defining when you start looking for a homepage image, or when it is changed and then going from there to describe which articles to pick.

**Comment by FAtherden-eLife** [comment]
It sounds like we need to find an easier/simpler way of tracking which articles have been published with striking images in a week.

**Comment by FAtherden-eLife** [comment]
> However, you should not make any significant changes to the photo. 

Can you explain why for the reader?

**Comment by FAtherden-eLife** [comment]
Is the Slack reminder useful or should I delete it?

**Comment by FAtherden-eLife** [comment]
If the Slack reminder is useful, and we should keep it, then is it worth referring to it in this page?

**Comment by FAtherden-eLife** [comment]
Do image attributions display over the image? Just curious.

**Comment by FAtherden-eLife** [comment]
> The new homepage image is selected from the striking images of VOR articles that have been published from Wednesday, of the previous week, to the following Tuesday. The words are requested on the Monday morning so, if you were to pick a VOR article that has not yet been published, it is best to only use press papers that are already scheduled for that Tuesday. 

Can you explain what to do in the event that there are no suitable striking images for the homepage that week?

**Comment by FAtherden-eLife** [comment]
Is it worth including the contact person at eLife if something goes wrong with the CMS?

**Comment by JGilbert-eLife** [comment]
> Only VOR articles are selected for the homepage, not PoA articles.

I seem to recall in the past we have resorted to using a PoA article if there's no good VoR to hand . . . but I'm not 100% sure.

**Comment by JGilbert-eLife** [comment]
For the first mention of the striking image bucket, is it worth linking to the appropriate point on the striking image page?

**Comment by JGilbert-eLife** [comment]
> Leave the field 'Alternative text' blank.

*Should* we be doing something with this? This is a wider question, obviously, but is it worth discussion?

**Comment by JGilbert-eLife** [comment]
> If there is an image attribution, this should be entered in the field below. 

Maybe provide an example and/or link to the striking images page?

**Comment by JGilbert-eLife** [comment]
I think most of the issue with editing the images boils down to avoiding a reduction in quality. This is especially important when increasing the image - if you have to increase them too much, the image will go fuzzy.

No more comments I think - thanks for doing this @bcollins14!

**Comment by naushinthomson** [comment]
Suggest changing 

>The requirements for Journal CMS (the website used to change the homepage image) are as follows: 

to

>The **file** requirements for Journal CMS (the website used to change the homepage image) are as follows:

**Comment by naushinthomson** [comment]
Otherwise all good from me!

**Comment by bcollins14** [comment]
> The new homepage image is selected from the striking images of VOR articles that have been published from Wednesday, of the previous week, to the following Tuesday. The words are requested on the Monday morning so, if you were to pick a VOR article that has not yet been published, it is best to only use press papers that are already scheduled for that Tuesday.

I thought this didn't overly make sense after I was finished. Perhaps I need to add a visual image for this process :/

**Comment by bcollins14** [comment]
> Do image attributions display over the image? Just curious.

I do not actually know where they display or are used.. @JGilbert-eLife I don't suppose you know?

**Comment by JGilbert-eLife** [comment]
@bcollins14 I *thought* they did display over the image. Did we add them for the famous jelly fish painting? Can we check that in the archive?
