### ISSUE TITLE
Create Interacting with authors page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#114]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with prepress

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?

**Comment by naushinthomson** [comment]
https://app.gitbook.com/@elifesciences/s/schematron/toolkit/interacting-with-authors 

I've just added some guidance here for prepress in terms of dealing with common author emails. I haven't gone into detail about corrections and new versions because I think that can go in a separate page in the future and we aren't expecting prepress to cover this anyway! Let me know if anything is missing!

**Comment by Melissa37** [comment]
>to in a timely manner

Can we define timely manner:
responded to on the day the email hits the inbox unless after 4pm, in which case needs to be responded to the following morning
emails must be responded to even with a "holding" response if we do not have an answer yet

**Comment by Melissa37** [comment]
>There are many email templates saved in the production collaboration tool (Hiver) which can be used when drafting responses to authors. 

Maybe be explicit that you cannot just add the template text, respond to the complete nuance of the author email as necessary

**Comment by Melissa37** [comment]
Template emails
Can you give an explanation for each one we have?
For instance Blank page does not mean a lot so explanation of what that is would be good!

**Comment by Melissa37** [comment]
>Most of the emails we get from authors fall into the following categories:

Are there common queries that correspond with template emails? If so, might be worth linking them

**Comment by Melissa37** [comment]
>Often authors will send striking images by email instead of including these in the initial submission.

Explain why @JGilbert-eLife can explain which email from editorial they are reminded about this and hence why it might not come via EJP

**Comment by Melissa37** [comment]
Striking images page
>Requirements for striking images:
No images with graphs or text
No cartoons, graphical abstracts or summary figures
Colour photographs, microscopy images and illustrations work best (examples here) 
Images should have strong visual impact and not be composed of more than one or two panels
Images should be landscape and a minimum size of 1800 x 900 pixels

We don't check for this though do we, I thought we just load them and leave that to someone else to deal with if they want to use the striking image?

**Comment by JGilbert-eLife** [comment]
Striking images are requested in the acceptance email, and the article can be exported before they respond.

**Comment by Melissa37** [comment]
>If the proofs are still signed out with them, let them know that they will need to submit the proofs before the files can be replaced (there is a template for this). 

Suggest change wording:
If the author has not _signed off_ the proofs, let them know that they will need to submit the proofs before the files can be replaced (there is a template [add template name] for this). 

Suggest better term/explanation for _signed off_

**Comment by Melissa37** [comment]
>If the changes are extensive, the email should be forwarded on to Exeter with the subject prefix 'Author correspondence: XXXXX' (where XXXXX is the article number) so they can make the changes at the post-author validation stage

Humm, if the changes are extensive and the author cannot do them because of the system you can do this, but if it's not that then either push the author to make the changes OR we have to do them for them

**Comment by Melissa37** [comment]
>If authors email to ask for extra time to proof their article, we need to let them know that they may still receive automatic reminder emails. There is a template email for this. Once you have sent this, make sure to leave a comment in the note for the article in Kriya so staff know that the article will be delayed. 

We allow author extensions. Make it clear that's OK

**Comment by Melissa37** [comment]
>Often authors will ask for ORCIDs to be added to manuscripts on behalf of other authors. Unfortunately, due to ORCIDs stipulations, we cannot do this. The only way for an ORCID to be linked to a manuscript is for the author to access the proofs using the link we send them. There is an email template to let authors know this

Need to be clear that it is the specific author who wants to add their ORCID who needs to sign in to do this, another author cannot do it for them as it requires their own password to access the ORCID system to create the link

**Comment by Melissa37** [comment]
>If an article has recently been added to Kriya and the decision letter has yet to be added, it will usually take up to two weeks before this is ready to go to the authors. 

Really?! We need to sort out the decision letter process!!

**Comment by Melissa37** [comment]
>Some emails will be from authors who have noticed a mistake or problem in their published article. If the error affects the scientific conclusions of the article, a correction will need to be prepared.

This needs to be checked with Wei Mun. He's the one who decides on official corrections

**Comment by FAtherden-eLife** [comment]
> > If an article has recently been added to Kriya and the decision letter has yet to be added, it will usually take up to two weeks before this is ready to go to the authors.

> Really?! We need to sort out the decision letter process!!

Should this be digest instead of decision letter?

**Comment by JGilbert-eLife** [comment]
"Problems accessing proofs"

Ideally, we need to get the operating system name and version, and the version of the browser the authors are using as well to help Exeter troubleshoot.

**Comment by naushinthomson** [comment]
- [ ] How long should a decision letter take to load?
- [ ] Review Problems editing proofs section
- [ ] Do we need the Latex package request template email and Missing copy-edit level template email?

**Comment by naushinthomson** [comment]
@JGilbert-eLife Just assigning you to add the text for the Latex package request email!

**Comment by JGilbert-eLife** [comment]
Done, @naushinthomson !
