### ISSUE TITLE
Update Kriya fields for software refs

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#124]
- [x] Create ticket in GitLab board for Exeter to update Kriya fields for software refs
- [x] Exeter update 'Software name' field to 'Source' and 'Software host' field to 'Publisher'
- [x] Update screenshots in GitBook once Kriya fields are changed

**Comment by Melissa37** [comment]
Added to Gitlab Kriya 2 board: https://gitlab.com/ExeterPremedia/reqs/cust/elife-kriyadocs/-/issues/18

**Comment by FAtherden-eLife** [comment]
Fields are different now. Need to confirm how this gets parsed into the XML.

**Comment by FAtherden-eLife** [comment]
https://gitlab.com/ExeterPremedia/reqs/cust/elife-kriyadocs/-/issues/34
