### ISSUE TITLE
Make sure schematron messages include error ids

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/schematron-gitbook#125]
Message to Exeter: I appreciate this is slightly difficult because you need to get used to changing, for instance, in this example, 1 to XX: "The reference in position 1 of the data availability section does not have an id (pub-id is empty)"

The direct message will not provide a result because the generic XX are added to the GitBook: "The reference in position XX of the data availability section does not have an id (pub-id is empty)"

Would it help if we standardised across all the pages to one X? I see there is a mixture of XX and XXXXX.

Response from Bala:
Yes, it would be helpful if we standardised across all the pages to one X.

**Comment by JGilbert-eLife** [comment]
I tried to use XX for number values and XXXXXX for strings. I thought that might make it clearer what kind of information was going to replace them in the messages?

But anyway - I'm not sure I understand. Exeter won't be manually changing anything in these messages; the schematron will populate them with the information?

**Comment by Melissa37** [comment]
Let me explain on the Huddle call - it's about searching the GitBook to find the action on how to handle a schematron message.
