### ISSUE TITLE
PMIDs and DOIs for book references

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#127]
- [ ] Exeter to update Kriya to allow PMIDs in book references
- [ ] Update Crossref tool so Books are checked against Crossref DOI database

**Comment by Melissa37** [comment]
Added to Kriya 2 GitLab board: https://gitlab.com/ExeterPremedia/reqs/cust/elife-kriyadocs/-/issues/19

**Comment by FAtherden-eLife** [comment]
PMID for book refs already permitted.

Need to confirm books are validated against crossref, but assume that they are.
