### ISSUE TITLE
Update guidance for software with RRIDs

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#128]
- [x] Clarify whether software with RRIDs needs to be added as a software ref

**Comment by naushinthomson** [comment]
@eLife-Exeter We have updated the guidance for when software references need to be added (see changelog on the [software refs page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/references/software-references)).
