### ISSUE TITLE
Create feature content page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#130]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents 
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [ ] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by FAtherden-eLife** [comment]
Just adding a thought I had here before I forget - Should we share this page with features as well?

**Comment by JGilbert-eLife** [comment]
Already planning to do so!

**Comment by FAtherden-eLife** [comment]
Perfect - I should've realised you will have already thought of that! :+1:

**Comment by FAtherden-eLife** [comment]
FYI - Adding a new test `feature-bio-test-6`, which is in the G Spreadsheet. I will commit it tomorrow.

**Comment by JGilbert-eLife** [comment]
@bcollins14 @naushinthomson @Melissa37 @FAtherden-eLife 

First draft done! https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/feature-content

All feedback welcome - I figure we're running it around the team before sharing with Features?

Questions -

1) Do we need something explicit linking to the figures page re illustrations? All the warnings will point there rather than here, I think.

2) I didn't include any specific XML at the end, I've just dotted it through where it was needed for the schematron. Should I summarise at the end for educational purposes? E.g. include XML for sub-display channel, template type etc?

3) Have I sufficiently covered publication issues for features? I figure that we'll have a full publishing page that I can link to at some point.

**Comment by Melissa37** [comment]
>How to handle the different types of Feature content
first line - F should be f to follow the rest of the document?

**Comment by Melissa37** [comment]
Can we lower case references to Production and Feature content throughout?

Personal preference :-)

**Comment by Melissa37** [comment]
>Editorial - an editorial piece written by one or more of eLife's deputy or senior editors, or the editor-in-chief, usually addressing a specific issue or development in the scientific community in general and/or at eLife in particular.

I thought these were only written by eLife staff or editor-in-chief

**Comment by Melissa37** [comment]
>Magazine templates


Can we link to the templates on the googledrive? So people can look at the full template if they want?

**Comment by Melissa37** [comment]
>Title prefix - a brief category label displayed in front of the title, currently captured in the XML as a 'sub-display-channel' subject element. The text should be in title case.

Add this is not a pre-defined list of terms.

**Comment by Melissa37** [comment]
>Feature content is submitted to eLife via two paths: articles arriving through the the normal submission process and articles commissioned or invited by the Feature team. 

Double 'the'

**Comment by Melissa37** [comment]
>Feature content is submitted to eLife via two paths: articles arriving through the the normal submission process and articles commissioned or invited by the Feature team.

Suggest change to:

>Feature content is submitted to eLife via one of two paths: the article arriving through the normal submission process OR the article is commissioned or invited by the Feature team.

**Comment by Melissa37** [comment]
> and will likely have decision and response sections as a result.

Suggest change to:

> and will likely have a decision letter and author response as a result.

**Comment by Melissa37** [comment]
>The article file will be renamed to indicate which template should be used and the any figure files 

remove the from in front of any

**Comment by Melissa37** [comment]
>Feature content should be processed as soon as possible after export (within 24 hours for Insights, Editorials and Template 3/4 content, within 48 hours for Template 5 content).

48 hours for feature 5? I did not know this! I need to add it to the agreements with Exeter. Can you confirm this is what Peter said? Thanks :-)

**Comment by Melissa37** [comment]
>In very rare cases where copy-editing is required, the Features team will advise the Production team who will request that the article is moved into the copy-editing workflow.

add a comma in front of who

**Comment by Melissa37** [comment]
>The author's name should be given in bold and the bio should not end in a full-stop.


Suggested change:

>In the author bio the author's name should be bold and the bio should not end in a full-stop.

**Comment by Melissa37** [comment]
>Once author proofing is complete, the article will move into the 'Feature Review' stage to allow the Features team to check over the authors' edits. They will be alerted with an email notification when this occurs.

Can we suggest features team accepts the author changes? It makes sense and is more efficient

**Comment by Melissa37** [comment]
>If the authors have requested an additional proof, the article should be sent back to them following the normal procedure (signing the article off to Author review for a second time).

If the author makes more changes do we pass to Features to check? Should we always have a second post-author stage for Features too?

**Comment by Melissa37** [comment]
>Insight articles should be published alongside the research content to which they are related. Usually, the typeset version of record for this content will be ready by the time the Insight has gone through proofing. In the event that the research content is not ready for VoR publication and it has not been published as an accepted manuscript, the Insight should be held until the related article is ready. If the article has been published on acceptance (PoA), the Features team should be contacted to ask if the related Insight should be held until the VoR is ready. They may decide to go ahead with publication of the Insight as it will be linked to the PoA version of the research content.

Need to also mention the need to contact the author to ensure they are ready to hold publication until the Insight is ready

**Comment by Melissa37** [comment]
>Error: bio must contain a bold element which contains the name of the author - XXXXXX.


Chane to>Error: bio must contain a bold element that contains the name of the author - XXXXXX.

**Comment by Melissa37** [comment]
>Action: Only bold formatting (<bold>) elements are allowed within an author's bio. Any other formatting and any hyperlinks should be removed. The message will indicate which disallowed elements are present and the text of the affected bio will be included at the end.

Not allowing hyperlinks in an author bio - is that a Continuum or Kriya issue? Presumably, this should be acceptable?

**Comment by Melissa37** [comment]
>This elements (e.g. formatting, bold, italics) should be removed

Either this element or these elements

**Comment by Melissa37** [comment]
>Action: This error indicates the template type in the XML (see above) is not 1, 2, 3, 4 or 5. Correct the template type to the one indicated by the name of the article file in the export package (e.g. ). If the template number given in the article file name is a value other than 1, 2, 3, 4 or 5, the Production team should check which value the Feature team intended for the article.

Does this display in Kriya? I assumed it would have to be corrected by Exeter staff, but this is not clear from the action

**Comment by Melissa37** [comment]
>feat-custom-meta-test-3	and feat-custom-meta-test-4	

Same issue as above - can production staff change this?

**Comment by Melissa37** [comment]
>This error indicates that zero or more than one elements of this type are present.

remove plural from element

**Comment by Melissa37** [comment]
>feature-subj-test-4
Error: There is more than one sub-display-channel subjects. This is incorrect.

should be 'There are'

**Comment by Melissa37** [comment]
Nice! Thanks James :-)


>Do we need something explicit linking to the figures page re illustrations? All the warnings will point there rather than here, I think.

Yes, thnk that's a good idea.

>I didn't include any specific XML at the end, I've just dotted it through where it was needed for the schematron. Should I summarise at the end for educational purposes? E.g. include XML for sub-display channel, template type etc?

Would be good if just following the same model as other pages

>Have I sufficiently covered publication issues for features? I figure that we'll have a full publishing page that I can link to at some point.

Yes I think so!!

**Comment by FAtherden-eLife** [comment]
>> feat-custom-meta-test-3 and feat-custom-meta-test-4

> Same issue as above - can production staff change this?

> @FAtherden-eLife can we flag this for Libero - if we have this in the XML and we can change it, does that mean the template will update automatically? I wonder :-)

Yeah good point. For MVP, I reckon we could just manually edit the XML files ourselves, but it would be nice post-MVP to do. 
I've [raised a ticket in the Editor repo](https://github.com/libero/editor/issues/554). It would also be good to confirm this with Exeter when we're discussing integration with them.

**Comment by FAtherden-eLife** [comment]
> In addition to this there are four categories of Feature article that come through the Production process:

Suggest changing to
> In addition to this there are three categories of feature article that come through the production process:

**Comment by FAtherden-eLife** [comment]
In the Magazine templates table, is it worth adding which have author contributions? I think 4 and 5 do (4 is less common but I've seen it) - the rest don't (I think), or does that still need confirming with Features?

**Comment by FAtherden-eLife** [comment]
> feature-bio-test-6

In the action there's an example of where this can be ignored. This example wouldn't fire this rule. It's checking that the content of the affiliations is in the bio (specifically it tokenises each affiliation by comma, and then checks that each of those tokens is present in the bio - so in the example `Department of Genetics`, `University of Bristol`, `Bristol`, `United Kingdom`, `Institute of Neuroscience` and so on). 

I've only myself seen this when the apostrophes are slightly different in them (or similar other character differences), although I'm obviously not working on them so much anymore.

**Comment by FAtherden-eLife** [comment]
> feature-bio-test-5

This is actually checking that the only child of `<bio>` is a `<p>` element. If there is a child of bio which is not a `p`, then it will fire.

**Comment by FAtherden-eLife** [comment]
Please can you add `insight-asbtract-impact-test-1` and `insight-asbtract-impact-test-2`? 

I will correct the typos in the ids so that they are `insight-abstract-impact-test-1` and `insight-abstract-impact-test-2`

**Comment by FAtherden-eLife** [comment]
> Do we need something explicit linking to the figures page re illustrations? All the warnings will point there rather than here, I think.

I suggest it should probably go the other way - from the figures page to the Features page.

**Comment by FAtherden-eLife** [comment]
> I didn't include any specific XML at the end, I've just dotted it through where it was needed for the schematron. Should I summarise at the end for educational purposes? E.g. include XML for sub-display channel, template type etc?

I personally think it's fine, you've provided feature specific snippets in the relevant places which I think is sufficient.

**Comment by FAtherden-eLife** [comment]
> Have I sufficiently covered publication issues for features? I figure that we'll have a full publishing page that I can link to at some point.

Suggest putting the insight paragraph before this paragraph:
> Publication of feature content follows the same process as for research content. If no specific date has been requested for Editorials or Feature articles, they should be published as soon as they are ready to go.

and suggest the following edit:
> Publication of **other** feature content follows the same process as for research content. If no specific date has been requested for Editorials or Feature articles, they should be published as soon as they are ready to go.

**Comment by FAtherden-eLife** [comment]
Is it worth just summarising the workflow steps for feature content at the beginning of the 'Production process for feature content' section? Maybe just a bulleted list?

**Comment by FAtherden-eLife** [comment]
Is it worth including `disp-subj-value-test-6` here? Or should we save that for a different page?

**Comment by FAtherden-eLife** [comment]
Similarly `back-test-7` is a test which will only fire in feature content. Is it worth including here or in a separate page?

**Comment by FAtherden-eLife** [comment]
That's it from me - thanks for this James!

**Comment by naushinthomson** [comment]
>This content is overseen by the Features team and consists in part of blogposts and podcasts that do not required Production intervention to publish.

change to 

>This content is overseen by the Features team and consists in part of blogposts and podcasts that do not require Production intervention to publish.

**Comment by naushinthomson** [comment]
I don't think I have anything else to add! Thanks James!

**Comment by FAtherden-eLife** [comment]
Please also add the newly added test `final-feat-ok-test`. (there's a separate equivalent for digests which should presumably go in that page).

**Comment by bcollins14** [comment]
In the key box info, where you say 'This content is not currently displayed online.', is it worth mentioning that instead we include the related article to the right hand of the webpage?

**Comment by bcollins14** [comment]
Sometimes Features will send their corrections via slack in addition to emails so would be good to mention this.

**Comment by bcollins14** [comment]
In the publication section, could we talk about the press side of things? That Peter will give Emily the date that the Insight should be ready and that if the Insight isn't ready, that the press publication is prioritised.

**Comment by bcollins14** [comment]
Otherwise, looks good. Thanks James :)

**Comment by JGilbert-eLife** [comment]
> Is it worth including `disp-subj-value-test-6` here? Or should we save that for a different page?

I think I'd prefer to cover this on an article types page. I assume we are going to have one?

**Comment by JGilbert-eLife** [comment]
> Please also add the newly added test `final-feat-ok-test`. (there's a separate equivalent for digests which should presumably go in that page).

Done - do we need to convert these into author queries are pub check?

**Comment by JGilbert-eLife** [comment]
> > Insight articles should be published alongside the research content to which they are related. Usually, the typeset version of record for this content will be ready by the time the Insight has gone through proofing. In the event that the research content is not ready for VoR publication and it has not been published as an accepted manuscript, the Insight should be held until the related article is ready. If the article has been published on acceptance (PoA), the Features team should be contacted to ask if the related Insight should be held until the VoR is ready. They may decide to go ahead with publication of the Insight as it will be linked to the PoA version of the research content.
> 
> Need to also mention the need to contact the author to ensure they are ready to hold publication until the Insight is ready

Or does that need to go on a publication page, since that's about holding the research content?

**Comment by JGilbert-eLife** [comment]
> In the publication section, could we talk about the press side of things? That Peter will give Emily the date that the Insight should be ready and that if the Insight isn't ready, that the press publication is prioritised.

Again, I think this needs to go on a publication page.

**Comment by JGilbert-eLife** [comment]
> > feature-subj-test-4
> > Error: There is more than one sub-display-channel subjects. This is incorrect.
> 
> should be 'There are'

I've fixed this - @FAtherden-eLife, did this get corrected in the actual schematron?

**Comment by JGilbert-eLife** [comment]
> > Editorial - an editorial piece written by one or more of eLife's deputy or senior editors, or the editor-in-chief, usually addressing a specific issue or development in the scientific community in general and/or at eLife in particular.
> 
> I thought these were only written by eLife staff or editor-in-chief

We have had them from other editors in the past.

**Comment by FAtherden-eLife** [comment]
>>> feature-subj-test-4
>>> Error: There is more than one sub-display-channel subjects. This is incorrect.

>> should be 'There are'

> I've fixed this - @FAtherden-eLife, did this get corrected in the actual schematron?

I've changed this to:
> There is more than one sub-display-channel subject. This is incorrect.

in the Schematron and GitBook.

**Comment by JGilbert-eLife** [comment]
Notes for a meeting with Features:

- Ask Features about converting [OK] to author queries?
- Ask Features about contributions vs templates
- Ask Features about how they want to handle second proofs

**Comment by JGilbert-eLife** [comment]
I'm still waiting for a wider discussion with Features about what's allowed in each template but in the meantime, I've shared this with Exeter since I don't anticipate the actual schematron rules will change much (except insofar as we'll update them in response to any template changes).

**Comment by FAtherden-eLife** [comment]
`insight-abstract-impact-test-1` and `insight-abstract-impact-test-2` are also on the Impact statement page. Which should I be linking to in the Schematron?

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife Did you already update the impact statement page to remove them from there?

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife, no I'm asking where they should be placed (impact statement page or feature page).

**Comment by JGilbert-eLife** [comment]
Ah - spelling mistake on the impact statement page meant they didn't show up when I searched them. Impact statement page seems more appropriate given out treatment of other item-specific rules. I've made the required changes.

**Comment by FAtherden-eLife** [comment]
Sounds good to me - thanks.
