### ISSUE TITLE
Create 'managing production inbox' page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#132]
- [x] Import previous guidance into gitbook 
- [x] Update as necessary
- [x] Team approved
- [x] Share with prepress
- [x] Revise based on feedback

**Comment by JGilbert-eLife** [comment]
Probably worth stating "The email will then be tagged with that user’s name **and moved to their inbox.**"

**Comment by JGilbert-eLife** [comment]
"‘Pending’ status can be used for emails that you want to come back to later, or to keep an eye on."

Is it worth making it clear that this moves them to a separate section in Hiver that will need to be checked?

**Comment by naushinthomson** [comment]
https://app.gitbook.com/@elifesciences/s/schematron/toolkit/managing-the-production-inbox

Here's the page for managing the production inbox - please let me know if there's anything else that needs to be covered or if anything is incorrect!

**Comment by Melissa37** [comment]
>The email will then be tagged with that user’s name and moved to their inbox.

Suggest adding some screenshots of what that does or what their inbox is

**Comment by Melissa37** [comment]
>You can view an email’s history, and any notes that have been added to it (as well as adding your own) in the activity bar beneath this:


How do you get to that?

**Comment by bcollins14** [comment]
"..that everyone in the department has access to."

Can we maybe change this to team? Department makes me think grander than our little wholesome posse.

**Comment by Melissa37** [comment]
>Author Correspondence - for any and all emails from authors

Maybe note this does not include an automated email being delivered to the author from Kriya, just if they respond to is

**Comment by bcollins14** [comment]
Is it worth noting that even though the email is moved to our inbox, the rest of the team can still search/see this email?

**Comment by Melissa37** [comment]
>Similarly, authors receive another email when their proof is overdue, one at 2 days, and one at 4 days. These can be closed.

Maybe add a statement about why we receive them (ie what's the point in getting them if we just close them!)

**Comment by Melissa37** [comment]
>Every time an article with videos is sent to Continuum, we receive a processing report from Glencoe, our video hosting site. If all videos are listed underneath the ‘succeeded’ heading, this email can be closed. If any are listed under ‘failed’ then action is needed.

Explain what the action is

**Comment by bcollins14** [comment]
Also, I'm not sure if you have mentioned that when we send an email, we can choose to send it and it will automatically close or be set to pending.

**Comment by Melissa37** [comment]
>This is an automatic email that notifies us when the post-acceptance check has been completed by Editorial Office. This can be closed.

@JGilbert-eLife please remind me why we want this email and we should add why to the gitlab page :-)

**Comment by Melissa37** [comment]
>If the decision letter has loaded, this email can be closed. If the article is not yet in Kriya, this email should be left open until it is, and the decision letter will then need to be re-loaded at that point. 

Is there still a delay? ie how long do we wait to see it's loaded before we contact Exeter and what's the procedure for contacting Exeter?

**Comment by FAtherden-eLife** [comment]
I think we need to include what to do when we receive an email for Decision letter loading failures.

**Comment by Melissa37** [comment]
>Digest

What do we do if it's not loaded and how long do we wait before our next action if it's not loaded?

**Comment by FAtherden-eLife** [comment]
Same ([as above](https://github.com/elifesciences/schematron-gitbook/issues/132#issuecomment-645863361)) for digest loading emails.

**Comment by bcollins14** [comment]
Under Striking images, I think it is worth noting that authors can also word these as promotional images, graphical abstracts etc

**Comment by Melissa37** [comment]
>Our Features team regularly send us a list of the latest articles that are not getting digests. They will have already marked them as ‘no-digest’ articles in Kriya, however we need to check all of them to ensure that the labels have stuck.

Is it worth expanding on "stuck"?
Are there common instances of why it might not stick?

**Comment by FAtherden-eLife** [comment]
The No-digest email process is longer than has been added here (adding no digest to the editorial sheet as well). Unsure if this needs expanding on this page though (so I understand that's why you might not have included it!)...

**Comment by bcollins14** [comment]
Under Press emails, it may be good to also remind the reader that press tags should also be added to these.

**Comment by FAtherden-eLife** [comment]
> Emily will also cc us in if she asks Sue at Editorial Office to put any recently accepted papers on hold, whilst she looks into potential press for them. There is no action needed for these emails, except to read them and check that there aren’t any issues.

What about when she asks Sue to schedule PoA publication, and we need to add it to the prod team actions sheet, and check where the VoR currently is in the Production pipeline.

**Comment by Melissa37** [comment]
Add to Glossary:
PoA (I like PoA and not POA :-))
Digest
bot
PMC
PubMed
Crossref

**Comment by Melissa37** [comment]
Will the links to Googledocs be swapped out for Gitbook pages?

**Comment by FAtherden-eLife** [comment]
> Our tags:

Please also include new versions

**Comment by FAtherden-eLife** [comment]
Is it worth including details about how emails from GitLab/GitHub issues should be dealt with?

**Comment by FAtherden-eLife** [comment]
We regularly receive Crossref maintenance emails. Is it worth covering these too?

**Comment by FAtherden-eLife** [comment]
Is it worth covering the scenario in which we receive an automated OOO type response from a corresponding author from a proofing email? Or is that too niche for this page?

**Comment by FAtherden-eLife** [comment]
We also receive 'PublishFinalPOA Success!' emails. Should this be alluded to somewhere?

**Comment by JGilbert-eLife** [comment]
"Author Correspondence: This is for author emails we forward on to Exeter which contain changes that they should make during the Post-author validation stage."

This does NOT correspond to a tag - we should not be tagging the emails that we forward to Exeter with the Author Correspondence label as that is intended to record messages coming from the author.

Not sure it's correct to say that there's any equivalence with any of them, actually - the subject line prefixes as specifically to help Exeter sort their emails whereas the Hiver labels are for us to sort and track emails on our side. It's probably better to treat them as separate things.

**Comment by JGilbert-eLife** [comment]
Think I mentioned this elsewhere but it would be great if the Email types could be alphabetically ordered.

**Comment by JGilbert-eLife** [comment]
"If the proof is still not submitted, we will receive an email asking us to chase the authors manually."

I think we should mention that chasing should be escalated to copy in other corresponding author/first author(s).

**Comment by JGilbert-eLife** [comment]
"Manuscript processing"

Video processing?

**Comment by JGilbert-eLife** [comment]
"XML notification emails"

Please could you include screenshots of both PoA and VoR versions?

**Comment by JGilbert-eLife** [comment]
"Check the decision letter has loaded on the Kriya dashboard."

Including a no-digest tagged example as the after shot could be confusing?

**Comment by JGilbert-eLife** [comment]
"No-digest emails"

This needs to cover updating https://docs.google.com/spreadsheets/d/1oy8TIwsedSYdy6n3_SFuqUcJ4Ljeg7tXnTS6q2CsNI8/edit?ts=57fe457c#gid=0

**Comment by JGilbert-eLife** [comment]
"PMC failures"

I think it would be better to cover the daily summaries e.g. "DTS: Daily Summary for eLife Sciences Publications, Ltd - Jun 23, 2020", so that we proactively trace errors without waiting for PubMed to chase us. Also, please remove reference to Tori in particular - our contact at PMC has changed before and could again.

**Comment by naushinthomson** [comment]
- [ ] Review 'New versions' tag description
- [ ] What do we do if digests aren't loaded and how long do we wait before our next action if it's not loaded? Why might a 'no digest' not stick?
- [ ] How long does it take for a decision letter to be loaded?
- [ ] Should we add responses to OOO emails, Crossref maintenance emails, GitLab/GitHub issues
- [ ] Review chasing protocol
- [ ] Review no-digest section
- [ ] Review Pubmed loader section
- [ ] Review XML section

**Comment by naushinthomson** [comment]
@FAtherden-eLife Just assigning you to add the info about PMC failures! :)

**Comment by FAtherden-eLife** [comment]
I've added the PMC failure content - please review.
