### ISSUE TITLE
Create article assets page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#135]
- [x] Create page 
- [x] Import 'allowed assets' doc into gitbook
- [x] Add description of what is being covered
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife - probably a question for you: am I remembering correctly that we want the IDs for Chemical structures and Schema to be c1 and s1 respectively, but they're stuck as C1 and S1 due to Kriya?

Also, both currently used elife-12345-fig1 style filenames for the main text but e.g. elife-57824-app1-chem1 in the appendices. I presume our preference would be to make this consistent as elife-12345-chem1 and elife-12345-scheme1 for the main text too?

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife yeah, we're stuck with what we have for Kriya 1. What we want in Kriya 2 is: 
* Chemical structures - `chem0`
* Scheme - `scheme0`
* Appendix Chemical structures - `app0chem0`
* Appendix Scheme - `app0scheme0`

There's a ticket open for this on [the Kriya 2 board](https://gitlab.com/ExeterPremedia/reqs/cust/elife-kriyadocs/-/issues/23).

> Also, both currently used elife-12345-fig1 style filenames for the main text but e.g. elife-57824-app1-chem1 in the appendices. I presume our preference would be to make this consistent as elife-12345-chem1 and elife-12345-scheme1 for the main text too?

Yeah, I agree, consistency would be best.

**Comment by JGilbert-eLife** [comment]
Ta! I realised my mistake with the labels just now!

**Comment by JGilbert-eLife** [comment]
@naushinthomson @FAtherden-eLife @bcollins14 @Melissa37 - OK, I've completed the list of allowed assets. I don't think we need much else on this page, do we?

**Comment by FAtherden-eLife** [comment]
A full stop is needed at the end of almost all labels. Should we include the full stops in the tables here?

**Comment by FAtherden-eLife** [comment]
I think it would be helpful to provide a few of XML examples on this page, even though they're likely to be included elsewhere as well.

**Comment by FAtherden-eLife** [comment]
I think (in rare cases) we also allow Audio file 1?

**Comment by FAtherden-eLife** [comment]
If we want to add audio file 1, I'll very likely need to update the Schematron I think.

**Comment by FAtherden-eLife** [comment]
Do we need to include `inline-graphic`s in this page too?

**Comment by Melissa37** [comment]
>The term 'asset' refers to a figure, video, table or file associated with an article. These items are used to enhance the text of the article, providing illustration, raw data or the means to replicate the research.

Needs comma before the 'or'?

**Comment by Melissa37** [comment]
>eLife is relatively unique in allowing multiple supplements to 'top level' assets in order to provide more information to a reader. For example, a figure may be supplemented with additional sub-figures (figure supplements), source data files and/or videos.

Oxford comma required?

**Comment by Melissa37** [comment]
>The following assets appear within the main text of an article. Most of these should be placed after the paragraph in which their first citation in the text appears

I wonder whether it could be made clearer that a sub-asset is always grouped/part of its parent.

**Comment by Melissa37** [comment]
>The following assets are allowed with boxes.

Would it be clearer to say 'within" instead of "with"?

**Comment by Melissa37** [comment]
Is it worth putting some XML examples at the bottom?

**Comment by Melissa37** [comment]
Looks good! Thanks :-)

**Comment by JGilbert-eLife** [comment]
OK, I've updated this page in response to the comments and have added XML samples. Let me know if I've missed anyone's favourite forty-asset pile-up for those!

@FAtherden-eLife I've added audio files based on how we've handled them before. Are you happy with this?

**Comment by FAtherden-eLife** [comment]
Thanks @JGilbert-eLife, looks good. Only question left from my perspective is [this one](https://github.com/elifesciences/schematron-gitbook/issues/135#issuecomment-675520097).

**Comment by JGilbert-eLife** [comment]
Ah! Yes, sorry, I think I was under the impression that we'd discussed that and decided not to include them, but I suspect I was thinking of another context. Let me add those in ASAP.

**Comment by FAtherden-eLife** [comment]
Thanks!

**Comment by naushinthomson** [comment]
Looks good to me!

**Comment by bcollins14** [comment]
Thanks! It looks very swish, love the table usage 👍

**Comment by FAtherden-eLife** [comment]
Thanks - that's everyone and, aside from stuff I can't fully flesh out at this stage and a separate page about how to clone, PR etc. in Git, I think we're done.
