### ISSUE TITLE
Update Interacting with authors page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#136]
- [x] Add email template to hiver about cover images vs striking images response
- [x] Add explanation of this email template in interacting with authors page
- [x] Let Rowena know we get this query often from authors
- [x] Rowena to suggest improving language of template email to Product

**Comment by naushinthomson** [comment]
@bcollins14 @JGilbert-eLife @FAtherden-eLife @Melissa37 Ok with this addition? https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/toolkit/interacting-with-authors#cover-image-response
- [ ] Becky approved
- [ ] James approved
- [ ] Fred approved
- [ ] Melissa approved

**Comment by Melissa37** [comment]
Yes, that's cool, but can we talk to Rowena about changing the text in the your article is published email so it's clearer?

Thanks!

**Comment by naushinthomson** [comment]
> Yes, that's cool, but can we talk to Rowena about changing the text in the your article is published email so it's clearer?
> 
> Thanks!

Yup I've already sent her an email about this!

**Comment by JGilbert-eLife** [comment]
@naushinthomson 'answers' rather than 'clarifies? Clarifies your question sounds a bit like we've cleared up what they were asking rather than actually answered it!

**Comment by bcollins14** [comment]
Can we maybe change this sentence a bit? 

_The cover image is different from the striking image, which may be used to highlight published articles on the eLife website's homepage and on social media._ 

to 

_We are currently unable to incorporate striking images into the covers, instead these may be used to highlight published articles on the eLife website's homepage and on social media._ 

Or something to that effect?
