### ISSUE TITLE
Update Software refs page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#140]
- [x] Clarify that if there are RRIDs we don't need to add AQ, and if authors have added a software ref this is fine to leave. 

### Definition of done
- [x] Updates completed
- [x] Team reviewed and approved page?

**Comment by naushinthomson** [comment]
@Melissa37 @bcollins14 @FAtherden-eLife @JGilbert-eLife 
In light of recent discussions about what we want for software references, can I ask for a re-review of the following sections?:
- The [What needs to be added?](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/references/software-references#what-needs-to-be-added) section
- The [When to add software references](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/references/software-references#when-to-add-software-references) section
- The action of [github-web-test](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/references/software-references#github-web-test). Do we want to query authors who have cited github repos and not provided version numbers? They probably won't know what we mean if we use the query as it stands - should we specifically ask for which commit they used or not bother?

**Comment by FAtherden-eLife** [comment]
For 'What needs to be added?', can we change the Mandatory cells for Source and Publisher from 'No' to 'Yes (or Publisher must be entered instead)' and 'Yes (or Source must be entered instead)'?

**Comment by FAtherden-eLife** [comment]
The action for github-web-test is fine I think.
Although, the Author fields in that specific example are not correct, (should be O'Toole A and McCrone JT, based on the repo), but I don't know if the expectation is that Exeter would find out that information, or just leave the author details as they are in this scenario (given that the query has been added).

**Comment by JGilbert-eLife** [comment]
On the point about host versus publisher - maybe an '(if applicable)' in the bullet pointed list descriptions?

**Comment by JGilbert-eLife** [comment]
The screenshot with the caption "All the software here needs to be added as software references and cited properly" is probably not terribly useful to a new starter without some highlighting to make clear where the software is in that paragraph.

**Comment by JGilbert-eLife** [comment]
Agree that the github-web-test action is OK. However, not sure how wide-covering the examples are with regards to distinguishing repos from blog posts.
