### ISSUE TITLE
Create Oxygen page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#141]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [ ] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter and invite feedback

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by Melissa37** [comment]
https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/oxygen#how-to-set-up-the-crossref-transformation-scenario

**Comment by Melissa37** [comment]
>First, ensure that you have cloned a version of the elife Schematron to you local machine, in a suitable location, such as in your Documents folder.

This makes me realise we need a GitHub page too :-) 
To include instructions on what repos we use and how to clone GitHub pages

**Comment by Melissa37** [comment]
>9. Click the folder symbol next to the URL field, navigate to and select the Schematron file which you would like to set up the validation scenario for (either pre-JATS-schematron.sch or final-JATS-schematron.sch):

Maybe add that you will find this in the folder where you cloned the GitHub repo (seems obvious but not to a newbie!)

**Comment by Melissa37** [comment]
>You have now created a validation scenario. You can then run this scenario on numerous different XML files by opening the 'Configure Validation Scenario(s)' pop-up, ticking the scenario with the name which you just created, and then clicking 'Apply associated (1)'.

It would be useful to see a screenshot of what someone would see if they run one and maybe add a final statement that tells the user how to now use this Gitbook to work out what the messages mean?

**Comment by Melissa37** [comment]
>Keyboard shortcuts

Should it indicate these are Mac shortcuts and not PC?

**Comment by FAtherden-eLife** [comment]
@naushinthomson, @JGilbert-eLife, @bcollins14, please can you review this page when you get a chance - https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/oxygen?

**Comment by bcollins14** [comment]
To be honest, I didn't know what 'Note that it is proprietary..' meant until I asked Sam >_<

**Comment by bcollins14** [comment]
> For example clicking the left most column heading (which usually has **not** text),

I assume that is a typo?

**Comment by bcollins14** [comment]
> Some messages will contain GitBook links at the end of them. These are messages which have been covered in this GitBook, and you can follow the link to be taken to the accompanying page and description/action for that message.

Would it be worth mentioning that you can't click the URLs directly? At least I cannot unless I am missing a trick.

**Comment by bcollins14** [comment]
Other than that, I am done. Thanks!

**Comment by FAtherden-eLife** [comment]
> To be honest, I didn't know what 'Note that it is proprietary..' meant until I asked Sam >_<

Changed to 'not open source' :smile: :dollar::dollar:

**Comment by FAtherden-eLife** [comment]
> Would it be worth mentioning that you can't click the URLs directly? At least I cannot unless I am missing a trick.

Yup, same here - changed.

**Comment by JGilbert-eLife** [comment]
Looks good to me - I corrected a couple of small typos.

Is this an appropriate page to cover offline validation as requested by Exeter, or is that best done outside of Oxygen? (The instructions you once gave me on doing this are buried somewhere in Slack!)

**Comment by FAtherden-eLife** [comment]
> Is this an appropriate page to cover offline validation as requested by Exeter, or is that best done outside of Oxygen? (The instructions you once gave me on doing this are buried somewhere in Slack!)

It's best done in BaseX - I've added a page for this specific case in a generic BaseX page - https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/basex.

**Comment by naushinthomson** [comment]
> This makes me realise we need a GitHub page too :-)
> To include instructions on what repos we use and how to clone GitHub pages

@Melissa37 I've made an [issue](https://github.com/elifesciences/schematron-gitbook/issues/144) for this now and it is in the Backlog :)

**Comment by naushinthomson** [comment]
Is it worth saying when you would need to do the Crossref transformation and linking to the [fixing failures page](https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/fixing-crossref-dryad-failures)? @bcollins14 Is the plan to delete the 'what to do when a failure occurs' section and just linking to the Oxygen page?

**Comment by naushinthomson** [comment]
That's all from me!

**Comment by FAtherden-eLife** [comment]
Add info on editing validation/transformation scenarios
