### ISSUE TITLE
Update Toggl page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#142]
- [x] Review Toggl tags and workflow
- [x] Update page as necessary
- [x] Becky approved?
- [x] James approved?
- [x] Melissa approved?
- [x] Naushin approved?
- [x] Fred approved?

**Comment by bcollins14** [comment]
Looks great, thanks James! 👍

**Comment by Melissa37** [comment]
Could we change

>to double-check the team has time to work on projects outside the day-to-day tasks

To
>to monitor the team's availability to work on projects outside the day-to-day tasks

**Comment by Melissa37** [comment]
>To help monitor the performance of the Kriya proofing system, it is helpful to track the time taken to refresh the page and to assign articles. However, it's accepted that other tasks may be completed while the page is reloading, so these should take priority in terms of tracking.


I don't really understand what the instruction is. If Toggl cannot track two things at once, and people are favouring other task they do concurrently, the data we get from this is incomplete?

**Comment by Melissa37** [comment]
>Meetings
Recommended description:
The name/purpose of the meeting

Should meetings have a list of preset ones, to help have clean data? eg Staff meeting; huddle; update with Melissa; Exeter call, Press meeting?

**Comment by Melissa37** [comment]
As a general point, as the tags have evolved there is inconsistent use of capitalisation and it bugs the copy editor in me :-)

eg all the "Emails:" are followed by a lowercase, except for "Emails: Pub date query"
Projects have Continuum Checks, yet Home page.

Could we clean that up or would it mess with the data for you James?

**Comment by JGilbert-eLife** [comment]
> > To help monitor the performance of the Kriya proofing system, it is helpful to track the time taken to refresh the page and to assign articles. However, it's accepted that other tasks may be completed while the page is reloading, so these should take priority in terms of tracking.
> 
> I don't really understand what the instruction is. If Toggl cannot track two things at once, and people are favouring other task they do concurrently, the data we get from this is incomplete?

I'd like to straw-poll the others about what they do with refreshing. @naushinthomson @bcollins14 - how have you been recording refreshing the page? Have you? Or should we just drop this?

For the meetings, @Melissa37, do we care about getting fine details of meetings? How long we huddle, for example? I'm happy to add preset options, but I'd like more guidance from the team on what those should be! :)

**Comment by naushinthomson** [comment]
> I'd like to straw-poll the others about what they do with refreshing. @naushinthomson @bcollins14 - how have you been recording refreshing the page? Have you? Or should we just drop this?

I believe we've already covered this in a chat on huddle now :)

**Comment by naushinthomson** [comment]
There are descriptions of each of the email tags except for 'Emails: reproducibility' - is this still to be added?

Otherwise this looks fine to me! I've asked Claudia to have a look over it as well :D

**Comment by naushinthomson** [comment]
From @griffithsc :D 
>Very comprehensive and helpful in that it explains exactly when to use each tag/project and provides clarification on what to include in the description (which I wasn’t 100% sure on before)
