### ISSUE TITLE
Create eLife website and communication house style page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#147]
- [x] Create page 
- [x] Add description of checks required on this content, compiled from current protocol [documents](https://docs.google.com/document/d/1cVwSo0O4UPLYI_GjOZxvcLMh9U-ImIR8maValVFdOU8/edit)
- [x] Team approved page

**Comment by bcollins14** [comment]
@Melissa37 This page has now been transferred [https://app.gitbook.com/@elifesciences/s/productionhowto/elife-website-and-communication-house-style](url)

I assume the rest of Production do not need to approve this?

**Comment by Melissa37** [comment]
Yes this is cool. @naushinthomson can we close this ticket without all the actions signed off?

**Comment by naushinthomson** [comment]
Yep, I'll just tweak the ticket checklist and close this!
