### ISSUE TITLE
Update Fixing crossref failures page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#148]
- [x] Update page to add information about how to resolve non-Dryad failures (using manual system of deleting rel:program elements)
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [ ] Team reviewed and approved page?
- [ ] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by bcollins14** [comment]
Hello all! @naushinthomson @JGilbert-eLife @Melissa37 @FAtherden-eLife 

I have updated this page. The new sections are 'What to do when a failure occurs (non-Dryad)' and 'Replacing the XML at Crossref (non-Dryad)' [https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/toolkit/fixing-crossref-dryad-failures](url)
 
Thanks :)

**Comment by JGilbert-eLife** [comment]
I don't think you mentioned changing the timestamps within the XML file in addition to the file name? It might also be worth being clear about what needs to be changed and why (e.g. avoiding conflicts with previously submitted XML).

Other than that, it looks good!

**Comment by naushinthomson** [comment]
Other than what James said I have nothing to add, looks good!

**Comment by Melissa37** [comment]
@bcollins14 Can you add a change history to it, identifying what you've done and date this?
