### ISSUE TITLE
Update Tables page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#151]
- [x] Add Inline images in tables section to page
- [x] Link out from figures page - under 'Unlabelled images in the article file', add the sentence 'Inline images may also be present within tables - for more about this, see here.' before the final sentence of the first paragraph.
- [x] Add schematron message and action about titles of appendix tables ending in fullstops.
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by FAtherden-eLife** [comment]
@bcollins14, @naushinthomson, @JGilbert-eLife, @Melissa37, I've updated this page with a small section on inline images. Any further information need adding here?
https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/allowed-assets/tables#inline-images

**Comment by Melissa37** [comment]
Looks good to me

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife Have you yet to add some of the images, or have they been lost somehow? I think I'm only seeing one out of three (?).

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife, sorry not sure i understand the question. Do you want me to add images of the tables in that section?

**Comment by JGilbert-eLife** [comment]
This bit seems to be missing images referred to in the text, but there wasn't anything in your initial comment about still needing to add images:

![Screen Shot 2020-09-08 at 12 19 01](https://user-images.githubusercontent.com/1785305/92469938-96464a00-f1cd-11ea-9f3e-7ffbc57c6cca.png)

**Comment by FAtherden-eLife** [comment]
The 'Here' text is linked to examples. I will also add images, since it seems that's unclear.

**Comment by JGilbert-eLife** [comment]
Ah, sorry! Yes, that's really obvious and I can only plead having a hard time distinguishing bold text in GitBook today.

I do think images would help, though, following the pattern elsewhere.

**Comment by FAtherden-eLife** [comment]
No problem - also agree that we should be consistent if that's what's been done elsewhere. I've added the images.

**Comment by naushinthomson** [comment]
Looks good to me!

**Comment by bcollins14** [comment]
Looks good to me also, thanks!
