### ISSUE TITLE
Update Data availability page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#152]
- [x] Add clarification on what to do about Github repos entered as generated datasets:

![Screenshot 2020-09-02 at 12 11 24](https://user-images.githubusercontent.com/40770049/91978617-55a58700-ed1c-11ea-834e-d7f47414b6cb.png)

(If the repo includes source data, this can stay in the generated datasets section. No need to add a software ref but code still needs to be forked if it is mentioned in the DAS?)

- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter if relevant

### Definition of done
- [x] Team reviewed and approved page?
- [ ] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by JGilbert-eLife** [comment]
@naushinthomson @bcollins14 @FAtherden-eLife @Melissa37 - I've added this section. Is what I have sufficient? I was a little unsure how much information was required for this. 

https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/data-availability#github-repositories-entered-as-datasets

**Comment by FAtherden-eLife** [comment]
Looks good to me. Do we need to check with Editorial in case the data could be more appropriately placed elsewhere (and this was missed during Editorial QA)? Or do we just proceed?

**Comment by JGilbert-eLife** [comment]
I'm not sure about that. I don't think we've ever recommended the authors move their data, but then most of the examples I can recall had both code and data.

**Comment by naushinthomson** [comment]
>If it is clear from the entered details or the repository page that data is present, it is acceptable to retain the dataset entry.

Would we then also fork the repository? I think that was my main reason behind adding this update because I wasn't sure.

**Comment by naushinthomson** [comment]
Otherwise, all good from me!

**Comment by bcollins14** [comment]
All good from me too, thanks!

**Comment by JGilbert-eLife** [comment]
I think this was actually completed but I didn't sign off on it. I will update the text once everything is OKed for code archiving with Exeter, then share it with them explicitly.

**Comment by JGilbert-eLife** [comment]
I've just shared this with Exeter.
