### ISSUE TITLE
Create eToc page

### ISSUE THREAD

**Issue by FAtherden-eLife** [elifesciences/schematron-gitbook#154]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Review house style document to ensure all requirements are covered
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter and invite feedback

### Definition of done
- [x] Page revised after team comments
- [x] Team reviewed and approved page?

**Comment by FAtherden-eLife** [comment]
@naushinthomson, @bcollins14, @JGilbert-eLife, @Melissa37 

Please review the eToc page here - https://app.gitbook.com/@elifesciences/s/productionhowto/pages-in-progress/etoc. Again I'm not sure where this should be placed in the sidebar. Perhaps under tools like we did with the ERA page?

**Comment by FAtherden-eLife** [comment]
FYI it's a short page, should only take 5 minutes to review.

**Comment by Melissa37** [comment]
Looks good to me - took 1 min to review!!

Only comment - Will in marketing team; could you add his surname too as if you've never emailed someone before you need to know that!

**Comment by naushinthomson** [comment]
Just one comment - is it worth spelling out what eToc means?

**Comment by JGilbert-eLife** [comment]
Suggest a minor edit: "Twice a week an email is sent out to subscribers **listing** all the articles eLife has published in a certain time period."
