### ISSUE TITLE
Update eLife website and communication house style page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#155]
- [x] Remove 'Note: Research Article titles – colons are discouraged except in tools and resources.' from Colon section.
- [x] Add changelog to page

**Comment by Melissa37** [comment]
Hi @naushinthomson there is no change history added with this update? Can you do that?

Thanks!

**Comment by Melissa37** [comment]
![Screenshot 2020-09-14 at 16 09 38](https://user-images.githubusercontent.com/6051876/93103582-bb8ef880-f6a4-11ea-8b43-711f3ff9fa14.png)

Hi there @naushinthomson it's missing this bit from the top 

For pages with a changelog, include 'Updated dd/mm/yyyy'

Thanks! That\'s from the template page :-)

**Comment by naushinthomson** [comment]
Ah sorry! Done now
