### ISSUE TITLE
Update Article structure page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#158]
- [x] Add guidance about Medicine article structure
- [x] Add guidance about what to do with 'list of abbreviations' sections (define each abbreviation in each first instance it is used in the main text and in display objects (such as each figure caption, table caption etc.) and remove such sections.
![image](https://user-images.githubusercontent.com/40770049/94130096-1dddbb00-fe54-11ea-85b6-c4988f777c6b.png)

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page

**Comment by griffithsc** [comment]
This looks good to me @naushinthomson  - thanks for this!
