### ISSUE TITLE
Update forking/archiving page

### ISSUE THREAD

**Issue by FAtherden-eLife** [elifesciences/schematron-gitbook#159]
- [x] Add updates to page
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [ ] Team reviewed and approved page?
- [ ] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by FAtherden-eLife** [comment]
@Melissa37, @JGilbert-eLife, @naushinthomson, @bcollins14 updated archiving (Software Heritage) protocols are here - https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/toolkit/archiving-code. Please review.

This page would replace When and how to fork repositories.

I imagine we'll want to add examples of a Software Heritage reference to the software references page, but I haven't done that yet.
@eLifeProduction

**Comment by Melissa37** [comment]
>As it is not possible to fork this, the following query needs to be left:
We see that you have included a custom script hosted on a lab website. In the interests of transparency and reproducibility, please upload this to a dedicated software repository (such as GitHub, GitLab etc.) and ensure that the software is licensed with an open source license [https://opensource.org/licenses]. We can provide guidance for you if required. Once your code has been licensed, we will fork it to our own GitHub repository for archiving purposes.
If the link to the code is not to a GitHub/GitLab/SourceForge/Bitbucket repository, and instead to a lab/institution website (which will usually have the lab's name in the title of the website or on the page), the above query should be added.

Need to update the AQ "we will fork it to our own GitHub repository for archiving purposes" to SH.

Also, do they need to put it in GitHub - could they go straight to SH?

**Comment by Melissa37** [comment]
>A software reference also needs to be added in the main article (see here for how to do this) - this should only be done after the code has been archived. Please note software citations can't be added in the data availability statement.

I think the Software references page needs to be updated to allow for Software Heritage - that is preferable to GitHub as the bibliographic data

**Comment by Melissa37** [comment]
Thanks! This is cool :-)

**Comment by FAtherden-eLife** [comment]
> Need to update the AQ "we will fork it to our own GitHub repository for archiving purposes" to SH.

Whoops! Done

**Comment by FAtherden-eLife** [comment]
> Also, do they need to put it in GitHub - could they go straight to SH?

Not currently unfortunately. We would need to build something which can generate [the required metadata](https://docs.softwareheritage.org/devel/swh-deposit/metadata.html) and post the files via API for the deposit.

**Comment by naushinthomson** [comment]
I think this looks good to me! Just one note - I think all hyperlinks to other pages etc. need to be bolded. Other than that, nothing else from me :)

**Comment by JGilbert-eLife** [comment]
For the section 'If the code is not in GitHub or GitLab', do we have examples of non-git repos that can be given in the relevant paragraphs?

**Comment by JGilbert-eLife** [comment]
Is it worth making explicit that we can't have embedded hyperlinks in the DAS?

**Comment by JGilbert-eLife** [comment]
And just because I've seen this happen - Add an author query should not apply post-author!

**Comment by JGilbert-eLife** [comment]
Otherwise, this look absolutely lovely and I cannot wait to be doing this rather than all that tedious messing around in GitHub!

**Comment by FAtherden-eLife** [comment]
> For the section 'If the code is not in GitHub or GitLab', do we have examples of non-git repos that can be given in the relevant paragraphs?

'fraid not, I couldn't find any from the archive to use as an example.

**Comment by FAtherden-eLife** [comment]
> Is it worth making explicit that we can't have embedded hyperlinks in the DAS?

Ah good, point that'll scupper this instruction:
> If a link to a repository is included the data availability statement, always add the text 'copy archived at XXXXXX', replacing 'XXXXXX' with the SWHID containing the embedded hyperlink.

I'll update it. 

I've also raised a [GitLab ticket](https://gitlab.com/ExeterPremedia/reqs/cust/elife-kriyadocs/-/issues/51) for this for Kriya 2.

**Comment by bcollins14** [comment]
"The time this process takes is dependent on the contents of the repo, but on average for new repos it may take around 2 hours." 

How will we know this has been completed? Or does this not matter?

**Comment by bcollins14** [comment]
Otherwise, looks great. Thanks!
