### ISSUE TITLE
Create Name change policy page

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/schematron-gitbook#160]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [ ] Share page with Exeter and invite feedback

### Definition of done
- [x] Page revised after team comments
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
First draft is up here - https://app.gitbook.com/@elifesciences/s/productionhowto/pages-in-progress/name-change-requests

Does that all make sense so far? There's more stuff to come, such as updating blogposts and what happens with confirming the changes have been made, but any comments welcome!

Thanks!

**Comment by FAtherden-eLife** [comment]
Is it worth making it _really_ explicit that when creating a zip, the items (and not the folder) needs to be be compressed - this is a relatively common mistake.

**Comment by FAtherden-eLife** [comment]
So we are definitely updating the PDF of every version, not just the latest version? (the latter would remove the need for the actions described in 'Updating old versions in the archive').

And this is also the case if a reviewer, BRE or SE had a name change (possibly hundreds of versions needing manual correction for one name change)?

**Comment by FAtherden-eLife** [comment]
That's it from me - thanks for all your efforts here.

**Comment by naushinthomson** [comment]
>eLife aims to allow authors, reviewers and editors to update their names with a minimum of hassle.

Should this be:
>'eLife aims to allow authors, reviewers and editors to update their names with **minimum hassle**.'?

**Comment by naushinthomson** [comment]
I think all good from me other than that! Thanks!

**Comment by Melissa37** [comment]
>Any related content such as Insights, Corrections or co-submissions

What exactly does this involve? If we're talking about updating the reference list in co-submissions and Insights I would vote this is a step too far. No other reference lists in the literature are going to be changed, as long as any future citations do get updated because we update the article and data sent to eg Crossref I'd say this should be enough.

I agree we should update correction metadata if there is a correction on an article this person is an author on

**Comment by Melissa37** [comment]
>Article metadata:
author list or peer review details
author contributions
competing interests
funding table (should correct automatically)
funding statement
data statement

Again - is this not a reference? If the original reference on the database where this dataset is stored has not changed then we're going against what is an original piece of metadata.
If it has been changed, this is still a reference and I vote should not be changed.

**Comment by Melissa37** [comment]
>For Insight articles and co-submissions, the following will also need to be corrected where applicable:
key info box details for the related article (in Insights)
mentions of the first author(s) in the text (if applicable)
entry for related article in the reference list

I personally think this is a step too far for this policy.

**Comment by eLifeProduction** [comment]
> > n cases where the individual's pronouns have changed in addition to their name, the following sections should be checked and updated if necessary:
> > competing interests
> > funding statement
> > acknowledgments
> 
> I agree - but can we have a policy going forward that we stop using s/he and use they instead for everyone?

Just to jump on this - I think most of the time *we* do because our stuff (in insights etc) refers to groups. However, we can't just 'they' universally for more or less the same reason why you don't misgender someone. If there's a preferred pronoun, you should use that. 'They' is no more universal than the others, and I don't think it would make sense in the context of contributions or competing interests, which sometimes refer to one of the other authors instead/as well.

**Comment by JGilbert-eLife** [comment]
> > n cases where the individual's pronouns have changed in addition to their name, the following sections should be checked and updated if necessary:
> > competing interests
> > funding statement
> > acknowledgments
> 
> I agree - but can we have a policy going forward that we stop using s/he and use they instead for everyone?

Just to jump on this - I think most of the time *we* do because our stuff (in insights etc) refers to groups. However, we can't just 'they' universally for more or less the same reason why you don't misgender someone. If there's a preferred pronoun, you should use that. 'They' is no more universal than the others, and I don't think it would make sense in the context of contributions or competing interests, which sometimes refer to one of the other authors instead/as well.

**Comment by bcollins14** [comment]
I think everyone has covered everything. Thanks James :)

**Comment by FAtherden-eLife** [comment]
> Following an update to change an author, editor or reviewer's name, an annotation should be added to the latest version of the article to indicate that such a change has taken place.
>> This article has been updated in response to a name-change request.


I know it's implicit, but can we make it explicit that this is the annotation that should be used, and not some variant of it. 

Or perhaps even add something to make it clear that author who's name has been changed should **not** be mentioned in the annotation.

**Comment by JGilbert-eLife** [comment]
> > Article metadata:
> > author list or peer review details
> > author contributions
> > competing interests
> > funding table (should correct automatically)
> > funding statement
> > data statement
> 
> Again - is this not a reference? If the original reference on the database where this dataset is stored has not changed then we're going against what is an original piece of metadata.
> If it has been changed, this is still a reference and I vote should not be changed.

This isn't meant to refer to the datasets but the actual data availability statement, where the author(s) may be mentioned e.g. contact X to request access to the data.
