### ISSUE TITLE
Update RRID page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#161]
- [x] Add updates to page about using identifiers.org instead of scicrunch resolver (see [here](https://gitlab.com/ExeterPremedia/Customers/eLife-1.5/-/issues/464) for gitlab ticket)
- [ ] Fred approved page
- [ ] James approved page
- [ ] Naushin approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [ ] Team reviewed and approved page?
- [x] Add changelog to page
- [x] Assign Fred to update the Schematron if relevant

**Comment by FAtherden-eLife** [comment]
Please also add this new Schematron test `addgene-test`.

**Comment by Melissa37** [comment]
> @FAtherden-eLife I've updated the text and it looks like the identifiers.org url no longer needs the RRID/ anymore, eg: https://identifiers.org/RRID:AB_2178887
> 
> That means this warning needs updating (any maybe the test in the Schematron too)?
> 
> > Warning: 'XXXXXX' element contains what looks like XXXXXX unlinked RRID(s). These should always be linked using 'https://identifiers.org/RRID/RRID:'. Element begins with XXXXXX.
> 
> Can these be updated to remove the "(scicrunch)":
> 
> > Error: RRID (scicrunch) link should be preceded by 'RRID:' with no space but instead it is preceded by 'XXXXXX'.
> 
> > Warning: RRID (scicrunch) link should be preceded by 'RRID:' with no space but instead it is preceded by 'XXXXXX'.

Whoops, sorry, it should be: 'https://identifiers.org/RRID:

You Ok to update again.
