### ISSUE TITLE
Update homepage image page

### ISSUE THREAD

**Issue by bcollins14** [elifesciences/schematron-gitbook#165]
- [x] Add updates to page - image credit 
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page

**Comment by bcollins14** [comment]
@naushinthomson  @JGilbert-eLife @FAtherden-eLife @Melissa37 @griffithsc

I have made a small update to include the new image credit presentation 😄   I don't think it will need everyone to check it so if anyone has some free time, that would be great!

**Comment by FAtherden-eLife** [comment]
Looks good to me - thanks @bcollins14.
