### ISSUE TITLE
Update Name change page to account for old crossref peer review DOIs

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/schematron-gitbook#166]
- [x] Add updates to page
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by JGilbert-eLife** [comment]
https://app.gitbook.com/@elifesciences/s/productionhowto/toolkit/name-change-requests#updating-old-decision-response-sub-dois

@Melissa37 @naushinthomson @FAtherden-eLife @bcollins14 - here's the addition to the Name Change page to account for old D/R sub-DOIs.

Let me know if you're happy with this!

Thanks,

James

**Comment by FAtherden-eLife** [comment]
Thanks @JGilbert-eLife. Looks good - just one question:
When searching crossref:
> Enter the date this email was received into the search function in CrossRef. This will return all the CrossRef submissions for that day.

If the email has been found in the inbox, could we not simply use the submission ID when searching to bring up the correct one? In the screenshot example `1458120946`?

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife Because muggins here completely zoomed past that option like a dingbat >_<

I will simply the instructions accordingly ASAP!

**Comment by JGilbert-eLife** [comment]
OK - that's fixed and I shall now curl up in a corner from embarrassment.

**Comment by naushinthomson** [comment]
Sorry I haven't been able to feed back on this one - should be able to do so today or tomorrow once the name change I'm working on is finished!

**Comment by Melissa37** [comment]
@JGilbert-eLife I don't know what's changed and it does not have a change log - can you add that, or did you not do that as we're still in the 'figuring it out' stage?

If not adding that - can you identify the para(s) that changed?

Thanks!
M

**Comment by naushinthomson** [comment]
@JGilbert-eLife Okay, having done the whole thing including updating crossref, it was pretty straightforward! Might be useful to clarify though that when looking for the crossref email with the peer review materials, if you've already sent off the silent correction you should not use the most recent email (as that will have the new style DOI). Also it may be useful to have an instruction about how to update PubMed just in case, I don't think we need screenshots but just a sentence might be useful! Otherwise, it all went smoothly, thank you for the comprehensive instructions!

**Comment by bcollins14** [comment]
@JGilbert-eLife I'm not sure if this is an issue but a question I thought of none the less. What if the article is older than the emails we have in the inbox? Would we be able to find the submission ID if the email had been deleted during a google memory limit purge? 

Otherwise, all looks good 👍

**Comment by JGilbert-eLife** [comment]
@naushinthomson - Thanks! I've clarified that the email will have been received in November 2019, since that's when we bulk-delivered all the peer review materials for older articles. I also linked to the data management centre for PubMed - we'll need to cover that more fully on the new version page.

@bcollins14 - It's a good point. We won't have to worry about that for a year or so, but I think going forward I'm going to stop deleting CrossRef emails. They're small so that shouldn't be a problem (and I primarily go after emails with attachments anyway!)

**Comment by naushinthomson** [comment]
@JGilbert-eLife Sorry, one more thing: can we indicate specifically that PDFs need to be downloaded from the bucket and sent to Exeter when asking them to update old versions because they don't have access to anything but the latest version?
