### ISSUE TITLE
Update Journal references page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#169]
- [x] Update page to add information about manuscripts in prep in main body of gitbook page (instead of just in the schematron errors section)
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter if relevant

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page
- [x] Assign Fred to update the Schematron if relevant

**Comment by bcollins14** [comment]
@Melissa37 @JGilbert-eLife @naushinthomson @FAtherden-eLife @griffithsc

I have added a small section on articles in preparation. If I need to add more, please let me know 😄  [https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/references/journal-references#articles-in-preparation](url)

We will also need to update the above templates to include Claudia's approval if that has not already been done.

**Comment by FAtherden-eLife** [comment]
> In the reference list, an author may use different terms to 'in press' (e.g. 'manuscript in preparation', 'in production', 'under review' etc).

Can we make this clearer please? i.e. the 'in preparation' etc. text would be in the main text not in the reference itself.

It may also be worth avoiding the comparison to 'in press' in this sentence because the way it reads to me sort of suggests that they're alternative phrases for the same thing which isn't the case.

Also is it worth including that the authors are free to add as much information as they want? It doesn't _have_ to just be 'Smith et al., in preparation'. For example they can add the title in the text, where it's been submitted etc. if they wish to.

**Comment by naushinthomson** [comment]
I don't have anything to add, looks good! :D

**Comment by JGilbert-eLife** [comment]
This does look good and - to contradict Fred - we do find these in the reference list as well as the main text, often without a date. It's probably worth mentioning that they can show up in both places?

However, this is broader than just journal articles, unfortunately - we can get these for books as well. I wonder if we need to put this at the level of the 'References' page? Or would it be better just to treat it indivdually on the two reference type pages?

We should also consider if/how we identify instances of this that are just provided in the text, and that 'submitted' can be an alternative to in preparation if it's that far along in the process (this is at the author's discretion, obviously!).

**Comment by Melissa37** [comment]
I think we should add something to the AQ and text about preprints! eLife is promoting preprints like mad and it is our mission. So if the article is posted as a preprint that should be the reference rather than in press to a journal article that does not have a PID yet.

Cat amongst the pigeons?!

**Comment by griffithsc** [comment]
Thanks Becky - this looks great! I would perhaps second Fred's 2nd comment about making the first sentence a bit clearer though?
