### ISSUE TITLE
Create Keywords and research organisms page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#17]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [ ] Fred approved page
- [ ] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by FAtherden-eLife** [comment]
@bcollins14, please can you add in the distinction between author keywords and research organisms?

**Comment by FAtherden-eLife** [comment]
I have added the [list of research organisms](https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/keywords#list-of-allowed-research-organism) in eJP. Am I correct in thinking this list is set - and we should be validating that the res org keyword is one of these (error if not)?

**Comment by FAtherden-eLife** [comment]
@Melissa37, @JGilbert-eLife, @naushinthomson, this page is now ready for review - https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/keywords. 

I _think_ we still need a section on Research Organisms here (If you agree, I'll leave that to Becky when she's back). I've added a section purely containing the list of res orgs from eJP, and all the Schematron tests.

Any thoughts on [my question above](https://github.com/elifesciences/schematron-gitbook/issues/17#issuecomment-702126386) as well?

**Comment by Melissa37** [comment]
>Despite being such a small part of the submission, keywords can have a big impact on the number of people who can find the article once published and as a result, the higher amount of citations.

I don't necessarily agree with this, so I'd rather ditch this statement.

**Comment by Melissa37** [comment]
>Keywords are scientific terms

Suggest change to:

Keywords are one-word (or two) terms ...

**Comment by Melissa37** [comment]
>The words chosen should ideally be specific to the topic of the article, contain a mixture of words and phrases, and it is beneficial to include additional words that are not included in the title.  

NOT phrases!! We try to avoid these, they are not keywords and when authors provide them we should delete them :-)

**Comment by Melissa37** [comment]
>Keywords: Molecular Dynamics, Simulation, Statistics, Thermodynamics, Kinetics

These should be in lower case:

Keywords: molecular dynamics, simulation, statistics, thermodynamics, kinetics

**Comment by Melissa37** [comment]
>A maximum of 6 words 

Is this a maximum of 6 keywords? It could be read that one single keyword could be a phrase of maximum 6 words

**Comment by Melissa37** [comment]
>List of allowed Research organism

Please change R to r

**Comment by Melissa37** [comment]
>In italics if appropriate (e.g. E. coli)

Please also state that for species name the Genus should be reduced to first letter and full stop (eg _Escherichia coli_ should be _E. coli_ )

**Comment by Melissa37** [comment]
>What needs to be checked?

Also need something about abbreviations VS spelling things out.
Do we have a list of common terms that never need to be spelled out VS things that need defining?

**Comment by Melissa37** [comment]
>List of allowed Research organism

This is a preselected list allowed don EJP, but we do allow Authors to add their own in production

**Comment by Melissa37** [comment]
There is a general issue - we did a massive clean up of keywords back in 2015 and had a new house style of what should be checked and what was allowed/not allowed. I cannot find this recorded anywhere but have dug through my emails and found a bunch of work with Graham and I did. I've passed the emails to Fred.

@JGilbert-eLife can you find anything about this in document form or your memory. It was when it was you, me and Sam!

Hopefully we can use schematron to get consistency!

**Comment by JGilbert-eLife** [comment]
The limit on Keywords (e.g. 6) is an eJP thing, not a hard and fast rule. We have added more keywords at author request in the past.

**Comment by JGilbert-eLife** [comment]
Picky but shouldn't it be 'lower case' not 'sentence case', since the latter implies the first letter in the list should be a capital.

**Comment by JGilbert-eLife** [comment]
*Why* are we adding 'None' if there are no research organisms? I thought that didn't show up?

**Comment by JGilbert-eLife** [comment]
For kwd-group-title, is it worth making it explicit that the title should be boilerplate text in Kriya?

**Comment by JGilbert-eLife** [comment]
kwd-child-test - 'disallowed', not 'un-allowed'?

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife does auth-kwd-check check the reference list? I think I remember you telling me it did not, but if it does, that's relevant.

Additionally, does it cover the decision/response? I'm thinking that the reviewers may use a different capitalisation from the authors.

I find this rule a bit flaky, I have to say.

**Comment by JGilbert-eLife** [comment]
Does auth-kwd-check-4 account for scientific terms that contain brackets?

**Comment by JGilbert-eLife** [comment]
test-auth-kwd-group-presence-1 - should this state that it fires for a specific type of content? E.g. Corrections don't have keywords, so this shouldn't fire.

**Comment by JGilbert-eLife** [comment]
Other than that, looking good! Thanks!

**Comment by FAtherden-eLife** [comment]
> Why are we adding 'None' if there are no research organisms? I thought that didn't show up?

That text was added because of my (incorrect) assumption [above](https://github.com/elifesciences/schematron-gitbook/issues/17#issuecomment-702126386). I'll change it.

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife does auth-kwd-check check the reference list? I think I remember you telling me it did not, but if it does, that's relevant.

> Additionally, does it cover the decision/response? I'm thinking that the reviewers may use a different capitalisation from the authors.

> I find this rule a bit flaky, I have to say.

It ignores the ref list and any sub-articles - searches content in the body of the article and appendices. Sorry about the flakiness. If you can provide me with some examples I will endeavour to improve. 

Off the top of my head I imagine it could be related to the word appearing at the start of a sentence (and capitalised but not indicative of it always being capitalised) vs not.

**Comment by FAtherden-eLife** [comment]
> Does auth-kwd-check-4 account for scientific terms that contain brackets?

Not currently. I would guess they are few and far between, but if you have common examples @JGilbert-eLife, then I will ensure they are exempt. In the meantime I've updated the action to account for this.

**Comment by FAtherden-eLife** [comment]
> test-auth-kwd-group-presence-1 - should this state that it fires for a specific type of content? E.g. Corrections don't have keywords, so this shouldn't fire.

Already does:
> This will fire if more than 1 or no author keyword group element (`<kwd-group kwd-group-type="author-keywords">`) is present in any article which is not a correction or retraction notice...
