### ISSUE TITLE
Update DL/AR page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#180]
Covered [here](https://app.zenhub.com/workspaces/production-wiki-5f7f1ebb23e6bb0017ce997f/issues/elifesciences/schematron-gitbook/220)

**Comment by FAtherden-eLife** [comment]
@naushinthomson, there's already a [checklist on the DL/AR page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/decision-letters-and-author-responses#what-needs-to-be-checked). Should we just update that instead of creating a separate page?
