### ISSUE TITLE
Create PoA processes page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#188]
- [x] Create page 
- [x] Add description of what is being covered (including group authorship and structured abstracts)
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Review house style document to ensure all requirements are covered by GitBook
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page revised after team comments
- [x] Team reviewed and approved page?

**Comment by JGilbert-eLife** [comment]
OK! Finally done - the only question I have is, do you think we should link to the standard data availability page rather than the common changes google doc? That's my assumption but I wasn't sure if we wanted to retain the slab within Production only . . .

Otherwise, usual thing - does everything look OK?

**Comment by FAtherden-eLife** [comment]
> If an article is a Clinical trial, the abstract will be structured with headings and additional details at the end (Clinical trial info and funding). All of this must be retained for publication. Clinical trials will usually be indicated in a sticky note.

I think this info is slightly outdated. Might be worth mentioning that Medicine and E&GH articles commonly (although there are some exceptions) have structured abstracts, and removing the sentence about the sticky note?

**Comment by FAtherden-eLife** [comment]
> Once the system is updated, eLife Production should be alerted to the presence of the group author regardless as the details will need to be added to the XML while the article is in the elife-poa-packaging/outbox folder (see below)

The sentence before this mentioned group members. My understanding is that we don't add group author members at POA, because doing so would require manual intervention from us. Is it worth mentioning in the section about adding group authors to the XML that we do not need to add group author members?

**Comment by FAtherden-eLife** [comment]
> There are two options: CCBY 4.0 Creative Commons license and CC0 1.0 Public Domain Dedication. If any of the authors are affiliated with an American government organisation (e.g. the US Department of Energy or the National Institutes of Health), they MUST use the CC0 license.

What to do if the authors are affiliated with US Gov org, and they have selected CCBY?

**Comment by FAtherden-eLife** [comment]
> The chief visual **different** on first viewing the article is

typo

**Comment by FAtherden-eLife** [comment]
> it is possible that XML conversion errors may break certain characters or **introduced** bugs

typo

**Comment by FAtherden-eLife** [comment]
> Once any necessary edits have been made to the article files and metadata, go to the Tasks tab and select the ‘Resend PoA files’ button.

Suggest removing 'button'

**Comment by FAtherden-eLife** [comment]
I think it's probably worth mentioning somewhere in this page that Ed Office currently carry out these checks/steps (aside from the bits that we do ourselves).

**Comment by FAtherden-eLife** [comment]
Nice work James - nothing else to add from me.
