### ISSUE TITLE
Create Abstracts page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#20]
- [x] Create page 
- [x] Add description of what is being covered (including clinical trial info)
- [x] Add info about full submissions no longer having impact statements and new procedure (example 70394)
- [x] Include digests and impact statement info
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions
- [x] Add any new queries to author queries list

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by Melissa37** [comment]
Needs to include Clinical trial requirements and Medical abstracts being split into sections

**Comment by naushinthomson** [comment]
@JGilbert-eLife @FAtherden-eLife @griffithsc @Melissa37 This [page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement) is now ready to review I believe! Just a few notes: 

I think we need to discuss equations/math elements in abstracts in the production meeting (abstract-test-4).

I think I've provided all the required info about clinical trials that would be relevant to this page but let me know if more is needed!

**Comment by Melissa37** [comment]
>If the biological system (species names or broader taxonomic groups if appropriate) is not mentioned in the title, it must be included in the abstract.

I did not know this! Is there a schematron test for it? Otherwise, are the Exeter copy editors responsible for checking this?

**Comment by Melissa37** [comment]
>Subheadings are discouraged in abstracts, except for medical submissions

I thought there were not allowed instead of discouraged?

**Comment by Melissa37** [comment]
>For eLife articles, abstracts are usually 150-200 words (except medical submissions which can be around 250 words).

I thought there was a word limit and schematron warning if it went over?

**Comment by Melissa37** [comment]
>Subheadings are discouraged in abstracts, except for medical submissions. If an article has the major subject areas 'Medicine' or 'Epidemiology and Global Health' and a colon in the article title (e.g. 'Association of Toll-like receptor 7 variants with life-threatening COVID-19 disease in males: findings from a nested case-control study'), the abstract should be structured, and include the following subheadings: Background; Methods; Results; Conclusions; Funding; Clinical trial number (for submissions reporting results of a trial only). These headings should be tagged in the underlying XML using <sec> and <title> tags (not <bold> tags).

Does schematron pick this up or is it something we should all know?

**Comment by Melissa37** [comment]
>eLife digests explain the findings of eLife papers to a broader audience

Please add a statement to say not every article has one (it's not just the article typese excluded)

**Comment by Melissa37** [comment]
>Digests

Need to add something about not editing them in copy editing or production processes and any edits need to be run past features team

**Comment by Melissa37** [comment]
>Excepting their use in scientific terms (e.g. ratios 1:800), if a colon or semi-colon is present, the statement should be rephrased (unless the article is a Replication study, in which case the statement should begin 'Editors' summary:').

s there a schematron check for this?

**Comment by Melissa37** [comment]
>multiple sentences and  it is unclear

Double space between and and it

**Comment by Melissa37** [comment]
There is nothing about Feature content abstracts - is this covered on feature content page? Can you add a link

**Comment by Melissa37** [comment]
>Action: This needs to be discussed in production meeting - should display formulae be allowed in abstracts? Formulae are allowed in Continuum but converted to placeholder text in pubmed. Needs to be discussed in production meeting.

PubMed

It's not just PubMed, it's Crossref too and I suspect a lot of indexers. I suggest we keep this rule as complex equations are unlikely to be in an abstract?

**Comment by Melissa37** [comment]
>final-abstract-word-count-restriction
Action: This warning will fire at post-author stages if an abstract has more than 280 words. The production team will need to check with the editorial team about whether the authors need to be asked to edit the abstract to 280 words or fewer.

Add to end?

if it has not been checked earlier

**Comment by Melissa37** [comment]
>Action: This error will appear if the first section in a structured abstract is titled anything other than 'Background:'. Double-check that the original submission has a structured one and that there is indeed a section titled 'Background'. If so, the production vendors will need to correct the section title accordingly as here. If the abstract is not a structured abstract, it shouldn't have section titles at all. 

suggest changing to:

Action: This error will appear if the first section in a structured abstract is titled anything other than 'Background:'. Double-check that the original submission has a structured abstract and that there is indeed a section titled 'Background'. If so, the production vendors will need to correct the section title accordingly as here. If the abstract is not a structured abstract, it shouldn't have section titles at all. Check with editorial though in case it should have a structured abstract

**Comment by Melissa37** [comment]
>Warning: digest paragraph starts with a lowercase letter. Is that correct? Or has a paragraph been incorrect split into two?

Typo @FAtherden-eLife - incorrectly

**Comment by Melissa37** [comment]
>Action: This warning will appear if a paragraph in a digest section begins with a lowercase letter. Double-check whether this is due to a paragraph incorrectly being split into two, or due to a typo and correct accordingly. 

Needs a comma after two:
...this is due to a paragraph incorrectly being split into two, or due to a typo, and correct accordingly

**Comment by Melissa37** [comment]
>Action: XXXXXX will be the current impact statement. In replication studies, impact statements act as a summary of the editor’s assessment of how successful the work was in replicating the previous work. The text must begin 'Editors' summary: ' (see above). If this has been misspelled, please correct it. If this prefix is not present, please alert the Production team so that they can get the correct text from the Editorial team. The article should not go to the authors until this is resolved, but can be moved to waiting for assets. This is a warning at the pre-author stages. 

This seems a random addition: The article should not go to the authors until this is resolved, but can be moved to waiting for assets.

Who is responsible for keeping an eye on this being updated? Is it put on hold while waiting?

**Comment by Melissa37** [comment]
Nice work, thanks!
M

**Comment by griffithsc** [comment]
Abstracts allow readers to have a quick overview before reading the whole article. For eLife articles, abstracts are usually 150-200 words (except medical submissions which can be around 250 words).
- Could you put something in about needing to query editorial if it's over?

**Comment by griffithsc** [comment]
the abstract should be structured, and include the following subheadings: Background; Methods; Results; Conclusions; Funding; Clinical trial number (for submissions reporting results of a trial only). 
- Do they have to have all of these subheadings? (with the exception of the clinical trial number, can any of the other headings listed here be absent?)

**Comment by griffithsc** [comment]
An impact statement is a succinct summary of an article, intended for display on the contents views of the eLife website:
- Should this be 'content view' or 'in content view'?

**Comment by griffithsc** [comment]
This is great, thanks Naushin! :)

**Comment by FAtherden-eLife** [comment]
I know it's rampant pedantry but can we remove "In scientific articles," from this sentence?
> In scientific articles, an abstract provides a clear and concise summary of the work. 

They do the same in other types of articles, and not everything we publish is strictly 'scientific' (e.g. certain feature contributions or editorials on publishing).

**Comment by FAtherden-eLife** [comment]
> If an article has the major subject areas 'Medicine' or 'Epidemiology and Global Health' and a colon in the article title ..., the abstract should be structured

 I think this is out of date now. All Medicine and E&GH articles whose received date is after 2021-04-05 should have a structured abstract.

**Comment by FAtherden-eLife** [comment]
>> Excepting their use in scientific terms (e.g. ratios 1:800), if a colon or semi-colon is present, the statement should be rephrased (unless the article is a Replication study, in which case the statement should begin 'Editors' summary:').

> s there a schematron check for this?

custom-meta-test-8

**Comment by FAtherden-eLife** [comment]
>> If the biological system (species names or broader taxonomic groups if appropriate) is not mentioned in the title, it must be included in the abstract.

> I did not know this! Is there a schematron test for it? Otherwise, are the Exeter copy editors responsible for checking this?

Neither did I. There's no schematron check for it.

**Comment by JGilbert-eLife** [comment]
I think we need to include instructions on what to do with digest changes post-author review.

**Comment by FAtherden-eLife** [comment]
The `abstract-word-count-restriction` tests will not fire on structured abstracts btw. Not sure if we want to include that information.

**Comment by FAtherden-eLife** [comment]
Please can we include `medicine-abstract-conformance-2`?

**Comment by JGilbert-eLife** [comment]
abstract-test-6

What if the abstract begins with something like "Abstract thinking is an interesting aspect of human intelligence"? I think the action needs to be clear that we need to delete this if it's obvious it's meant to be the title.

**Comment by FAtherden-eLife** [comment]
insight-abstract-impact-test-1 and insight-abstract-impact-test-2

> The majority of Insight articles will have abstracts that match the impact statement.

I think that it's safe to say that all of them should have the same, except in very rare cases.

**Comment by FAtherden-eLife** [comment]
> test-no-digest

In the action text, it might be worth mentioning that it should be investigated which article the digest was intended for, if it wasn't sent for the correct one.

**Comment by JGilbert-eLife** [comment]
final-abstract-word-count-restriction

Please could we make it clear this can be ignored if the authors have already been queried and haven't been able to reduce the length, or if Editorial has approved the extended length?

**Comment by FAtherden-eLife** [comment]
insight-abstract-impact-test-1 and insight-abstract-impact-test-2 appear twice

**Comment by JGilbert-eLife** [comment]
clintrial-conformance-2 - clintrial-conformance-6

I think you need to change 'first' in each of the actions to second, third, fourth etc.

**Comment by FAtherden-eLife** [comment]
> This error will appear if a structured abstract has a <related-object> element (which contains a link to the clinicaltrials.gov record for a clinical trial) in a section other than 'Clinical trial number':

Suggest removing `clinicaltrials.gov` from this sentence, since it can be one of many different CT registries.

**Comment by FAtherden-eLife** [comment]
The text is wrong for `clintrial-related-object-5`. It's actually 
> `<name/>` must have an @document-id-type='clinical-trial-number'.

Please can you update that and the action?

**Comment by FAtherden-eLife** [comment]
> clintrial-related-object-7
> This error will appear for a structured abstract if the `<related-object>` element doesn't have an `xlink:href` with the clinical trial number for example: 

"... with a link to the clinical trial information at its registry ..."

**Comment by FAtherden-eLife** [comment]
> clintrial-related-object-11
> ... does not match any of the Crossref clinical trial registries.

"... does not match any of the subtitles of the **clinical trial registries permitted by eLife**."

**Comment by FAtherden-eLife** [comment]
There's a description of clinical trials in the [ethics page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/ethics). Is it worth linking to that page somewhere?

**Comment by FAtherden-eLife** [comment]
Please can we add `abstract-child-test-1` to this page?

**Comment by JGilbert-eLife** [comment]
Thanks @naushinthomson !

**Comment by FAtherden-eLife** [comment]
> An impact statement is a succinct summary of an article, intended for display on the contents views of the eLife website:

suggest:

> An impact statement is a succinct summary of an article, which displays in the table of contents on the eLife website and in the eTOC (the bi-weekly email sent to subscribers).

**Comment by FAtherden-eLife** [comment]
>> the abstract should be structured, and include the following subheadings: Background; Methods; Results; Conclusions; Funding; Clinical trial number (for submissions reporting results of a trial only).

> Do they have to have all of these subheadings? (with the exception of the clinical trial number, can any of the other headings listed here be absent?)

They all have to be present (with the exception of the optional clintrial number).

**Comment by naushinthomson** [comment]
> > For eLife articles, abstracts are usually 150-200 words (except medical submissions which can be around 250 words).
> 
> I thought there was a word limit and schematron warning if it went over?

Yep, the schematron warnings are [pre-abstract-word-count-restriction](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement#pre-abstract-word-count-restriction) and [final-abstract-word-count-restriction](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement#final-abstract-word-count-restriction)

**Comment by naushinthomson** [comment]
> > Subheadings are discouraged in abstracts, except for medical submissions. If an article has the major subject areas 'Medicine' or 'Epidemiology and Global Health' and a colon in the article title (e.g. 'Association of Toll-like receptor 7 variants with life-threatening COVID-19 disease in males: findings from a nested case-control study'), the abstract should be structured, and include the following subheadings: Background; Methods; Results; Conclusions; Funding; Clinical trial number (for submissions reporting results of a trial only). These headings should be tagged in the underlying XML using  and <title> tags (not  tags).
> 
> Does schematron pick this up or is it something we should all know?
> 
> Is there any punctuation after the set texts?

There are a bunch of schematron tests for structured abstracts: abstract-test-5, abstract-test-7, medicine-abstract-conformance and all the clintrial-conformance tests. 
I've also updated the table in the [structured-abstracts](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement#structured-abstracts) to include the exact text we need :D

**Comment by naushinthomson** [comment]
> > If the biological system (species names or broader taxonomic groups if appropriate) is not mentioned in the title, it must be included in the abstract.
> 
> I did not know this! Is there a schematron test for it? Otherwise, are the Exeter copy editors responsible for checking this?

This was also taken from the author guide - @FAtherden-eLife is looking into whether we can add a schematron test for this.

**Comment by naushinthomson** [comment]
> > Digests
> 
> Need to add something about not editing them in copy editing or production processes and any edits need to be run past features team

I've added the following text:

>eLife digests explain the findings of eLife papers to a broader audience. They are managed by the Features team and written by editors and writers working together with authors. Digests should not be edited during any production processes - the wording of these is up to the Features team and any author edits to this section will need to be approved by them.

**Comment by naushinthomson** [comment]
> > Action: XXXXXX will be the current impact statement. In replication studies, impact statements act as a summary of the editor’s assessment of how successful the work was in replicating the previous work. The text must begin 'Editors' summary: ' (see above). If this has been misspelled, please correct it. If this prefix is not present, please alert the Production team so that they can get the correct text from the Editorial team. The article should not go to the authors until this is resolved, but can be moved to waiting for assets. This is a warning at the pre-author stages.
> 
> This seems a random addition: The article should not go to the authors until this is resolved, but can be moved to waiting for assets.
> 
> Who is responsible for keeping an eye on this being updated? Is it put on hold while waiting?

I'm not sure - all the impact statement text/schematron messages about this were done by James and I just merged them into this page. Any idea @JGilbert-eLife?

**Comment by naushinthomson** [comment]
> Abstracts allow readers to have a quick overview before reading the whole article. For eLife articles, abstracts are usually 150-200 words (except medical submissions which can be around 250 words).
> 
> * Could you put something in about needing to query editorial if it's over?

There are schematron warnings about this: [pre-abstract-word-count-restriction](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement#pre-abstract-word-count-restriction) and [final-abstract-word-count-restriction](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement#final-abstract-word-count-restriction)

Should I refer to these at the beginning as well?

**Comment by naushinthomson** [comment]
> * Do they have to have all of these subheadings? (with the exception of the clinical trial number, can any of the other headings listed here be absent?)

Yep - I've edited the text as follows: 

>Structured abstracts should have all the following subheadings: Background; Methods; Results; Conclusions; Funding; Clinical trial number (for submissions reporting results of a trial only).

Schematron messages will also appear if any of them are missing!

**Comment by naushinthomson** [comment]
> abstract-test-6
> 
> What if the abstract begins with something like "Abstract thinking is an interesting aspect of human intelligence"? I think the action needs to be clear that we need to delete this if it's obvious it's meant to be the title.

I've updated the action to: 
>If an abstract begins with the text 'abstract', and this is not part of the first sentence (e.g. 'Abstract thinking is an interesting aspect of human intelligence') this text should be deleted. 

That ok?

**Comment by naushinthomson** [comment]
> Please can we add `abstract-child-test-1` to this page?

I've added this [here](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/article-structure/abstract-digest-impact-statement#abstract-child-test-1). Is the text ok?

**Comment by JGilbert-eLife** [comment]
> eLife digests explain the findings of eLife papers to a broader audience. They are managed by the Features team and written by editors and writers working together with authors. Digests should not be edited during any production processes - the wording of these is up to the Features team and any author edits to this section will need to be approved by them.

I think this is a bit misleading because 'production processes' covers author review too. Maybe we should say, "Digests should not be edited by copyeditors or production staff, and any author edits to this section will need to be approved by the Features team." ?

**Comment by JGilbert-eLife** [comment]
> > This seems a random addition: The article should not go to the authors until this is resolved, but can be moved to waiting for assets.
> > Who is responsible for keeping an eye on this being updated? Is it put on hold while waiting?
> 
> I'm not sure - all the impact statement text/schematron messages about this were done by James and I just merged them into this page. Any idea @JGilbert-eLife?

Hmm. This was written before we abolished pub check again, I think. We should probably revise it to say that Exeter should hold the article until the correct Impact Statement is added in. Though it's not going to happen very often if at all since the reproducibility project is over for now.

**Comment by FAtherden-eLife** [comment]
There's not a warning specific to inline-formula, but there is one specific for maths (which would cover both types of formula), **[math-test-18](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/maths#math-test-18)**. 

So in the case where a display formula was in an abstract, there would be an error (as discussed), and the above warning. 
In the case where an inline-formula was present, the above warning would fire (provided it contained maths, if it didn't contain maths, then a separate error would fire stating that inline-formula must contain maths).

Let me know if you need anything further from me to update the page.
