### ISSUE TITLE
Fix formatting of Slab pages

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#201]
Make sure all imported pages match the template/are consistent as far as possible. For larger pages, split into series and link. Once you're finished, please verify the page on Slab so we know which pages have been checked.

**Naushin**
- [x] Figures (1.5)
- [x] Abstracts, digests and impact statements (0.1)
- [x] Code Blocks (0.1)
- [x] Country names (0.1)
- [x] Decision Letters And Author Responses (0.4)
- [x] Ethics (0.1)
- [x] Funding Information (0.1)
- [x] Licensing and copyright (1)
- [x] Tables (0.4)
- [x] RRIDs (0.1)
- [x] Archiving code (0.2)
- [x] Glencoe (0.1)
- [x] Asset citations (0.1)
- [x] Keywords (0.1)
- [x] Preprint references (0.1)
- [x] Thesis references (0.1)
- [x] Report references (0.1)
- [x] Reference citations (0.1)

**Claudia** 
- [x] Book references
- [x] Conference references
- [x] Data references
- [x] Journal references (also add info about journal-bracket-check and article-title-case messages)
- [x] Software references
- [x] Press processes

**James**
- [x] Data availability
- [x] Article assets
- [x] Maths
- [x] Additional files
- [x] Content processing
- [x] References

**Comment by FAtherden-eLife** [comment]
Here are the pages that I've fixed today:
- downstream deliveries
- code blocks
- ethics
- feature content
- funding
- archiving code
- Asset Citations
