### ISSUE TITLE
Create Asset citations page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#27]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by naushinthomson** [comment]
@JGilbert-eLife @bcollins14 @FAtherden-eLife @Melissa37 This is now [ready to review](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/allowed-assets/asset-citations)! Just a few things: 

Should the following tests be added here or covered in other pages? 
supplementalfigure-presence
supplementalfile-presence
supplementaryfigure-presence
supplement-table-presence
xref-target-conformance
empty-xref-test
semi-colon-xref-test

Are there cases where vid-xref-test-10 can be ignored?

Are there cases where supp-file-xref-conformity-1 can be ignored?

@FAtherden-eLife The message for vid-xref-conformity-2 has a typo (matches needs to be changed to match)

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife The message for vid-xref-conformity-2 has a typo (matches needs to be changed to match)

Thanks - I will update when I add the links.

> Should the following tests be added here or covered in other pages?

In my view, these should all be in this page.

> Are there cases where vid-xref-test-10 can be ignored?

I left it as a warning for 2 reasons:
- In case there was any other use of `cf.` in scientific writing that I was unaware of, that mean something other than confer.
- In case authors strongly objected for some reason and we felt lenient. 

To be honest, simply removing it as the message suggests may make the sentence grammatically incorrect, so it would probably need replacing with another word, rather than removing. Happy to upgrade to an error if deemed appropriate and take suggestions on what the message should say.

> Are there cases where supp-file-xref-conformity-1 can be ignored?

Yes, if it was marked up this way `Source data <xref ref-type="supplementary-material" rid="sdata1">1</xref>-<xref ref-type="supplementary-material" rid="sdata3">3</xref>` it would fire for the second link, even though that's perfectly fine capture. In that case, it could be ignored.

**Comment by FAtherden-eLife** [comment]
> Figure citation is in a reference to a figure from a different paper, and therefore must be unlinked.

urgh :man_facepalming: another typo from me 

I will change to:
> Figure citation refers to a figure from a different paper, and therefore must be unlinked.

**Comment by FAtherden-eLife** [comment]
> **supp-file-xref-conformity-3**
> Action: This will fire if a citation of supplementary material points to a 'supp' type asset but the citation text doesn't include the string 'supplementary file', for example, if the citation text is 'Source data 1' but points to 'Supplementary file 1'. Check the original submission to clarify whether the citation should be to source data or the supplementary file - try deleting and re-adding the correct citation but if this doesn't work, Exeter will need to update. 

In most cases when I've seen this, `Supplementary` has just been misspelled and needs correcting. Is it worth adding that to the action?

**Comment by FAtherden-eLife** [comment]
Do equation citations need adding to this page, or will that be covered elsewhere?

**Comment by FAtherden-eLife** [comment]
Is it worth including `xref-parent-test` and `xref-child-test` as structure tests here? Not sure what other page would be better suited for them.

**Comment by JGilbert-eLife** [comment]
"Clicking them in the PDF will take the reader to the relevant asset in the PDF and HTML view."

This isn't quite right as stated. Citations in the PDF will scroll the page to where the cited asset appears, not take the reader to the HTML view. Maybe just the first 'in the PDF' needs to be deleted?

**Comment by JGilbert-eLife** [comment]
For completeness, would it be possible to include more examples for "Asset citations may appear inside or outside brackets."? I think we should give cases of citations being included as part of sentences at least.

**Comment by JGilbert-eLife** [comment]
Likewise it's probably useful to include live examples of the part labelling, showing multiple part ranges, sub-parts e.g. Figure 2Bii etc.

**Comment by JGilbert-eLife** [comment]
"Sometimes, authors will use 'Fig' or 'Supp file'  . . ." We should probably say that this should be caught and the citations corrected to our style during pre-editing, so anything left over is a mistake.

**Comment by JGilbert-eLife** [comment]
Should we not be moving the stuff about figure and table citations (more detail that is) to here and genericising it? The rules are on this page, so surely the description about placement, citations to other articles (which covers all kinds of assets, not just figures) and so on should go here rather than on the asset-specific pages?

**Comment by JGilbert-eLife** [comment]
Would the -target tests not fall under structure rather than content?

**Comment by JGilbert-eLife** [comment]
"Exeter will need to correct the link in either case." - how? Should it be support? Except we'd only need that if we couldn't replace the citation with a correct one.

**Comment by JGilbert-eLife** [comment]
supplementary-material-xref-target-test

"If the link it meant . . ." should be "If the link is meant . . ." I think.

**Comment by JGilbert-eLife** [comment]
There is some context missing from other-xref-target-test to explain what 'award group' has to do with it.

**Comment by JGilbert-eLife** [comment]
fig-xref-conformity-3

"Check the citation links to the correct figure" - I think we need more guidance here on how to do this. This might be a result of incorrectly implement edits, for example, or a misprocessing of the original file.

**Comment by JGilbert-eLife** [comment]
fig-xref-conformity-5

It is not clear that this is talking about citations whose text just reads e.g. '3'. It needs to be clearly indicated that the tagging puts the citation link to e.g. Figure 1—figure supplement 3 on the '3' at the end of 'Figure 1—figure supplements 2,3'.

**Comment by JGilbert-eLife** [comment]
fig-xref-test-3

This sometimes fires when part labels (or more likely, sub-part labels) haven't been captured as part of the citation link. I think it would be worth mentioning that.

**Comment by JGilbert-eLife** [comment]
fig-xref-test-10

It might be worth providing alternate version so '—figure supplement' as I believe (@FAtherden-eLife ?) this warning looks for 'figure supplement' and would capture e.g. Figure 1 figure supplement 2.

**Comment by JGilbert-eLife** [comment]
fig-xref-test-14

General point: why don't we like c.f.? It has a specific use and dropping it would seem to alter the meaning of the text.

**Comment by FAtherden-eLife** [comment]
> It might be worth providing alternate versions to '—figure supplement' etc as I believe (@FAtherden-eLife ?) these warnings look for e.g. 'figure supplement' and would capture Figure 1 figure supplement 2, Figure 1, figure supplement 2 etc.

Yup - it'll catch those cases too.

**Comment by FAtherden-eLife** [comment]
> General point: why don't we like c.f.? It has a specific use and dropping it would seem to alter the meaning of the text.

I think I mist have seen it in a house style document somewhere. Not sure of that document still exists. I'll see if I can find evidence for it.

**Comment by JGilbert-eLife** [comment]
supplementary-material-xref-target-test

Again, does this count as structural?

**Comment by JGilbert-eLife** [comment]
Thanks @naushinthomson! I think the only other thing I'd say is that we should have XML examples for various assets at the end, just for continuity with the other pages and make it easy for people to pull those up.

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife a typo: "which in turns"

Thanks - I'll fix.

**Comment by bcollins14** [comment]
>  If figures or tables are cited out of order, queries should be left for the authors. 

Should this be changed to '..of order, this should be queried with the authors.' or to that effect so this applies to both pre and post author?

**Comment by Melissa37** [comment]
>Where multiple assets are cited in one set of brackets, each citation should be separated from the next by a comma or semi-colon followed by a space (depending on context and what the author has provided). 

Is this something we insist on? Is it possible for there to be a long list, or eg Table 1-5.

**Comment by Melissa37** [comment]
>Supplementary files with parts should have those parts included in the link text. In the example below, 'table 1' should be included in the citation link.

A it should be an em-dash and not a hyphen and B I did not realise we had this rule :-) Is it that important?

**Comment by Melissa37** [comment]
At the top of the schematron checks is it worth listing out the different xref "codes" for each asset? And the required structure for them?

**Comment by Melissa37** [comment]
> Error: xref with @ref-type='XXXXXX' points to XXXXXX. This is not correct.
Action: This means that the ref-type attribute on the xref is not correct with respect to what the link points to. If it is meant to point to an award group, then the ref-type attribute value must be 'other'. If the link it meant to point to something else, which is not an award group, then the link points to the incorrect location and will need to be updated. Exeter will need to correct the link in either case.

This feels like it is ot an asset citation schematron message but related to Funding?

**Comment by Melissa37** [comment]
>This will also fire if the link text refers to part labels, for example 'Figure 4E2'. As long as the citation links to the correct figure (Figure 4 in this case), this warning can be ignored. 


Could you provide an example xml? I think I understand but it would be useful :-)

**Comment by Melissa37** [comment]
>```<xref ref-type="video" rid="video2">Video 1</xref>.</p>```

please remove the ```.</p>``` so it matches the other sample xmls

**Comment by Melissa37** [comment]
>Action: This warning will fire if there is no space between a figure citation and the text before it, for example 'SeeFigure 2.' Add a space between the citation and the preceding text. However, if the text is 'See Figures 2,3' this is ok to leave.

I wonder whether it's worth being explicit here and saying this will fire on the "Figure 3"  and it's OK for that citation?

**Comment by Melissa37** [comment]
>Action: This warning will fire if there is no space between a figure citation and the text after it, for example 'See Figure 2for.' Add a space between the citation and the following text.

Converse of above, this is not included as an example

**Comment by Melissa37** [comment]
>If the citation doesn't refer to a part label, again check if it refers to a figure from another paper - if so, change it to plain text. If the authors are simply referring to the figure in general, the citation can be left as is. If the figure has been incorrectly captured, for example, if the authors wrote 'Figure 1 - Supplemental Figure 4' and 'Figure 4' has been linked, this needs to be corrected (in this example, to Figure 1—figure supplement 4).

>If the authors are simply referring to the figure in general, the citation can be left as is.

I don't really understand this, have you got an example?

**Comment by Melissa37** [comment]
>Action: This warning will fire if there is no space between a video citation and the text before it, for example 'SeeVideo 2.' Add a space between the citation and the preceding text. However, if the text is 'See Videos 2,3' this is ok to leave.


Should this link to Video 2 and then then the number 3 link to video 3

**Comment by Melissa37** [comment]
>Action: This will fire if a video citation is followed by text which suggests it should be a link to a source data or code supplement - for example, if the linked citation text is 'Video 1' but it is followed by '—source code 1' or '—source data 1' in plain text. In this example, a citation to Video 1—source code 1 or Video 1—source data 1 should replace the citation for Video 1.

- for example should be changed to , for example,

**Comment by Melissa37** [comment]
>Action: This will fire if a video citation is preceded by text which suggests it should be a link to a figure level video- for example, if the linked citation text is 'Video 1' but it is preceded by 'Figure 1— '.


Same as above

**Comment by Melissa37** [comment]
>"Table 2 shows further analysis." The citation of 'Table 2' in this example can just be retained.

Should it not be deleted because if someone clicks on it it loops them to the table they are looking at?

**Comment by Melissa37** [comment]
>"Supplementary file 2 shows further analysis." The citation of 'Supplementary file 2' in this example can just be retained.

Same as above?

**Comment by Melissa37** [comment]
Nice job, thanks @naushinthomson !

**Comment by JGilbert-eLife** [comment]
@naushinthomson It's just occurred to me that we should ideally have a table or list indicating which assets require citation and which don't.

**Comment by bcollins14** [comment]
I think everyone has covered everything. Thanks Naushin!

**Comment by naushinthomson** [comment]
@FAtherden-eLife Schematron is ready to update for this page! :)

**Comment by FAtherden-eLife** [comment]
Thanks @naushin. Going through to add the links now and I wonder whether any of the following tests would be appropriate for this page:
- xref-ref-type-conformance
- disp-formula-xref-target-test
- table-fn-xref-target-test
- figurefigure-presence
