### ISSUE TITLE
Create Math elements/Equations page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#34]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [ ] Fred approved page
- [x] James approved page
- [ ] Naushin approved page
- [ ] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by Melissa37** [comment]
>authors can capture maths in varying ways - either as plain text, as MathML (by using an equation editor in Word or similar word processors), in LaTeX, or in other ways

or in other ways - is it worth being explicit at this point that if they capture it as an image it has to be sent back to them as we cannot work with flat math images?

**Comment by Melissa37** [comment]
>There are no errors in equations (which will be flagged by the Schematron).

I am unsure about this point - I would read no errors to be that they match the original submission from the author, but I don't think Schematron can do that? Can you articulate what errors schematron picks up?

**Comment by Melissa37** [comment]
>Equations can be captured in two ways, inline or as a display equation. Inline equations can only appear inline within the text, so as part of a paragraph, list item, or table cell. Display equations look distinct from the text, and in rare cases can be captured directly under a section, but in many cases they are captured in the same way as inline equations, but simply rendered with more prominence than inline equations.

Could you add a screenshot to show how they look distinct?

**Comment by Melissa37** [comment]
>with just unicode

is unicode the equivalent of "plain text", maybe add that in brackets for non-tech people :-)

**Comment by Melissa37** [comment]
>Equations appear in a different font to plain text in both the PDF and HTML (where MathJax is used to render the equations).

Could we add the name of the font - Stix?

**Comment by Melissa37** [comment]
>Here is an example of where changing equations to plain text is inappropriate:

Wow! What is the N in the math font?

**Comment by Melissa37** [comment]
>All other instances should be retained as equations, unless specified by eLife Production staff.


Should this be the author or production staff?

**Comment by Melissa37** [comment]
>For example, until recently PubMed were unable to render mathML in abstracts. As a result eLife currently replace any equation in an abstract with the text [Formula: see text] in the content that we send them.

Is it on Graham's to-do list to update what we send to PubMed?

**Comment by Melissa37** [comment]
OMG I LOVE the cheatsheets, thank you!!!!

**Comment by Melissa37** [comment]
>During pre-publication checks, special care should be given to equations by eLife production staff, to ensure that there is no discrepancy between the equations as they appear on Continuum and the equations as they appear in the PDF.


Could we add that we have an arrangement with Exeter - they are paid more for LaTex articles and expected to carefully check math at pre-editing?

**Comment by Melissa37** [comment]
>math-test-11
Warning: mml:math contains '○' (the white circle symbol). Should this be the degree symbol instead - '°', or '∘' (the ring operator symbol)?
Action: Check the context in which this symbol is used. If it follows numbers and/or is used in the context of discussing temperature, rotation or angles, then replace the inline equation with a plain text degree symbol. If it is definitely supposed to be a white circle symbol, then check how it's been used elsewhere - if the character is present in a display equation, then it will need to remain as an inline equation to keep the font consistent. The aim here is to remove unnecessary math markup, but not to the detriment of keeping fonts/meaning consistent in the article.

Is there a chance this could be used to demote something in a graphic and should be change to open white circle?

**Comment by Melissa37** [comment]
>math-test-15
Warning: mml:math seems to only contain the formula for a cation - 'XXXXXX' - which is likely unnecessary. Should this be captured as normal text instead?
Action: This warning will fire at all stages if there is an equation which only contains a cation, such as .

Would it be useful to help the user by defining what a cation is and looks like in text? 

a positively charged ion, i.e. one that would be attracted to the cathode in electrolysis.

**Comment by Melissa37** [comment]
>math-test-16
Warning: mml:math seems to only contain the formula for an anion - 'XXXXXX' - which is likely unnecessary. Should this be captured as normal text instead?
Action: This warning will fire at all stages if there is an equation which only contains an anion, such as .

Same as above?

**Comment by Melissa37** [comment]
>Warning: math (XXXXXX element) containing 'XXXXXX' has a color style which is not red, blue or purple - 'XXXXXX' - which is not allowed. If it is clear that colours are supposed to be used, but you are not sure which ones, then please query the authors - 'eLife only supports the following colours for text and maths - 'red', 'blue' and 'purple'. Please confirm how you would like the colour(s) here captured given this information.'.

US/UK spelling typo in the schematron message - color

**Comment by Melissa37** [comment]
>eLife do not permit this for text

Should be:
>eLife does not permit this for text

**Comment by Melissa37** [comment]
>Action: This warning will fire in cases where an equation contains what may be LaTeX markup, meaning tat the maths may not be processed correctly. 

typo tat -> that

**Comment by Melissa37** [comment]
>Action: This warning will fire at all stages for an inline formula which does not contain a table and is more than 90 characters long. Such length formulas will need to br wrapped over multiple lines in the HTML on the eLife website, which will affect the readability within the text. For example from

typo be -> be

**Comment by Melissa37** [comment]
>...equation from a different paper (for example Equation 1 from Smith et al. and there is also an equation 1 from the authors), then the label in the equation taken from the other paper can be removed, and ...

Should "then the label in the equation taken from the other paper can be removed" be changed to "then the **XML-tagged** label in the equation taken from the other paper can be removed"  to make it clear we're talking about XML tagging and not the actual content?

**Comment by FAtherden-eLife** [comment]
>> Equations appear in a different font to plain text in both the PDF and HTML (where MathJax is used to render the equations).

> Could we add the name of the font - Stix?

Actually looks like the font is the same in the HTML. Not sure what the font is in the PDF. Does anyone know? If not I can ask Exeter.

**Comment by FAtherden-eLife** [comment]
>>Here is an example of where changing equations to plain text is inappropriate:

>Wow! What is the N in the math font?

Sorry, I don't understand what you mean here.

**Comment by FAtherden-eLife** [comment]
>> All other instances should be retained as equations, unless specified by eLife Production staff.

> Should this be the author or production staff?

This is pre-author though.

**Comment by Melissa37** [comment]
>Actually looks like the font is the same in the HTML - I've updated. Not sure what the font is in the PDF. Does anyone know? If not I can ask Exeter.

It is called Stix

**Comment by Melissa37** [comment]
> @Melissa37 Sorry, I don't understand what you mean here.

Sorry,, maybe a show and tell onscreen would help!

**Comment by FAtherden-eLife** [comment]
>> Actually looks like the font is the same in the HTML - I've updated. Not sure what the font is in the PDF. Does anyone know? If not I can ask Exeter.

> It is called Stix

Ah OK - great thanks.

**Comment by FAtherden-eLife** [comment]
>> For example, until recently PubMed were unable to render mathML in abstracts. As a result eLife currently replace any equation in an abstract with the text [Formula: see text] in the content that we send them.

> Is it on Graham's to-do list to update what we send to PubMed?

I raised a ticket just now, but Graham pointed out we [discussed it previously and opted not to](https://github.com/elifesciences/elife-pubmed-feed/issues/75). Even though we're sticking with MathML for longer than anticipated back then, I'm inclined the same way (not to do it) because we have had so few abstracts (and not article titles) with equations in the past. Unless you disagree?

**Comment by JGilbert-eLife** [comment]
Might be worth stating in the opening para what display equations are?

**Comment by JGilbert-eLife** [comment]
I think it might be more appropriate to say:

"A large number of equations slow the load time of content in web pages. Therefore, certain maths elements (single operators [+, –, ±], numbers along, some individual characters/short equations) should be converted to plain text where possible. However, this should be done with caution, equations should not be changed to text at the expense of meaning. Equations appear in a different font (Stix) to plain text in the PDF. If a symbol is used in a display equation, and then referenced in a preceding or subsequent paragraph (typically defining or expounding what that symbol represents), the symbol in the paragraph should be tagged as an inline equation, so the fonts match and the reader can easily discern that it is the same symbol from the equation."

It's not really about 'unnecessary' equations and I think saying it is will cause confusion with Exeter.

**Comment by JGilbert-eLife** [comment]
"This means that the label numbering can being again in an appendix" should be "This means that the label numbering can begin again in an appendix"

**Comment by JGilbert-eLife** [comment]
Fonts - \mathcal also works, though renders the same as \mathscr on Continuum (it probably shouldn't as they are distinct fonts.

And by work, I apparently mean - renders OK in the PDF but not in the content view on Kriya 2.

<img width="142" alt="Screen Shot 2021-03-16 at 13 03 35" src="https://user-images.githubusercontent.com/1785305/111313462-494d9f80-8658-11eb-9422-0926e51ec1c5.png">

**Comment by JGilbert-eLife** [comment]
Equations on the eLife website - is it worth touching on the current shortcomings with regard to space for maths and the wrapping of equations?

**Comment by JGilbert-eLife** [comment]
For math-test-3 - is it worth including appropriately split maths? It's unlikely to be really required for this particular rule but should we cover it elsewhere in this page?

**Comment by JGilbert-eLife** [comment]
math-test-8 - ". . . then it can be deleted . . ." - shouldn't that be 'converted to plain text'? I don't think anything should be outright removed in response to this rule and we should avoid implying otherwise (just in case!).

**Comment by JGilbert-eLife** [comment]
math-test-15 - I'd suggest adding a couple more examples in the final para.

**Comment by JGilbert-eLife** [comment]
math-test-19 - what is this looking for? I've never seen it fire (even when it might have been useful for it to do so). That might be related to some spacing options working better than others.

**Comment by JGilbert-eLife** [comment]
final-mathbackground-test-2 - should be 'post-author', not 'pre-author'.

**Comment by JGilbert-eLife** [comment]
mtext-test-1 - is it possible to provide example of the strange notation that might fire this?

**Comment by JGilbert-eLife** [comment]
inline-formula-length-test-1 - is display equation language we expect authors to understand? I'm honestly unsure on this point!

**Comment by JGilbert-eLife** [comment]
disp-formula-test-3 - I think we had an example of an equation at the start of a section recently but I can't remember the number - might be worth pulling it out of the archive to illustrate this?

**Comment by JGilbert-eLife** [comment]
Thanks for this @FAtherden-eLife - this is great! I'm just testing whether Kriya 2 has the issue with 0 in maths not rendering/getting into the XML (so far so good); do you think it's worth covering that on this page in the meantime?

**Comment by FAtherden-eLife** [comment]
> I think it might be more appropriate to say:

> "A large number of equations slow the load time of content in web pages. Therefore, certain maths elements (single operators [+, –, ±], numbers alone, some individual characters) should be converted to plain text where possible. However, this should be done with caution, equations should not be changed to text at the expense of meaning. Equations appear in a different font (Stix) to plain text in the PDF. If a symbol is used in a display equation, and then referenced in a preceding or subsequent paragraph (typically defining or expounding what that symbol represents), the symbol in the paragraph should be tagged as an inline equation, so the fonts match and the reader can easily discern that it is the same symbol from the equation."

> It's not really about 'unnecessary' equations and I think saying it is will cause confusion with Exeter. We should probably also have an example of appropriate conversion to text (e.g. some numbers, symbols alone or p values)

Thanks. I have changed to:
> Equations slow the load time of content in web pages, and may not appear in downstream locations. Therefore, certain maths content (single operators [+, –, ±], numbers alone, some individual characters) should be converted to plain text where possible. However, this should be done with caution, equations should not be changed to text at the expense of meaning. Equations appear in a different font (Stix) to plain text in the PDF. If a symbol is used in a display equation, and then referenced in a preceding or subsequent paragraph (typically defining or expounding what that symbol represents), the symbol in the paragraph should be tagged as an inline equation, so that the fonts match, and the reader can easily discern that it is the same symbol from the equation.

**Comment by FAtherden-eLife** [comment]
> math-test-19 - what is this looking for? I've never seen it fire (even when it might have been useful for it to do so). That might be related to some spacing options working better than others.

@JGilbert-eLife It's looking for an empty `<mml:mi>` element which has a preceding `<mml:mi>` element containing letters and a following `<mml:mi>` element containing letters. I think sometimes Kriya outputs an empty `<mml:mi>` element instead of a `<mml:mspace>` (with the appropriate attributes) in certain conditions. 

If you (or anyone else) happens to recall or spot one of these not being flagged in the wild, then that will help me find the conditions I can test for - thanks!

**Comment by FAtherden-eLife** [comment]
> inline-formula-length-test-1 - is display equation language we expect authors to understand? I'm honestly unsure on this point!

Not sure. Suggestions on alternative text for the query are welcome.

**Comment by bcollins14** [comment]
Really helpful, thanks Fred 😄
