### ISSUE TITLE
Create RRIDs page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#35]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by naushinthomson** [comment]
@JGilbert-eLife @Melissa37 @bcollins14 @FAtherden-eLife 
I think this page is now complete and ready for review! https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/content/rrids

Just one point for @FAtherden-eLife:
the text of pre-rrid-spacing and final-rrid-spacing is currently 
>RRID (scicrunch) link should be preceding by 'RRID:' with no space but instead it is preceded by 'XXXXXX'. 

This should be changed to 
>RRID (scicrunch) link should be **preceded** by 'RRID:' with no space but instead it is preceded by 'XXXXXX'. 

I've updated this in the gitbook already but just so you know to change it in the schematron.

**Comment by Melissa37** [comment]
>Research Resource Identifiers (RRIDs) are persistent and unique identifiers for referencing a research resource (e.g. plasmids, antibodies, software). Identifiers are prefixed with 'RRID:', followed by a second tag that indicates the source authority that provided it (e.g. 'AB' for the Antibody Registry, 'CVCL' for the Cellosaurus, 'MMRRC' for Mutant Mouse Regional Resource Centers, 'SCR' for the SciCrunch registry of tools) and the ID itself. 

Are we treating Research Resource Identifiers as proper nouns or should we change to Research resource identifiers?

Suggest changing "followed by a second tag" to "followed by a second string"

Suggest changing "and the ID itself" to "and the unique identifier string itself"

**Comment by Melissa37** [comment]
>RRIDs are most commonly listed in the key resources table but can also appear in the main text of an article. They should be displayed in the format 'RRID:XXXXXX' where XXXXXX is the ID and there is no space between the colon and the ID.

Suggest changing "where XXXXXX is the ID" to "where XXXXXX is the unique RRID as described above"

**Comment by FAtherden-eLife** [comment]
The reason there is a pre and final version of the rrid-spacing test is that sometimes authors haven't included the identifier. So I think we need to add in an author query to the action if that's the case.

**Comment by bcollins14** [comment]
In your examples of RRIDs, would it be good to hyperlink these so the reader sees examples of pages it would link out to/how it should look in Kriya?

**Comment by bcollins14** [comment]
Otherwise, looks good to me. Thanks again 👍

**Comment by JGilbert-eLife** [comment]
"Identifiers are prefixed with 'RRID:'," - this isn't quite true. *We* ask authors to prefix them with RRID, but the ID itself is the numbers following the colon, e.g. AB_477593 in https://scicrunch.org/resolver/AB_477593

**Comment by JGilbert-eLife** [comment]
"To find the entry, search for the RRID using the SciCrunch resolver and use the resulting URL to add a hyperlink to the RRID." - is it worth giving the short-hand instruction of simply adding the ID string to https://scicrunch.org/resolver/?

**Comment by JGilbert-eLife** [comment]
Other than that, no additional comments from me. Thanks!

**Comment by naushinthomson** [comment]
> Are we treating Research Resource Identifiers as proper nouns or should we change to Research resource identifiers?

I was keeping it capitalised as that explains the acronym?
