### ISSUE TITLE
Create template page

### ISSUE THREAD

**Issue by eLifeProduction** [elifesciences/schematron-gitbook#4]
- [x] Create page 
- [x] Add template sections and text about what should go in each section
- [x] Add formatting guidance e.g. about Kriya queries
- [x] Melissa approval
- [x] Fred approval
- [x] James approval
- [x] Becky approval

**Comment by naushinthomson** [comment]
Here's the template for making new pages, let me know if there's anything I've missed! Otherwise just tick off your names when you approve it :)  https://app.gitbook.com/@elifesciences/s/schematron/untitled-4
@FAtherden-eLife @bcollins14 @JGilbert-eLife
