### ISSUE TITLE
Create Additional files page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#41]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
@bcollins14 @griffithsc  @FAtherden-eLife @Melissa37 @naushinthomson - Please could you take a look at the additional files page and let me know what you think? I think I've covered everything, but there might be stuff I need to expand or illustrate.

https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/allowed-assets/additional-files

Thanks!

**Comment by Melissa37** [comment]
>Asset- and article-level source files, supplementary files and other additional filess

Need to remove extra s :-)

**Comment by Melissa37** [comment]
Audio files

Are they explicitly not allowed as children of fig/table/video?
If not why? 
Might be worth explaining

**Comment by Melissa37** [comment]
>At present, eLife cannot support inline audio-only playback so audio files (as distinct from videos) should be included as additional files. These are treated in all respects like Supplementary files, but are labelled as as Audio file 1, Audio file 2, etc.

Need to remove second "as"

**Comment by Melissa37** [comment]
>Source data and source code may be provided to aloow readers access to the raw data and any scripts 

typo - allow

**Comment by Melissa37** [comment]
>Source files (asset-level

Missing end bracket

**Comment by Melissa37** [comment]
>The source data will usually consist of tables of raw data but may also include unprocessed images, editable version of charts provided as flat images, or multiple-page documents that cannot be typeset as single figures/figure supplements

Does "editable version of charts provided as flat images" refer to content provided as a figure? This could be clearer

**Comment by FAtherden-eLife** [comment]
Is it worth including an example of a suitable reporting standards file? In the past we've had files come through labelled as reporting standards, which actually didn't need to be included (validation report from data uploaded to a repo for example), so it would be good to cover that as well, if possible.

**Comment by FAtherden-eLife** [comment]
It's implied in the language (XXX should have a title/legend), but perhaps worth expanding that while it's highly preferred/recommended, we can publish additional files without titles/legends.

**Comment by FAtherden-eLife** [comment]
> supplementary-material-test-6

Is it worth adding a link to the allowed assets page, the point the user to a list of permitted labels?

**Comment by FAtherden-eLife** [comment]
Is this page where we should cover the Schematron checks for additional file titles?

`supplementary-material-title-test-1` - `supplementary-material-title-test-8`.

**Comment by FAtherden-eLife** [comment]
Think we should include `supplementary-material-child-conformance` here too.

Nice work James, thanks.

**Comment by Melissa37** [comment]
>Asset-level source files may accompany figures, videos and tables in an appendix as well as those in the main text. Schema and Chemical structures, however, cannot support associated source files.

I am not sure I understand this. Can you explain at the production meeting?

**Comment by Melissa37** [comment]
>To facilitate the interpretation and replication of experiments, authors are asked during full submission to provide information relating to sample-size estimation, replicates, and statistical reporting.

There is an Oxford comma here, but it's not used elsewhere

**Comment by Melissa37** [comment]
>Transparent reporting form
To facilitate the interpretation and replication of experiments, authors are asked during full submission to provide information relating to sample-size estimation, replicates, and statistical reporting. They are then encouraged to fill out a template form (available as a PDF or a Word file) describing the places within their article where this information has been included. This transparent reporting form will be published alongside the final version of record.
It is important to note that while TRFs accompany most articles, they are not mandatory. If, for example, an article does not describe experiments or the analysis of data (as might be the case in a Tools and Resources submission), the form would not be needed.
Transparent reporting forms do not require a title or legend and are published at the end of the Additional files section.

Transparent reporting forms then TRF then Transparent reporting forms again. Might be worth defining, using the abbreviation and then using it thereafter. I think its useful to use the abbreviation somewhere as that is used and might be a way for someone to look up what it is

**Comment by Melissa37** [comment]
>As indicated by the relevant schematron tests, asset-level source data and code should be relate directly 

related, not relate

**Comment by Melissa37** [comment]
>The details from the orphaned legend can then be added that asset's own legend

added *to* that...?

**Comment by Melissa37** [comment]
>Occasionally, authors will provide a LaTex (.tex) file as an additional file, under the assumption that we will typeset it for them. If they do so, they must be asked to provide a PDF version of this file so that it will be available in an easy-to-read format for publication.
We noticed that you have provided a .tex file as an additional file. Please could you provide a typeset PDF version of this file that we can use for final publication?

I don't understand this, can you explain in the prod meeting?

**Comment by Melissa37** [comment]
>In these cases, there is unfortunately little we can do beyond making sure the files to not have an arbitrarily low size (e.g. in the range of bytes rather than at least kilobytes).

to should be do?

**Comment by Melissa37** [comment]
Key Resources table schematron messages - suggest we mention KRTs here as they can sometimes remain as suppl files when they should be changed to appendices if not at the start of the methods?

**Comment by Melissa37** [comment]
>Action: This warning indicates at the pre-author stage that no file is present for an additional file entry. The author should be queried to provide the missing document.
Please provide the file for this source data.
Please provide the file for this source code.
Please provide the file for this supplementary file.
Please provide the file for this reporting standard

Suggest adding line, indicating the most appropriate of the options should be added as a query to author

**Comment by Melissa37** [comment]
>final-supplementary-material-test-5
Error: XXXXXX is missing a file (supplementary-material must have a media).
Action: This errors indicates no fil

This error (remove s)

**Comment by Melissa37** [comment]
>source-code-test-1
Warning: XXXXXX has a file which looks like code - XXXXXX, but it's not labelled as code.
Action: This warning indicates that an additional file has an extension that may indicate it is source code rather than, for example, data. It currently checks for the following extensions: .m, .py, .lib, .jl, .c, .sh, .for, .cpproj, .ipynb, .mph, .cc, .rmd, .nlogo, .stan, .wrl, .pl, .r, .fas, .ijm, .llb, .ipf, .mdl, .h. If the title and/or legend does not clearly indicate that the file contains data alone, please query the author as to whether it should be changed to source code.
Should this file be labelled as source code? 

Does this actually ever fire, if source code is always zipped up?

**Comment by Melissa37** [comment]
>supplementary-material-test-7
Error: supplementary-material in additional files sections cannot have the a media element with the attribute mimetype='video'. This should be mimetype='application'

Is there a typo in this "the a"

**Comment by Melissa37** [comment]
>back-supplementary-file-position
Error: XXXXXX id ends with XXXXXX, but it is placed XXXXXX. Either it is mislabelled, the id is incorrect, or it should be moved to a different position.
Action: This error indicates the labelling for a supplementary file does not match the sequence in which the other files of that type have been placed. And example would be Supplementary file 1,

An example, not And example

**Comment by Melissa37** [comment]
>back-supplementary-file-id
Error: The id (XXXXXX) for XXXXXX is not in the correct format. Supplementary files need to have ids in the format 'supp0'.
Action: This error indicates a supplementary file has an ID that does not confirm to the standard format 'supp0'. T

conform to?

**Comment by JGilbert-eLife** [comment]
> > source-code-test-1
> > Warning: XXXXXX has a file which looks like code - XXXXXX, but it's not labelled as code.
> > Action: This warning indicates that an additional file has an extension that may indicate it is source code rather than, for example, data. It currently checks for the following extensions: .m, .py, .lib, .jl, .c, .sh, .for, .cpproj, .ipynb, .mph, .cc, .rmd, .nlogo, .stan, .wrl, .pl, .r, .fas, .ijm, .llb, .ipf, .mdl, .h. If the title and/or legend does not clearly indicate that the file contains data alone, please query the author as to whether it should be changed to source code.
> > Should this file be labelled as source code?
> 
> Does this actually ever fire, if source code is always zipped up?

Doesn't fire on code, fires on other files that might be code. I did a double take on this too!

**Comment by JGilbert-eLife** [comment]
> Is this page where we should cover the Schematron checks for additional file titles?
> 
> `supplementary-material-title-test-1` - `supplementary-material-title-test-8`.

Argh - must have stopped searching prematurely. Sorry, will get those and the other one added in.

**Comment by Melissa37** [comment]
>supplementary-material-child-conformance	supplementary-material/*	**Error**: _XXXXXX is not allowed as a child of supplementary-material._

I am a bit confused by this at the end

**Comment by Melissa37** [comment]
Great work, thanks James!

**Comment by Melissa37** [comment]
>source-code-test-1
Warning: XXXXXX has a file which looks like code - XXXXXX, but it's not labelled as code.
Action: This warning indicates that an additional file has an extension that may indicate it is source code rather than, for example, data. It currently checks for the following extensions: .m, .py, .lib, .jl, .c, .sh, .for, .cpproj, .ipynb, .mph, .cc, .rmd, .nlogo, .stan, .wrl, .pl, .r, .fas, .ijm, .llb, .ipf, .mdl, .h. If the title and/or legend does not clearly indicate that the file contains data alone, please query the author as to whether it should be changed to source code.
Should this file be labelled as source code?

>Does this actually ever fire, if source code is always zipped up?

>Doesn't fire on code, fires on other files that might be code. I did a double take on this too!

Ahhh, good point! I guess reading this with an example in front of you it would be obvious, reading it alone it's a double-take! Thanks!!

**Comment by griffithsc** [comment]
At present, eLife cannot support inline audio-only playback so audio files (as distinct from videos) should be included as additional files. 
Pretty sure I know what this means, but could you be clearer about what you mean by inline here?

**Comment by griffithsc** [comment]
This should be done by downloading the file from the proof (or staged article) and seeing if there are any issues when it is opened in the appropriate program.
Not sure what staged article means, could you clarify this?

**Comment by griffithsc** [comment]
This should definitely be checked after the article is loaded to the journal website as conversions may occur at this stage. In the unlikely event that it appears the creation of the final package is responsible for the corruption of a file, the content processors should be advised and requested to resolve the issue.
I wasn't sure who you meant by content processors, could you clarify this?

**Comment by griffithsc** [comment]
Otherwise this is great - really comprehensive - thank you James!

**Comment by NuclearRedeye** [comment]
@JGilbert-eLife Just before I take a look at this, was I assigned to this by mistake or was there something you need my input on?

**Comment by FAtherden-eLife** [comment]
Think it was a mistake @NuclearRedeye! Feel free to ignore.

**Comment by FAtherden-eLife** [comment]
After doing a Pub check on Kriya 2 I realised we don't have robust enough tests on labelling for asset level source data/code.

I've added the following tests which (I presume) will also need covering on this page:
 - fig-data-label
 - fig-code-label
 - vid-data-label
 - vid-code-label
 - table-data-label
 - table-code-label

Sorry for the inconvenience.

**Comment by JGilbert-eLife** [comment]
No problem @FAtherden-eLife - I will take a look and get everything updated accordingly.

**Comment by FAtherden-eLife** [comment]
Many thanks!

**Comment by naushinthomson** [comment]
Nothing further to add, thanks for covering this one James!
