### ISSUE TITLE
Create Tables page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#43]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
I think that it might make sense to fold all the table header stuff into one section, even when it's cells in the body. The controls in Kriya don't, to my knowledge, distinguish between headers at the top and headers in the body, so it probably doesn't make sense to split them out, even though there is an XML distinction.

It might make sense to rephrase the descriptions of table footnotes to start with blank/uncited footnotes, then say something like 'these can be linked to the text in the table using . . .'  Just for clarity, and because I'm not sure which one we get more of.

Does it make sense to include a screenshot of the allowed colours in tables?

Are non-breaking spaces still a problem for the checks on labels?

Probably worth stating outright which of the 'table-report' tests fire at pre and post author stages.

distinct-label-conformance - would suggest putting (e.g. Table 1 and Table 1) just to ram home the point.

text-v-object-cite-test - "text should be added as a citation instead." -> suggest "text should be changed to a linked citation."

xref-column-test - for clarity, I'd suggest including the heading names for the 1st, 2nd and 4th columns.

doi-link-test - "This will fire if a table cell in a Key resources table contains a doi." Shouldn't that specify an unlinked DOI?

table-wrap-test-3 - does this only fire if the table isn't intended to be inline? If not, might be worth including multiple examples.

[I've not finished, but now Kriya is sort of working again!]

**Comment by naushinthomson** [comment]
Is there a reason the source data/code examples in Associated source data/code files is formatted with the code formatting? Is it because it refers to the XML?

'It's very unusual, but possible, that a header might need to contain normal, rather than header table cell' - I think an example might be useful here

Tables with multiple headers - I think the second screenshot can be deleted because I was a little confused - the 'Data collection statistics' as a header still makes some sense on page 2, but the problem is clearer on page 3 so it should be ok to just include that example. 

'In some articles, Key resources tables will be captured in a supplementary file instead.' - I can't remember if we have now moved to including these as appendices instead. Not sure whether we decided on a date to start doing this though! 

Should the checklist be the first thing at the top?

Is the action for table-fn-label-test-1 correct? The first sentence seems to relate to app-table-label-test-2.

**Comment by JGilbert-eLife** [comment]
Out of curiosity - why is the ID value not baked into kr-table-wrap-test-1?

**Comment by JGilbert-eLife** [comment]
This query -

"This Key resource table is not in the correct format. Please provide a revised table in the required format using this guide - https://cdn.elifesciences.org/author-guide/key_resources_table.xlsx. The table can be provided as an editable file (such as word or excel) in response to the proofing email. We regret that this was not brought to your attention earlier and apologise for the inconvenience."

I would suggest editing it to:

"This Key resource table is not in the correct format. Please provide a revised table as a Word or Excel file in response to the proofing email. A template for the table can be found at https://cdn.elifesciences.org/author-guide/key_resources_table.xlsx. We regret that this was not brought to your attention earlier and apologise for the inconvenience.

**Comment by JGilbert-eLife** [comment]
table-test-2 - just going off the warning, I don't think it's clear how a user is supposed to identify a missing header as a mistake. Maybe needs to refer them back to the original article file?

**Comment by JGilbert-eLife** [comment]
Thinking about headers in the body and tr-test-3, I'm not sure it's fair to call it unusual to have headers in tables. That's a fairly normal way to structure complex or detailed tables, and we allow it.

**Comment by FAtherden-eLife** [comment]
Thanks Both!

Adding the link to the page here for ease for next time:
https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/tables

> I think that it might make sense to fold all the table header stuff into one section, even when it's cells in the body. The controls in Kriya don't, to my knowledge, distinguish between headers at the top and headers in the body, so it probably doesn't make sense to split them out, even though there is an XML distinction.

I didn't do this because I didn't want to make it too Kriya specific - but I also didn't know how to make it _not_ XML specific when trying to not make it too Kriya specific. I'm happy to change if the distinction isn't helpful for anyone else (it is for me - but that's just me) - perhaps we can discuss on Thursday.

> Are non-breaking spaces still a problem for the checks on labels?

Yes they will be. I'll add this to the actions so it's explicit.

I've addressed your other points in this [comment](https://github.com/elifesciences/schematron-gitbook/issues/43#issuecomment-636917150).

**Comment by JGilbert-eLife** [comment]
rrid-test, org-test, code-test and related - these aren't specific to the context of tables, right? Shouldn't these be on another page about general styling/content tests?

**Comment by JGilbert-eLife** [comment]
Likewise, I think citation tests should be on a separate page from table content ala references.

**Comment by JGilbert-eLife** [comment]
table-xref-test-4 - should state what to do if there is no Table 1—source data 1!

**Comment by FAtherden-eLife** [comment]
@naushinthomson 

> Is there a reason the source data/code examples in Associated source data/code files is formatted with the code formatting? Is it because it refers to the XML?

Changed to bold formatting.

> 'It's very unusual, but possible, that a header might need to contain normal, rather than header table cell' - I think an example might be useful here

I can't find an appropriate example in the archive because there isn't one. Maybe I'll just change the text to say that it's never appropriate...

> Tables with multiple headers - I think the second screenshot can be deleted because I was a little confused - the 'Data collection statistics' as a header still makes some sense on page 2, but the problem is clearer on page 3 so it should be ok to just include that example.

I'll find a better (different) example of what I mean. In this case it just happens to be that that is correct because the same heading is repeated. 

> 'In some articles, Key resources tables will be captured in a supplementary file instead.' - I can't remember if we have now moved to including these as appendices instead. Not sure whether we decided on a date to start doing this though!

As I recall, we were going to implement this once we've fixed the display of appendices in the PDF.

> Should the checklist be the first thing at the top?

I can put it there (happy to if you think it's better), but will it make sense without the context of the stuff above it?

> Is the action for table-fn-label-test-1 correct? The first sentence seems to relate to app-table-label-test-2.

Thanks I've corrected it.

**Comment by FAtherden-eLife** [comment]
@JGilbert-eLife 
> Thinking about headers in the body and tr-test-3, I'm not sure it's fair to call it unusual to have headers in tables. That's a fairly normal way to structure complex or detailed tables, and we allow it.

`tr-test-3` is about normal cells in the header. Is that the right warning you mean? I've changed the wording in `th-row-test`:
> This will fire if a table row contains a mixture of table header cells and normal table cells. This is relatively unusual, although there are a some cases where this would be appropriate.

but this _is_ unusual since it's only one cell. I can't find any other places where I've referred to headers in the body as being unusual.

**Comment by FAtherden-eLife** [comment]
> rrid-test, org-test, code-test and related tests to do with content mistakes - these aren't specific to the context of tables, right? Shouldn't these be on another page about general styling/content tests? We don't want to have to repeat them, since then we'd have the ID/link going to two places.

Good point. I've moved them to a separate page, General Content for now. @naushinthomson, could you have a think about how you want this captured/what the name for this should be? Thanks!

**Comment by FAtherden-eLife** [comment]
> Likewise, I think citation tests should be on a separate page from table content ala references.

These _are_ specific to table citations (rather than general citations). Perhaps we should discuss on Thursday.

**Comment by FAtherden-eLife** [comment]
> table-xref-test-4 - should state what to do if there is no Table 1—source data 1!

Thanks for catching that. I've updated the action.

**Comment by FAtherden-eLife** [comment]
> 'It's very unusual, but possible, that a header might need to contain normal, rather than header table cell' - I think an example might be useful here

@JGilbert-eLife, @naushinthomson, what are your thoughts on me saying that this is _not_ allowed, and making `tr-test-3` an error instead of warning? 

I can't find any instances where this has been appropriately done in the archive.

**Comment by naushinthomson** [comment]
table-fn-label-test-1 should the action be ' If this warning fires, it is because a footnote has an indicator and it **isn't** one of the allowed symbols.'?

colour-check-table - Is there a scenario where we might see this message as well as the pre/final colour-check-table-2 in the same article, in which case how do we resolve the difference between the two Kriya queries - one which asks the authors to remove formatting and the other which asks the authors to pick a colour?

kr-table-header-3 - Should we also add to the action (just to be absolutely clear) that the thing to do is typeset the table according to the template?

th-row-test - For the second case, is it worth clarifying that the decision to make 'Map resolution' span the entire row is just by looking at the rest of the table? Or did you compare with the original document in which case would it be worth adding a screenshot of that?

I think that's all from me in terms of comments!

**Comment by naushinthomson** [comment]
> > 'It's very unusual, but possible, that a header might need to contain normal, rather than header table cell' - I think an example might be useful here
> 
> @JGilbert-eLife, @naushinthomson, what are your thoughts on me saying that this is _not_ allowed, and making `tr-test-3` an error instead of warning?
> 
> I can't find any instances where this has been appropriately done in the archive.

Fine by me!

**Comment by bcollins14** [comment]
Sorry if I repeat any of the above. 

"In Decision letters and Author responses the title is optional'

For completeness, can we add that if a legend is present then a title is required?

**Comment by bcollins14** [comment]
"Note that an object labelled as one table (with one label and optional title/caption), can actually be made up of multiple tables. This is avoided, where possible in eLife content (see also XML structure)." 

Why? Why would an author do this and we is it avoided?

**Comment by bcollins14** [comment]
Authors requesting tables as figure supplements? I haven't finished reading but just adding this in case this is not covered

**Comment by bcollins14** [comment]
"All footnotes that have indicators should follow this sequence , †, ‡, §, ¶, , ††, ‡‡, §§, ¶¶, , †††, ‡‡‡, §§§, ¶¶¶, **, ††††, ‡‡‡‡, §§§§, ¶¶¶¶, etc. in accordance with house style"

I don't entirely understand what you mean by 'this sequence' and the symbols (maybe sleepy brain). Are these the only symbols we use? Could we include a screenshot of good usage?

**Comment by Melissa37** [comment]
>Those outside of Decision letters and Author responses display in both the HTML and in the PDF. 

I think this would clearer if it said

>Tables display in both the HTML and in the PDF. Decision letters and Author responses are not added to the PDF so their tables only appear in the HTML version of the article.

Or something like that. It stumped me when I read it :-)

**Comment by bcollins14** [comment]
Is Associated source data/code files a common term? If not, would Supporting source data/code files be more suitable?

**Comment by bcollins14** [comment]
Allowed table colours - why do we only allow these ones?

**Comment by Melissa37** [comment]
Table body section:

>(by default roman)

Please add comma after default or change to (by default this is roman)

**Comment by Melissa37** [comment]
Table footnotes, there is a house style order and some more info missing from the GitBook:

Order: Designated footnotes, p value footnotes (*p<0.05; **p<0.01; ***p<0.001), undesignated footnotes and abbreviations last. All abbreviations used in tables must be defined in footnotes (unless on list of not required definition). 

https://docs.google.com/spreadsheets/d/1tC0mva-zPZcnJXk3PMwYOZsq1ZXmrE9NjTT0DT28f9c/edit#gid=823351812

**Comment by Melissa37** [comment]
>Associated source data/code files

Is it worth showing s display example of the HTML version too? Not just PDF

**Comment by bcollins14** [comment]
Would it be good to mention the troubles we sometimes have when adding citations in tables or trying to add text after a URL?

**Comment by Melissa37** [comment]
>Tables can be placed in the body of an article, in appendices, in Decision Letters and in Author responses.

Worth mentioning boxes here for the non pure XML understanders ;-)

**Comment by Melissa37** [comment]
Can more be said about inline tables, ie examples, were allowed or not allowed.

**Comment by Melissa37** [comment]
In the schematron warnings "Error: XXXXXX - Table label does not conform to the usual format." it would be useful to explicitly mention the full stop is required inside the label

eg "Please ensure that there are no typos, missing or extra spaces, that the capitalisation is correct, and that the character between 'Appendix X' and 'table X' is an em dash." mentions everything else except the full stop

**Comment by Melissa37** [comment]
>table-fn-label-test-1
Warning: Footnote starts with label which is not in line with house style - XXXXXX. Footnote symbols should be in the order: *, †, ‡, §, ¶, **, ††, ‡‡, §§, ¶¶, etc.
Action: Footnote indicators should be in the following sequence , †, ‡, §, ¶, , ††, ‡‡, §§, ¶¶, , †††, ‡‡‡, §§§, ¶¶¶, **, ††††, ‡‡‡‡, §§§§, ¶¶¶¶, etc. If this warning fires, it is because a footnote has an indicator and it isn't one of the allowed symbols. The indicators should be changed in line with the sequence above.

Does this allow for the following scenario, which is allowed:

*p<0.05; **p<0.01; ***p<0.001

I assume it does as it only looks at the first symbol, but wanted to check

**Comment by Melissa37** [comment]
>Action: This will fire when a Table label occurs twice in the same article for example there is a Table 1 and a Table 1. Table labels must be distinct. If this fires, action should be taken to ensure that this label is not used more than once.

This would read better as:

>Action: This will fire when a Table label occurs twice in the same article for example are two 'Table 1.'s. Table labels must be distinct. If this fires, action should be taken to ensure that this label is not used more than once.

**Comment by Melissa37** [comment]
>Action: This will fire at pre-author stages when a table is placed out of sequence in the body of an article (such as Table 1 being placed after Table 2). If this warning fires, and there is no citation for that table, please add the following author query:

Is this tagged table citations? Does it allow for untagged citations? I don't see them mentioned anywhere as a solution to this problem, which would be useful?

**Comment by Melissa37** [comment]
>If the table citation is obviously a reference to a table from another article or piece of work (e.g. Table 1 from Smith et al., 2020), then this can be ignored.

Please change to

>If the table citation is obviously a reference to a table from another article or piece of work (e.g. Table 1 from Smith et al., 2020), then this should be ignored.

'should', or 'must' would be good!

**Comment by Melissa37** [comment]
>Action: This will fire at a pre-author stage if a table cell in a table has a style attribute with an unallowed value. Usually this will be because the colour formatting is not a supported colour. If it is one of the supported colours and this message fires this is a problem - it means that the content has not been typeset correctly.

and following message too.

Is it true that it's not been typeset correctly, or should this state that it's not been **tagged** correctly?

**Comment by Melissa37** [comment]
I don't understand table-wrap-test-3
 and table-wrap-test-4

Sorry! I don't think they are clear

**Comment by Melissa37** [comment]
pre-table-wrap-cite-1
Warning: There is no citation to XXXXXX. Ensure to query the author asking for a citation.
Action: This will fire at pre-author stages for tables (which are not Key resources tables) with labels, in articles which are not corrections or retractions. If this fires (and there are no issues with labelling or the table id), then the following author query should be added:

Conditions for corrections or retractions are here but not mentioned anywhere else above. Should this be added to the main explanation text that these article types have different conditions?

**Comment by Melissa37** [comment]
>feat-table-wrap-cite-1
Warning: There is no citation to XXXXXX. Is this correct?
Action: This will fire at all stages for tables (which are not Key resources tables) with labels, in feature content (insights or feature articles). 
If this fires at a pre-author stage (and there are no issues with labelling or the table id), then the following author query should be added:

New conditions that are different for feature content - not mentioned above in main explanation part

**Comment by Melissa37** [comment]
>Action: This will at all stages fire if a table has all the KR table headings but does not have an  id keyresource. If this fires, ensure that the Table is captured as a Key resources table (with the correct id, label and no title or caption).

Style issue - for other ones you've done this:

>Action: This will at all stages fire if a table has all the Key resources table headings but does not have an id keyresource. If this fires, ensure that the Table is captured as a KR table (with the correct id, label and no title or caption).

**Comment by Melissa37** [comment]
>Action: This will fire at all stages if a table has a title containing the text 'Key resource'. If it is a key resources table, then this should be captured as a Key resources table (with the correct id, label and no title or caption). If it is not (i.e. just a normal table, without the standard KR table headings, which happens to have the text 'Key resource' in it's title), then this message can be ignored.


Style issue, please change to:

>Action: This will fire at all stages if a table has a title containing the text 'Key resource'. If it is a Key resources table, then this should be captured as a KR table (with the correct id, label and no title or caption). If it is not (i.e. just a normal table, without the standard KR table headings, which happens to have the text 'Key resource' in it's title), then this message can be ignored.

**Comment by Melissa37** [comment]
Please s&f Key resources table and ensure capitalisation on consistent thorughout doc

**Comment by Melissa37** [comment]
>Action: This will fire at all stages if a KR table does not have the correct number of headings. All KR tables should have 5 headings/columns. If the table is typeset correctly (please check this carefully), as the author provided it, then the following author query should be added:
This Key resource table is not in the correct format. Please provide a revised table as a Word or Excel file in response to the proofing email. A template for the table can be found at https://cdn.elifesciences.org/author-guide/key_resources_table.xlsx. We regret that this was not brought to your attention earlier and apologise for the inconvenience.

Change to:

>Action: This will fire at all stages if a Key resources table does not have the correct number of headings. All KR tables should have 5 headings/columns. If the table is typeset correctly (please check this carefully), as the author provided it, then the following author query should be added:
This Key resource table is not in the correct format. Please provide a revised table as a Word or Excel file in response to the proofing email. A template for the table can be found at https://cdn.elifesciences.org/author-guide/key_resources_table.xlsx. We regret that this was not brought to your attention earlier and apologise for the inconvenience.

**Comment by Melissa37** [comment]
There is no mention of column alignment and normal expectations. Should there be? This is something that comes up.

is there a choice? decimal, left etc

**Comment by Melissa37** [comment]
>Action: This will fire if a <table-wrap> element does not have a child <table> element. If this fires, it has been typeset incorrectly and steps should be taken to correct it.

Does this mean there is a table wrapper but no table?
Perhaps the message could say that?ie there is no table present, but there is table wrapping XML

**Comment by Melissa37** [comment]
>Action: This will fire if a <table-wrap> element more than one a child <table> element. If the table has two or more sections in it with differing numbers of columns, but it has the same label (and title), then this warning can be ignored. If it does not, the table should be collated so that there is only one table element.

Presumably only Exeter can do that action? Is it worth saying that...

**Comment by Melissa37** [comment]
>Action: This will fire if a <table> element does not have a child <tbody> element. This means that something has gone wrong with the typesetting and the table will need to be corrected.

Does this mean there is a table tag in the XML but no table content?
Perhaps the message could say that?ie there is no table present, but there is table wrapping XML

**Comment by Melissa37** [comment]
Could the XML structure section be moved up to the main explanation?
When reading this page sequentially that would be super useful to hit that sooner :-)

**Comment by FAtherden-eLife** [comment]
@bcollins14 
> Allowed table colours - why do we only allow these ones?

These are the only ones supported by Continuum, and I imagine they have been picked with accessibility in mind. Do we need to add this info?

**Comment by FAtherden-eLife** [comment]
@Melissa37 
> > Associated source data/code files

> Is it worth showing s display example of the HTML version too? Not just PDF

I already included an embedded link in "[Here is an example](https://elifesciences.org/articles/46883/figures#table1sdata1) from published content:". Is that OK or do you still want a screenshot?

**Comment by FAtherden-eLife** [comment]
> > table-fn-label-test-1
Warning: Footnote starts with label which is not in line with house style - XXXXXX. Footnote symbols should be in the order: *, †, ‡, §, ¶, **, ††, ‡‡, §§, ¶¶, etc.
Action: Footnote indicators should be in the following sequence , †, ‡, §, ¶, , ††, ‡‡, §§, ¶¶, , †††, ‡‡‡, §§§, ¶¶¶, **, ††††, ‡‡‡‡, §§§§, ¶¶¶¶, etc. If this warning fires, it is because a footnote has an indicator and it isn't one of the allowed symbols. The indicators should be changed in line with the sequence above.

> Does this allow for the following scenario, which is allowed:

> *p<0.05; **p<0.01; ***p<0.001

> I assume it does as it only looks at the first symbol, but wanted to check

All the test itself checks for is that, if a footnote starts with a superscript symbol, that it is one of those symbols. It doesn't actually check that the sequence itself is correct. I can add one to do that but it's complicated by the fact that we do not use `label` and instead just add superscripted text. 

The upside is that it will not fire for the use case you provide.

**Comment by FAtherden-eLife** [comment]
@Melissa37 
> I don't understand table-wrap-test-3
> and table-wrap-test-4

> Sorry! I don't think they are clear

Is the revised wording any clearer?

**Comment by FAtherden-eLife** [comment]
- Move Tables with multiple header after table header section.
- Include info on accessibility - maybe update author queries.
- Include info on how colours will not display downstream. Also add the query to the allowed colours section.
- Move checklist to the top
- Both colour checks firing - update action
- kr-table-header-3 - add example to action
- Add example of multiple table with authors original.
- Add a screenshot of good footnote indicators
- Would it be good to mention the troubles we sometimes have when adding citations in tables or trying to add text after a URL?
- Mention box text per Melissa's comment
- Add section of inline tables, add info on these.
- Add section on citations out of sequence/those left unlinked.
- Add section on Corrections/Retractions
- Feature content
- Add section on alignment.
- table-test-1 - deal with action
