### ISSUE TITLE
Create Ethics page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#62]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by bcollins14** [comment]
Hello everyone, I believe this page is ready for its first review. [https://app.gitbook.com/@elifesciences/s/productionhowto/ethics](url)

@JGilbert-eLife @naushinthomson @Melissa37 @FAtherden-eLife

**Comment by FAtherden-eLife** [comment]
Thanks @bcollins14 (clicking that link doesn't work btw - looks like it's tagged like this in the markdown `[https://app.gitbook.com/@elifesciences/s/productionhowto/ethics](url)`, which means that browsers will try to open `url`. Adding the link as plain text in your comment - https://app.gitbook.com/@elifesciences/s/productionhowto/ethics - or if embedding, then adding it within the `()` brackets - `[this is embedded text](https://app.gitbook.com/@elifesciences/s/productionhowto/ethics)` will work.)

**Comment by Melissa37** [comment]
Could you provide more detail about the format.

For instance, the author submits this info in the screens on EJP, eg:
![Screenshot 2020-12-17 at 13 03 39](https://user-images.githubusercontent.com/6051876/102491621-65956c80-4068-11eb-9fee-2149809a9ae9.png)


This is exported to Exeter in the XML.

Provide a screenshot of how it looks in Kriya

And provide some guidance that Animal experimentation: and Human subjects: are pieces of text that should not change

**Comment by Melissa37** [comment]
There is nothing about clinical trial info, which is also ethics

**Comment by Melissa37** [comment]
Can you make it clear these are not required field.

**Comment by FAtherden-eLife** [comment]
> ethics-title-test
> ...
> Action: This error will show if the title is anything but 'Ethics', the title should be corrected to 'Ethics'. 

Please clarify - who would have to do this?

**Comment by FAtherden-eLife** [comment]
For the XML example used at the bottom of the page, it would be good to include something with more than one footnote. Here's an example from 56991:
```xml
<fn-group content-type="ethics-information">
  <title>Ethics</title>
  <fn fn-type="other" id="fn1">
    <p>Clinical trial registration Clinical Trials.gov no. NCT02752672.</p>
  </fn>
  <fn fn-type="other" id="fn2">
    <p>Human subjects: A clinical study in psoriatic patients treated with dithranol was completed in cooperation with the Department of Dermatology, Klagenfurt State Hospital. Clinical trial procedures were approved by the ethics committee of the federal state of Carinthia, Austria (protocol number A23/15) and all participants gave written informed consent in accordance with the principles of the Declaration of Helsinki.</p>
  </fn>
  <fn fn-type="other" id="fn3">
    <p>Animal experimentation: All mouse experiments were approved by the Austrian Government, Federal Ministry for Science and Research (protocol numbers BMWF-66-010/0032-11/3b/2018, 66.009/0200-WF/II/3b/2014) and animal experiments performed in Vienna were additionally approved by the Animal Experimental Ethics Committee of the Medical University of Vienna.</p>
  </fn>
</fn-group>
```

**Comment by FAtherden-eLife** [comment]
You can include the example above as an example of a clinical trial one in the `Examples` section.

**Comment by FAtherden-eLife** [comment]
That's it from me - thanks.

**Comment by Melissa37** [comment]
@bcollins14 Fred and I spoke with Maria and we know what needs to be done for Clinical trials and ethics. This does need to be added to this page.
@FAtherden-eLife can you add a link to the Gitlab ticket here so Becky knows what to add?
Thanks!

**Comment by bcollins14** [comment]
@FAtherden-eLife Sorry I cannot seem to find the Gitlab ticket, do you mind adding it please?

**Comment by FAtherden-eLife** [comment]
@bcollins14 As we discussed previously, what remains is to add the clinical trial information to this page - how it should be tagged, any related Schematron messages, and so on. There's no GitLab ticket since there's still a need to keep this information in the few articles that have it.

Let me know if you need any help updating the page.

**Comment by bcollins14** [comment]
@FAtherden-eLife I have included some information about clinical trials but could not see any further schematron messages to add. Would you mind letting me know if anything more is needed?

**Comment by FAtherden-eLife** [comment]
Thanks for this @bcollins14. Looking good. Just a couple of suggestions. 

I would probably remove the mention of the FDA and studies being carried out on Animals, since that may, or may not be the case depending on the article.

I think it would be good to include what's currently in the author guide:
> eLife follows the [recommendations of the ICMJE](http://www.icmje.org/about-icmje/faqs/clinical-trials-registration/) that all trials must have been prospectively registered to be considered for publication, and the clinical trial registration number will be requested during submission.

You could include also something like:
> There are numerous clinical trial registries that are accepted by eLife [you could link again to that ICMJE page above where it states them]. Clinical trials are identified with a trial registration number, which is unique to that particular registry. Typically this information will be included in a structured abstract, however if the scope of an article is not purely clinical, but a clinical trial has nevertheless been undertaken, this information will need to be included in the ethics statement instead. This statement will include both the clinical trial registry and the clinical trial number, so that it can be accurately identified by readers.

**Comment by bcollins14** [comment]
Thanks Fred, will do 😄
