### ISSUE TITLE
Create Conference references page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#70]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
@naushinthomson @JGilbert-eLife @Melissa37 @FAtherden-eLife This page is now ready for your review:

https://app.gitbook.com/@elifesciences/s/productionhowto/article-details/content/references/conference-reference

Thanks!

**Comment by FAtherden-eLife** [comment]
Think I'm going to have to make `pre` (warning) and `final` (error) equivalents for some of these tests, so that eventually we can have a hard barrier which doesn't allow anything with errors to move onto author proofing. I can update this page with that myself though, if desired.

**Comment by FAtherden-eLife** [comment]
Nothing further to ad - thanks for this.

**Comment by naushinthomson** [comment]
Looks good to me!

**Comment by Melissa37** [comment]
One thing I was thinking about, this does not cover the scenario of when an abstract or paper is published in a supplement to a journal. We used to do this at the BMJ, here is an example:
https://ard.bmj.com/search/volume%3A79%20issue%3ASuppl%2B1%20jcode%3Aannrheumdis%20sort%3Arelevance-rank?facet%5Btoc-section-id%5D%5B0%5D=Metabolic%20pathways%20during%20the%20regulation%20of%20inflammation%20and%20immunity

In that case, the journal-title and suppl is used for the citation, not the conference title and location. 

Do we need to make this distinction clear in the explanation at the top?

**Comment by Melissa37** [comment]
Could you use a real example in the table - the DOI provided there points to a journal article and not a conference proceeding

Also, in the screenshot from the kitchen sink we've got the title of the conference wrong :-(
![Screenshot 2020-11-25 at 17 37 15](https://user-images.githubusercontent.com/6051876/100263055-ea4b0a00-2f44-11eb-8724-192ac581c587.png)

Is there an available reference that is real that has a conference title and a conference name?
Looking for cite as info for 2018 IEEE 15th International Symposium on Biomedical Imaging (ISBI) there is no conference title:
![Screenshot 2020-11-25 at 17 40 26](https://user-images.githubusercontent.com/6051876/100263356-53328200-2f45-11eb-9b5d-e6244ab8c412.png)

**Comment by Melissa37** [comment]
Do we have any rules about the conference location? Like what we do or do not publish in there (city, state, country)?

**Comment by Melissa37** [comment]
>Details for conference references can usually be found online, however there is no central indexing service for conferences as there is for journals.

I don't think this is true and should not be stated:
https://www.crossref.org/education/content-registration/content-type-markup-guide/conference-proceedings/

Not all journals register DOIs and Crossref is a central indexing service for conference proceedings if a publisher chooses to use it :-)

**Comment by Melissa37** [comment]
>err-elem-cit-confproc-10-1
Error: <conf-name> is required. Reference 'XXXXXX' has XXXXXX <conf-name> elements.
Action: Every conference reference must contain a conference name. This error indicates that no conference name is present. Compare the reference to the original manuscript file to check for processing errors such as the conference name being tagged as a conference title or as part of the article title. If one has not been provided, please query the author with the following:
Please provide the conference name for this reference.

This makes me think we should potentially ditch the conference title tag...? Might make of a more simple life!

**Comment by Melissa37** [comment]
>Action: This error will appear if a journal reference has a first page value larger than the last page value (this can happen if the authors truncate the last page, e.g. 123–34). If possible, look the article up online to find the correct page range. If this is not possible, add the following author query:
Please provide the correct page range for this reference.

I wonder whether we look a bit silly asking this if an author has provided 123-24 and whether we should change the AQ to "is the last page of this reference 124?
More work for Exeter but if the author provided a truncated version s/he might say it is correct as it is to a human reader!

**Comment by Melissa37** [comment]
>err-elem-cit-confproc-9-2-2
Error: A <source> element within a <element-citation> of type 'confproc' may only contain the child elements<italic>, <sub>, and <sup>. No other elements are allowed. Reference 'XXXXXX' has child elements that are not allowed.
Action: This error will appear if there are formatting elements in the <source> element (conference title) other than italics, superscripts and subscripts (e.g. bold, underline). Make sure any disallowed formatting is removed.

Needs a space in here: elements<italic>

**Comment by Melissa37** [comment]
Can we ask Exeter to add iso dates to conf-date?
https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/conf-date.html

**Comment by bcollins14** [comment]
Looks good to me, thanks!

**Comment by JGilbert-eLife** [comment]
> > err-elem-cit-confproc-10-1
> > Error:  is required. Reference 'XXXXXX' has XXXXXX  elements.
> > Action: Every conference reference must contain a conference name. This error indicates that no conference name is present. Compare the reference to the original manuscript file to check for processing errors such as the conference name being tagged as a conference title or as part of the article title. If one has not been provided, please query the author with the following:
> > Please provide the conference name for this reference.
> 
> This makes me think we should potentially ditch the conference title tag...? Might make of a more simple life!

I looked into this based on the list Fred provided. It looks like conferences on the SPIE digital library are a good example of references with both title and name e.g. https://doi.org/10.1117/12.860783

**Comment by JGilbert-eLife** [comment]
> Can we ask Exeter to add iso dates to conf-date?
> https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/conf-date.html

We do not currently use conf-date and year already has this.

**Comment by Melissa37** [comment]
>
err-elem-cit-confproc-10-1
Error: is required. Reference 'XXXXXX' has XXXXXX elements.
Action: Every conference reference must contain a conference name. This error indicates that no conference name is present. Compare the reference to the original manuscript file to check for processing errors such as the conference name being tagged as a conference title or as part of the article title. If one has not been provided, please query the author with the following:
Please provide the conference name for this reference.

This makes me think we should potentially ditch the conference title tag...? Might make of a more simple life!

>>I looked into this based on the list Fred provided. It looks like conferences on the SPIE digital library are a good example of references with both title and name e.g. https://doi.org/10.1117/12.860783

So when you download the citation this is what you get for bibtex:

@inproceedings{10.1117/12.860783,
author = {Patrick J. La Rivière and Darin Clark and Alexandra Rojek and Phillip Vargas and Xianghui Xiao and Francesco DeCarlo and Gordon Kindlmann and Keith Cheng},
title = {{Optimizing synchrotron microCT for high-throughput phenotyping of zebrafish}},
volume = {7804},
booktitle = {Developments in X-Ray Tomography VII},
editor = {Stuart R. Stock},
organization = {International Society for Optics and Photonics},
publisher = {SPIE},
pages = {186 -- 193},
keywords = {Synchrotron, MicroCT, Zebrafish},
year = {2010},
doi = {10.1117/12.860783},
URL = {https://doi.org/10.1117/12.860783}
}

And this is what you get for  ris:
Title: Optimizing synchrotron microCT for high-throughput phenotyping of zebrafish (inproceedings)
Author: Patrick J. La Rivière and Darin Clark and Alexandra Rojek and Phillip Vargas and Xianghui Xiao and Francesco DeCarlo and Gordon Kindlmann and Keith Cheng
Booktitle: Proc.SPIE
Year: 2010
Volume: 7804 
Month: 9
...

Personally I don't think it would be bad thing to smish them together into one tag if we get them. Nobody is using the proper tags by the looks of things :-) and it prevents confusion over which tag to us.

WDYT?

**Comment by FAtherden-eLife** [comment]
Looks like we didn't include conference title for Libero Editor - https://github.com/libero/editor/issues/100

**Comment by FAtherden-eLife** [comment]
Looks like the `source` doesn't display on the site currently, so if we do decide to keep it, we should get that fixed. e.g.:
```xml
<element-citation publication-type="confproc">
    <person-group person-group-type="author">
        <name>
            <surname>Woody</surname>
            <given-names>MS</given-names>
        </name>
        <name>
            <surname>Capitanio</surname>
            <given-names>M</given-names>
        </name>
        <name>
            <surname>Ostap</surname>
            <given-names>EM</given-names>
        </name>
        <name>
            <surname>Goldman</surname>
            <given-names>YE</given-names>
        </name>
    </person-group>
    <year iso-8601-date="2017">2017</year>
    <article-title>An ultra-fast EOD-based force-clamp detects rapid biomechanical transitions. in
        10347</article-title>
    <source>Optical Trapping and Optical Micromanipulation XIV; 103470Q</source>
    <conf-name>SPIE Nanoscience + Engineering</conf-name>
    <conf-loc>San Diego, California</conf-loc>
    <pub-id pub-id-type="doi">10.1117/12.2277130</pub-id>
</element-citation>
```
https://elifesciences.org/articles/49266#bib58

**Comment by JGilbert-eLife** [comment]
OK, I'll update to remove Conference title/source as a field we use.
