### ISSUE TITLE
Create Data references page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#71]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by Melissa37** [comment]
In the table there is a mix of capitalization for Accession

**Comment by Melissa37** [comment]
In the table it mentions Website (in Accession or DOI entry) but in the line for website it says URL - would be better to sue the same term in both instances to avoid any potential confusion

**Comment by Melissa37** [comment]
>Non-mandatory fields are required if they exist.

Could this be unbolded? I did a double take, thinking the terms underneath in bold were linked to that statement 

![Screenshot 2021-01-06 at 09 57 22](https://user-images.githubusercontent.com/6051876/103755353-9a606800-5005-11eb-8fd2-468f8e842d45.png)

**Comment by Melissa37** [comment]
It's a bit confusing - is a URL required if there is an accession number? It does not read clearly that a URL is NOT required or desired if there is a DOI but IS if there is an accession - which I think is the case?

**Comment by Melissa37** [comment]
>The Mass Spectrometry Interactive Virtual Environment (MassIVE), however, only clearly shows the title for the article. Author details are limited to the citation associated with the data and the primary contact (effectively corresponding author) for the dataset. Since the authors for the dataset may differ from those on the associated publication and the contact is unlikely to be solely responsible for collecting the data, an author query may be required to seek the full author list for the reference.

What is our success rate in authors providing full auto lists for datasets like this? I am curious because if they are re-suing datasets do they know the authors and can get those details or are they as in the dark as us?

**Comment by Melissa37** [comment]
Is it worth adding a line here about datasets not yet available? Or is this totally irrelevant until we change the process and stop putting data references in the DAS?

In which case we'd need to remember to update this page when we do that :-)

**Comment by FAtherden-eLife** [comment]
Would it be worth specifying at what stages `pre-` and `final-` messages fire, or is that implied/common knowledge now?

**Comment by Melissa37** [comment]
>Action: This warning indicates that more than one <source> element (database name) is present in a conference reference. The extra <source> elements should be removed — however please check whether the contents should be moved to the dataset title or the database name fields first. If possible locate the dataset online to check for the correct details.
final-err-elem-cit-data-11-2
Error: Data reference 'XXXXXX' has XXXXXX source elements. It must contain one (and only one).
Action: This error indicates that more than one <source> element (database name) is present in a conference reference. The extra <source> elements should be removed — however please check whether the contents should be moved to the dataset title or the database name fields first. If possible locate the dataset online to check for the correct details.

I think this is a copy paste issue and conference should be changed to data

**Comment by Melissa37** [comment]
>err-elem-cit-data-18

typo: deleteing should be deleting

**Comment by FAtherden-eLife** [comment]
Should we be getting rid of assigning authority for these now (before we move data references from the DAS). What do they add? They aren't gathered by crossref (since I presume Graham's tools will only be pulling those with the `specific-use` attribute out, and in any case, it no longer relies on it `assigning-authority`), and they aren't display on our site, PubMed etc. - only in the PDF (which is typically just a duplication of the database name or potentially a source of confusion).

**Comment by JGilbert-eLife** [comment]
> > Non-mandatory fields are required if they exist.
> 
> Could this be unbolded? I did a double take, thinking the terms underneath in bold were linked to that statement
> 

Sure - I've made this consistently roman on other pages.

**Comment by naushinthomson** [comment]
Re: Melissa's comment about the accession vs website field requirements, I agree the description of accession seems to say that you need both accession and website whereas the table seems to suggest one or the other is okay. 

I'm also confused by the wording of:
>Website: A URL is permitted as an alternative to an accession or DOI, if the latter are not available (note that this is a URL tagged separately from an accession number, rather than the URL for an accession number mentioned above).

I know we covered this in today's meeting but is there any way to make the wording clearer?

**Comment by naushinthomson** [comment]
Is it possible to clarify the difference between Publisher and Authority? That always trips me up in Kriya!

**Comment by naushinthomson** [comment]
I think that's all from me otherwise! :)

**Comment by FAtherden-eLife** [comment]
Just checked and in it's current state the Schematron (`final-err-elem-cit-data-13-1`) will fire if there isn't a `pub-id`, even if there is an `ext-link`. 

Obviously in the future, or now, we want to permit just an `ext-link` for general database references. Would Kriya parse it out correctly if there was just a `Website` field? Or would it output a `pub-id` with an `xlink:href` but no text and no other or empty attributes? If Kriya parses it fine, then happy to change it immediately for dataset refs in the ref list.

**Comment by FAtherden-eLife** [comment]
I've just tested and it looks like Kriya parses it correctly in the XML :tada:

```xml
<ref id="bib89">
    <element-citation publication-type="data">
        <person-group person-group-type="author">
            <name>
                <surname>Test</surname>
                <given-names>A</given-names>
            </name>
            <name>
                <surname>Test</surname>
                <given-names>B</given-names>
            </name>
        </person-group>
        <year iso-8601-date="2020">2020</year>
        <data-title>Dataset title</data-title>
        <source>Gene Expression Omnibus</source>
        <ext-link ext-link-type="uri" xlink:href="https://www.ncbi.nlm.nih.gov/geo/"
            >https://www.ncbi.nlm.nih.gov/geo/</ext-link>
    </element-citation>
</ref>
```

No just checking the PDF and Continuum...

**Comment by FAtherden-eLife** [comment]
As expected, PDF display is fine 
![Screenshot 2021-01-07 at 16 45 01](https://user-images.githubusercontent.com/43879983/103919227-b9472300-5107-11eb-9e39-a2f1e987a4a1.png)

**Comment by FAtherden-eLife** [comment]
No problems on Continuum (not sure why the `(authors)` text is present, but that's a question for another day)
![Screenshot 2021-01-07 at 16 48 27](https://user-images.githubusercontent.com/43879983/103919711-44281d80-5108-11eb-931e-69c68dba8c14.png)
https://continuumtestpreview--journal.elifesciences.org/articles/54172v1#bib44
Will update the Schematron now to support either `pub-id` or `ext-link`.

**Comment by bcollins14** [comment]
Nothing more from me. I have just echoed (placed eyes) on two of Naushin's messages above. Thanks!

**Comment by JGilbert-eLife** [comment]
> Is it possible to clarify the difference between Publisher and Authority? That always trips me up in Kriya!

We're dropping assigning authority entirely, so this shouldn't matter. Publisher is the database name - I've corrected the list and table

**Comment by JGilbert-eLife** [comment]
OK, think I've nailed down the issue with the table.

Thanks @FAtherden-eLife - should I await revised Schematron messages?

**Comment by FAtherden-eLife** [comment]
Sorry should have said, changes are already made to the following tests:
- `pre-err-elem-cit-data-13-1`.
- `final-err-elem-cit-data-13-1`.
- `err-elem-cit-data-18`.

New test added:
- `elem-cit-data-pub-id-ext-link`.

I've just updated the spreadsheets.

**Comment by JGilbert-eLife** [comment]
@Melissa37 @naushinthomson @bcollins14 @FAtherden-eLife I've revised this page - are you happy with the edited version particularly re Website inclusion?

Thanks!

**Comment by Melissa37** [comment]
Sounds good to me, thanks!

**Comment by FAtherden-eLife** [comment]
:+1: from me - thanks

**Comment by bcollins14** [comment]
Looking good, ta!

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife Exeter have approved this page, so the links can be added to the schematron if they're not already in there. Thanks!

**Comment by FAtherden-eLife** [comment]
Thanks @JGilbert-eLife, just noting that I've removed `pre-err-elem-cit-data-17-1` and `final-err-elem-cit-data-17-1` from the Schematron and GitBook page, since these are duplicates of `err-elem-cit-data-13-1` (after some slight tweaking).
