### ISSUE TITLE
Create Preprint references page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#73]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by FAtherden-eLife** [comment]
@naushinthomson  @JGilbert-eLife @bcollins14 @Melissa37 Please review! https://app.gitbook.com/@elifesciences/s/schematron/v/master/article-details/content/references/pre-print-references

**Comment by FAtherden-eLife** [comment]
I've updated the link to remove a superfluous hyphen - it's now https://app.gitbook.com/@elifesciences/s/schematron/~/drafts/-MAgKbMr1PJtZFb8qg2J/v/master/article-details/content/references/preprint-references

**Comment by FAtherden-eLife** [comment]
Urgh I mean https://app.gitbook.com/@elifesciences/s/schematron/v/master/article-details/content/references/pre-print-references of course

**Comment by Melissa37** [comment]
>What needs to be added? table

In the URL field can you use a preprint server that does not use DOIs? 

There is an example from the JATS4R rec:

https://therapoid.net/en/preprint/manuscript-21/

I appreciate this is different to the rest of the example used, but as they are mutually exclusive and should not both be present and it applied to one without a DOI it kinda makes more sense?

**Comment by Melissa37** [comment]
>Validation of references via the Crossref API tool should pull in the information (preprints are not currently available on PubMed but they may be in the near-ish future)

Change to:

>Validation of references via the Crossref API tool should pull in the information for preprints with a Crossref DOI (currently only preprints from bioRxiv that are funded by NIH are indexed on PubMed so it is not a comprehensive list). Please note some preprint servers may use DataCite for their DOIs and so will not be listed in the Crossref API

**Comment by Melissa37** [comment]
>Please note that publication ids such as 2020.03.24.20043018 are not currently captured by eLife, but they will be in the future.

What does this refer to?

**Comment by Melissa37** [comment]
For later:

From JATS4R rec:
`<date date-type=”published”>` If you have more details than just the year, this should be used for full publication date of the preprint instead of `<year>`

This is to intentionally capture versions of preprints where the DOI does not change - much the same as for our versions of VoRs....but I think this will be dealt with more globally vis some other initiatives I am trying to push so this is for info only

**Comment by Melissa37** [comment]
>Once you have entered the information in the fields, click on 'Search Crossref' (preprints are not currently deposited to PubMed so searching PubMed will return no results, this is likely to change in the future though). This will compare the information entered to the Crossref database and ensures that a DOI is added (if there is one - not all preprints have DOIs).

Please change to:

>Once you have entered the information in the fields, click on 'Search Crossref' (only some preprints are indexed on PubMed but those that are have a Crossref DOI anyway so better to use Crossref). This will compare the information entered to the Crossref database and ensures that a DOI is added (some DOIs may be registered via DataCite and these will not appear in the Crossref API and some preprints do not have DOIs).

What should the user do to ensure they capture 
>DOIs may be registered via DataCite and these will not appear in the Crossref API and some preprints do not have DOIs
?

**Comment by Melissa37** [comment]
>
The minimum fields that need to be populated for the PubMed and CrossRef validators to find an article are:

First author name

Year

Title

Journal

Some preprint references will not appear when searching the CrossRef database (not all of them have DOIs). If you have entered the article details correctly and verified that it is the same in the original submitted version, you can just click on 'Insert Reference' to add the reference to the article.

Suggest changing to:

>
The minimum fields that need to be populated for the CrossRef validator to find an article are:

First author name

Year

Title

Journal

Some preprint references will not appear when searching the CrossRef database (not all of them have DOIs or are DataCite DOIs). If you have entered the article details correctly and verified that it is the same in the original submitted version, you can just click on 'Insert Reference' to add the reference to the article.

**Comment by Melissa37** [comment]
>These are the known preprint servers that are commonly cited in eLife articles. If this fires, check that the reference is actually a preprint. If it is, then this can be ignored (it is also worth notifying the production-schematron slack channel that this test needs updating to account for that reference). If it's not a preprint reference (such as a journal article for example), then it should be captured as an appropriate reference type.

Suggest changing 
>this test needs updating to account for that reference)

to
>this test needs updating to account for that preprint server)

**Comment by Melissa37** [comment]
>Action: This will fire if the preprint server (Journal field in Kriya, source element in the XML) contains the text biorxiv without the correct capitalisation, for example 'Biorxiv' or 'BiOrXiV'. Ensure that bioRxiv is added with the correct capitalisation. 

>Action: This will fire if the preprint server (Journal field in Kriya, source element in the XML) contains the text arxiv without the correct capitalisation, for example 'Arxiv' or 'ArXiV'. Ensure that arXiv is added with the correct capitalisation. 

>Action: This will fire if the preprint server (Journal field in Kriya, source element in the XML) contains the text ChemRxiv without the correct capitalisation, for example 'Chemrxiv' or 'ChEmRxIv'. Ensure that ChemRxiv is added with the correct capitalisation

>Action: This will fire if the preprint server (Journal field in Kriya, source element in the XML) contains the text medRxiv without the correct capitalisation, for example 'Medrxiv' or 'MeDRxiv'. Ensure that medRxiv is added with the correct capitalisation. 

contains the text XXX without the correct capitalisation - for the first two the text in XXX is all lower case, but in the last 2 it is as it should be presented. Suggest change the top to to as it should be presented, so consistent and also clearer.

**Comment by Melissa37** [comment]
>Action: This error will appear if a preprint reference has a preprint server (Journal field in Kriya, source element in the XML) that includes the word 'handbook'. This indicates that the reference should actually be a book reference instead of a preprint reference. Change the reference to a book reference (hyperlink to be added) and update the fields accordingly.

Are we confident no preprint server has the term handbook in its title? I am sure we are, but just wanted to flag it!!

**Comment by Melissa37** [comment]
>If the reference has more than one title, compare the details with the original submission to work out which is the correct title and enter that. 


Suggest changing to:

>If the reference has more than one title, compare the details with the original submission to work out which is the correct title and enter that, delete the extra title.

**Comment by Melissa37** [comment]
>Action: This will fire if a preprint reference contains more than one doi. Compare the details with the original submission, or search online to work out which is the correct doi and enter that. If that doesn't work, then this will have to corrected by Exeter.

Is it worth mentioning that the DOI might be to a VoR version published in a journal but if this ref is to the preprint the preprint DOI must be used?

**Comment by Melissa37** [comment]
>Action: This error will appear if there is no author list, or if authors have been tagged as other kinds of contributors (e.g. editors or curators). If there is no author list, make sure this is added by searching for the article details online. If there are contributors other than authors or collaborations, this means there has been an error in processing - Exeter will need to fix this.

>If there are contributors other than authors or collaborations, this means there has been an error in processing
Is this referring to the article in Kriya? It could be read that you cannot find the authors when searching online so a bit confusing?

**Comment by Melissa37** [comment]
>Action: This will fire if there is a <pub-id> element without the attribute pub-id-type='doi'. This will need to be corrected by Exeter.

Suggest changing to:
>Action: This will fire if there is a <pub-id> element without the attribute pub-id-type='doi'. The only pub-id value allowed is a DOI. Please check the value is a DOI. If not please delete and add a DOI or URL

Not sure about this though!

**Comment by FAtherden-eLife** [comment]
>> Please note that publication ids such as 2020.03.24.20043018 are not currently captured by eLife, but they will be in the future.

> What does this refer to?

This refers to the equivalent of elocation-ids in journal references, which in the latest JATS4R recs, they suggest capturing using `<pub-id pub-if-type="...">` (instead of `<elocation-id>`). Happy to change the wording if it's unclear.

**Comment by FAtherden-eLife** [comment]
>> Action: This error will appear if a preprint reference has a preprint server (Journal field in Kriya, source element in the XML) that includes the word 'handbook'. This indicates that the reference should actually be a book reference instead of a preprint reference. Change the reference to a book reference (hyperlink to be added) and update the fields accordingly.

> Are we confident no preprint server has the term handbook in its title? I am sure we are, but just wanted to flag it!!

I'm not, but was working on the assumption we could quickly downgrade it to a warning if we found one that did!

**Comment by Melissa37** [comment]
>>>Please note that publication ids such as 2020.03.24.20043018 are not currently captured by eLife, but they will be in the future.

>>What does this refer to?

>This refers to the equivalent of elocation-ids in journal references, which in the latest JATS4R recs, they suggest capturing using <pub-id pub-if-type="..."> (instead of <elocation-id>). Happy to change the wording if it's unclear.

I'm still confused - I cannot see this in the JATS4R Preprint rec? https://jats4r.org/preprint-citations

**Comment by FAtherden-eLife** [comment]
> 6. `<pub-id>`. Preprint articles should have a persistent identifier (PID). If there is no PID then the URL of the preprint article (see `<ext-link>` below) should be present.
> [[Validator tool result:  Error if no `<pub-id>` or `<ext-link>` present ]] 

> 7. `@pub-id-type` on `<pub-id>`. A typical id type will be “doi” or, for example “arxiv”

This is what I interpreted from the above. So, for [this preprint](https://arxiv.org/abs/1803.10016) you could capture '1803.10016' using `<pub-id pub-id-type="arxiv">1803.10016</pub-id>`:
```xml
<element-citation publication-type="preprint">
  <person-group person-group-type="author">
    <name>
      <surname>Treder</surname> <given-names>MS</given-names>
    </name>
  </person-group>
  <year iso-8601-date="2018">2018</year>
  <article-title>Cross-validation in high-dimensional spaces: a lifeline for least-squares models and multi-class LDA</article-title>
  <source>arXiv</source>
  <pub-id pub-id-type="arxiv">1803.10016</pub-id>
  <ext-link ext-link-type="uri" xlink:href="https://arxiv.org/abs/1803.10016">https://arxiv.org/abs/1803.10016</ext-link>
</element-citation>
```

The confusion might just be because I used the term elocation-id, which isn't necessarily the right terminology for preprints (although this is what biorxiv term it).

**Comment by Melissa37** [comment]
>The confusion might just be because I used the term elocation-id, which isn't necessarily the right terminology for preprints (although this is what biorxiv term it).

Yes, that's probably why. I think arxiv is the only other pub-id that's been identified and it's a PID, not an elocation.

Thanks!

**Comment by JGilbert-eLife** [comment]
"Schematron warnings may also pick them up and should be checked at source."

I'm not sure this is clear on what action is required. Is it about checking the full details for the article on the preprint page itself?

**Comment by JGilbert-eLife** [comment]
"Please note that publication ids such . . ."

For consistency with other reference types, would it be correct to refer to these as e-location IDs?

**Comment by JGilbert-eLife** [comment]
"Updating a preprint reference to a journal reference"

Is it worth giving an example here? If only to show how to update the reference fields/type.

**Comment by naushinthomson** [comment]
> "Schematron warnings may also pick them up and should be checked at source."
> 
> I'm not sure this is clear on what action is required. Is it about checking the full details for the article on the preprint page itself?

I guess this was pulled from the guidance on journal references: 
>Non-mandatory fields are required if they exist. Validation of references via PubMed or Crossref API tools should pull them in if the author did not provide them. Schematron warnings may also pick them up and should be checked at source.

Suggest changing to 
> Schematron warnings may also pick up incomplete references, and these should be checked at the source of the reference.
(And I will update the journal refs page to this also!)

**Comment by bcollins14** [comment]
I really like why you should pick crossref when adding references, did not know this!

**Comment by bcollins14** [comment]
Nothing else to add in addition to everyone else's comments. Good job :)
