### ISSUE TITLE
Create Periodical references page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#74]
- [ ] Create page 
- [ ] Add description of what is being covered
- [ ] Add description of checks required on this content, compiled from current protocol documents
- [ ] Add examples covering correct and incorrect scenarios, as required to support checks
- [ ] Populate with schematron messages
- [ ] Provide explanations for how to fix schematron errors and warnings
- [ ] Review house style document to ensure all requirements are covered by GitBook and schematron
- [ ] Review schematron messages related to this topic to ensure they are user friendly
- [ ] Becky approved page
- [ ] Melissa approved page
- [ ] Fred approved page
- [ ] James approved page
- [ ] Naushin approved page
- [ ] Claudia approved page
- [ ] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by Melissa37** [comment]
With Peter to check it's OK to ditch this reference type.

If it is, the following tests will need to be amended:
err-elem-cit-high-6-2

The following removed:

err-elem-cit-periodical-2-1 to err-elem-cit-periodical-14-7

**Comment by Melissa37** [comment]
If Ok to remove will need to ask Editorial to remove periodical from the reference table in author guide https://reviewer.elifesciences.org/author-guide/initial

**Comment by Melissa37** [comment]
@FAtherden-eLife Peter has agreed we can remove this ref type.

Actions:
- Delete the page on the Gitbook
- Delete the reference to it in the author guide
- delete the related schematron rules
- delete any references to it anywhere else on the GitBook.

Would you like me to take any of these actions?

**Comment by FAtherden-eLife** [comment]
Many thanks @Melissa37. Please could you delete the page? I am unable to do that (I don't have permission to merge in GitBook atm). I'll take on the rest.

**Comment by Melissa37** [comment]
I've deleted the page :-)
