### ISSUE TITLE
Create Report references page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#75]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [ ] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by FAtherden-eLife** [comment]
Typo in "What needs to be added?" table - `World Healt Organization`

**Comment by JGilbert-eLife** [comment]
I would suggest expanding on "It covers things like white papers and instructions from manufacturers."

"It covers things like annual reports, equipment specifications, manufacturer instructions, white papers, and so on."

**Comment by JGilbert-eLife** [comment]
I'd have classed warning-elem-cit-report-11-3 as a content check, I think, since it refers to what's in the field.

**Comment by JGilbert-eLife** [comment]
I also want to edit the XML to be indented correctly but cannot because it's not letting me generate a change request . . . ? This new interface is going to be frustrating.

**Comment by griffithsc** [comment]
Nothing other than that from me! All looks great. Thanks Melissa! :-)

**Comment by Melissa37** [comment]
@FAtherden-eLife with you to do the stuff before it's live live!
