### ISSUE TITLE
Create Deceased status page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#89]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by naushinthomson** [comment]
@bcollins14 @JGilbert-eLife @Melissa37 @FAtherden-eLife 

I think this [page](https://elifesciences.gitbook.io/productionhowto/-M1eY9ikxECYR-0OcnGt/article-details/people/deceased-status) is now complete (yay for a short one!). Let me know if anything further needs to be added!

**Comment by Melissa37** [comment]
>passes away

Suggest changing to "dies"

**Comment by Melissa37** [comment]
>To add a deceased footnote to an author, Exeter will need to update the contrib element with the attribute deceased="yes" and a footnote needs to be added in the author-notes section with an appropriate label (usually † unless this is already being used for another footnote).

Suggest changing "Exeter will need to update the contrib element with the attribute deceased="yes"" to
"Exeter will need to add the attribute deceased="yes" to the contrib element"

**Comment by Melissa37** [comment]
Might be worth adding this line:

On the eLife website the attribute on the contrib element drives the necessary display. However, some sites, such as PMC, require the additional footnote as well to display the deceased status.

@FAtherden-eLife and @JGilbert-eLife will we be changing this for Libero? I seem to recall we were not that worried about PMC display and were considering  removing the footnote?

**Comment by Melissa37** [comment]
Thanks Naushin - looks good - nice quick one!!

**Comment by bcollins14** [comment]
No further points to add, thanks Naushin!

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife and @JGilbert-eLife will we be changing this for Libero? I seem to recall we were not that worried about PMC display and were considering removing the footnote?

Yup, we're not including the footnote for Libero Editor - https://github.com/libero/editor/issues/32

**Comment by FAtherden-eLife** [comment]
It would be implicit in 'dies prior to publication' (as suggested by Melissa above), but would it be worth making it explicit that we do not publish new versions of articles in order to indicate someone has died.

**Comment by JGilbert-eLife** [comment]
"(usually † unless this is already being used for another footnote)" - I don't think this is really necessary? We have a standard string of footnote symbols and this footnote will just take the next available one in the list.

**Comment by JGilbert-eLife** [comment]
Nothing else to add, thanks!

**Comment by Melissa37** [comment]
@FAtherden-eLife Over to you for the Schematron updates!
Thanks
